# Generated by Django 3.2.5 on 2021-09-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210910_2023"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="creation_date",
        ),
    ]
