# Generated by Django 3.2.5 on 2021-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_checked",
            field=models.DateTimeField(blank=True, null=True, verbose_name="E-mail vérifie"),
        ),
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(max_length=250, verbose_name="Fonction"),
        ),
        migrations.AlterField(
            model_name="user",
            name="organism",
            field=models.CharField(
                choices=[
                    ("DDT", "DDT"),
                    ("DREAL", "DREAL"),
                    ("DEPART", "Département"),
                    ("REGION", "Région"),
                    ("SCOT", "SCOT"),
                    ("EPCI", "EPCI"),
                    ("COMMUN", "Commune"),
                    ("BUREAU", "Bureau d'études"),
                    ("AGENCE", "Agence d'urbanisme"),
                    ("AMENAG", "Aménageur"),
                    ("EPF", "EPF"),
                    ("GIP", "GIP"),
                    ("ASSOCI", "Association"),
                    ("PARTIC", "Particulier"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=250,
                verbose_name="Organisme",
            ),
        ),
    ]
