# Generated by Django 3.2.5 on 2021-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20210914_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("AMENAG", "Aménageur"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DEPART", "Département"),
                    ("DREAL", "DREAL"),
                    ("EPCI", "EPCI"),
                    ("EPF", "EPF"),
                    ("GIP", "GIP"),
                    ("PARTIC", "Particulier"),
                    ("REGION", "Région"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=250,
                verbose_name="Organisme",
            ),
        ),
    ]
