# Generated by Django 4.2.13 on 2024-07-18 12:08

from django.db import migrations


def set_created_and_update_at_to_none(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.update(created_at=None, updated_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_created_at_user_updated_at"),
    ]

    operations = [migrations.RunPython(set_created_and_update_at_to_none)]
