# Generated by Django 4.2.13 on 2024-09-30 09:17

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_auto_20240718_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150, validators=[utils.validators.is_alpha_validator], verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(
                max_length=250, validators=[utils.validators.is_alpha_validator], verbose_name="Fonction"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150, validators=[utils.validators.is_alpha_validator], verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DDTM", "DDTM"),
                    ("DEAL", "DEAL"),
                    ("DREAL", "DREAL"),
                    ("DRIEAT", "DRIEAT"),
                    ("EPCI", "EPCI"),
                    ("PARTIC", "Particulier"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=250,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Organisme",
            ),
        ),
    ]
