# Generated by Django 4.2.13 on 2024-09-30 09:48

from django.db import migrations
from utils.validators import is_alpha_valid


def remove_invalid_user_inputs(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        if not is_alpha_valid(user.first_name):
            user.first_name = "empty"
        if not is_alpha_valid(user.last_name):
            user.last_name = "empty"
        if not is_alpha_valid(user.function):
            user.function = "empty"
        if not is_alpha_valid(user.organism):
            user.organism = "COMMUN"
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_user_first_name_alter_user_function_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_invalid_user_inputs),
    ]
