# Generated by Django 4.2.13 on 2024-11-26 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_user_email_ci_uniqueness"),
        ("users", "0015_auto_20240930_1148"),
    ]

    operations = []
