# Generated by Django 4.2.13 on 2025-01-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0016_merge_20241126_1219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="users", to="auth.group"),
        ),
    ]
