# Generated by Django 4.2.20 on 2025-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organism_group",
        ),
        migrations.AddField(
            model_name="user",
            name="main_land_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant unique du territoire principal de l'utilisateur.",
                max_length=255,
                null=True,
                verbose_name="Identifiant du territoire principal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="main_land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                ],
                help_text="Indique le niveau administratif du territoire principal de l'utilisateur. Cela va de la commune à la région.",
                max_length=7,
                null=True,
                verbose_name="Type de territoire principal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMENAGEMENT_URBANISME_ET_PAYSAGE", "Aménagement Urbanisme et Paysage"),
                    ("ETUDES_ET_EVALUATIONS", "Etudes et évaluations"),
                    ("SECURITE_PREVENTION_ET_GESTION_DES_RISQUES", "Sécurité Prévention et Gestion des Risques"),
                    (
                        "ELABORATION_ET_PILOTAGE_DE_POLITIQUES_PUBLIQUES",
                        "Elaboration et pilotage de politiques publiques",
                    ),
                    ("RESSOURCES_NATURELLES_ET_BIODIVERSITE", "Ressources naturelles et biodiversité"),
                    ("HABITAT_LOGEMENT", "Habitat Logement"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Service*",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="siret",
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="SIRET"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail (Identifiant)"),
        ),
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESPONSABLE_URBANISME", "Chargé(e) ou responsable de mission urbanisme"),
                    ("RESPONSABLE_PLANIFICATION", "Chargé(e) ou responsable de planification"),
                    ("RESPONSABLE_AMENAGEMENT", "Chargé(e) aménagement"),
                    ("SECRETAIRE_MAIRIE", "Secrétaire de mairie (commune)"),
                    ("ELU", "Élu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Fonction*",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organism",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMUNE", "Commune"),
                    ("EPCI", "EPCI"),
                    ("SCOT", "SCoT"),
                    ("SERVICES_REGIONAUX", "DREAL / DRIEAT / DRIHL"),
                    ("SERVICES_DEPARTEMENTAUX", "DDT / DDTM / DEAL"),
                    ("EXPERTS_URBANISTES", "Bureaux d'études / Agence d'urbanisme"),
                    ("ACTEURS_CITOYENS", "Association / Particulier"),
                ],
                max_length=250,
                null=True,
                verbose_name="Organisme",
            ),
        ),
    ]
