# Generated by Django 4.2.20 on 2025-04-17 09:05

from django.db import migrations


def reset_user_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(
        organism=None,
        function=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_user_organism_group_user_main_land_id_and_more"),
    ]

    operations = [
        migrations.RunPython(reset_user_data),
    ]
