# Generated by Django 4.2.20 on 2025-05-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_reset_organism_and_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proconnect",
            field=models.BooleanField(default=False, verbose_name="Proconnect"),
        ),
    ]
