# Generated by Django 5.2.9 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_proconnect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="main_land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                help_text="Indique le niveau administratif du territoire principal de l'utilisateur. Cela va de la commune à la région.",
                max_length=7,
                null=True,
                verbose_name="Type de territoire principal",
            ),
        ),
    ]
