from enum import StrEnum


class ProjectChangeReason(StrEnum):
    USER_UPDATED_PROJECT_FROM_PARAMS = "USER_UPDATED_PROJECT_FROM_PARAMS"
    USER_CLAIMED_PROJECT = "USER_CLAIMED_PROJECT"
    USER_ADDED_A_LOOK_A_LIKE = "USER_ADDED_A_LOOK_A_LIKE"
    USER_REMOVED_A_LOOK_A_LIKE = "USER_REMOVED_A_LOOK_A_LIKE"

    NEW_OCSGE_HAS_BEEN_DELIVERED = "NEW_OCSGE_HAS_BEEN_DELIVERED"
    FOLDER_CHANGED = "FOLDER_CHANGED"
    CREATED_FROM_PUBLIC_KEY = "CREATED_FROM_PUBLIC_KEY"
