
version: 2

type_de_changement: &type_de_changement
  values : [
    10, # Changement de nom
    20, # Création
    21, # Rétablissement
    30, # Suppression
    31, # Fusion simple
    32, # Création de commune nouvelle
    33, # Fusion association
    34, # Transformation de fusion association en fusion simple
    35, # Suppression de commune déléguée
    41, # Changement de code dû à un changement de département
    50, # Changement de code dû à un transfert de chef-lieu
    70, # Transformation de commune associée en commune déléguée
    71  # 71 is not in the official list but is present in the data
  ]

type_commune: &type_commune
  values : [
    "COM", # Commune
    "COMA", # Commune associée
    "COMD", # Commune déléguée
    "ARM" # Arrondissement municipal
  ]

models:
  - name: cog_changes_2024
    columns:
      - name: type_de_changement
        data_tests:
          - accepted_values: *type_de_changement
      - name: type_commune_avant
        data_tests:
          - accepted_values: *type_commune
      - name: type_commune_apres
        data_tests:
          - accepted_values: *type_commune
  - name: population_cog_2024
    columns:
      - name: code_commune
        data_tests:
          - not_null
          - unique
          - has_all_communes
          - relationships:
              to: ref('commune')
              field: code
  - name: flux_population_departements
    columns:
      - name: departement
        data_tests:
          - not_null
          - unique
          - has_all_departements
          - relationships:
              to: ref('departement')
              field: code
  - name: flux_population_regions
    columns:
      - name: region
        data_tests:
          - not_null
          - unique
          - has_all_regions
          - relationships:
              to: ref('region')
              field: code
  - name: flux_population_scots
    columns:
      - name: scot
        data_tests:
          - not_null
          - unique
          - has_all_scots
          - relationships:
              to: ref('scot')
              field: id_scot
  - name: flux_population_epcis
    columns:
      - name: epci
        data_tests:
          - not_null
          - unique
          - has_all_epcis
          - relationships:
              to: ref('epci')
              field: code
  - name: flux_population
    columns:
      - name: code_commune
        data_tests:
          - not_null
          - unique
          - has_all_communes
          - relationships:
              to: ref('commune')
              field: code
  - name: stock_population_departements
    columns:
      - name: departement
        data_tests:
          - not_null
          - unique
          - has_all_departements
          - relationships:
              to: ref('departement')
              field: code
  - name: stock_population_regions
    columns:
      - name: region
        data_tests:
          - not_null
          - unique
          - has_all_regions
          - relationships:
              to: ref('region')
              field: code
  - name: stock_population_epcis
    columns:
      - name: epci
        data_tests:
          - not_null
          - unique
          - has_all_epcis
          - relationships:
              to: ref('epci')
              field: code
  - name: stock_population_scots
    columns:
      - name: scot
        data_tests:
          - not_null
          - unique
          - has_all_scots
          - relationships:
              to: ref('scot')
              field: id_scot

sources:
  - name: public
    tables:
    - name: insee_cog_changes_2024
    - name: insee_population
