services:
  db:
    image: kartoza/postgis:17-3.5
    shm_size: 1gb
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5555:5432"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  s3:
    image: versity/versitygw:latest
    command: ["posix", "/data"]
    environment:
      - ROOT_ACCESS_KEY=localaccess
      - ROOT_SECRET_KEY=localsecret
    ports:
      - "7070:7070"
    volumes:
      - s3_data:/data
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: sparte/frontend:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    networks:
      - app-network

  export-server:
    build: ./export
    image: sparte/export-server:latest
    environment:
      - PORT=3000
      - ALLOWED_HOSTS=localhost,django,frontend
    depends_on:
      - frontend
    networks:
      - app-network

  django:
    build: .
    image: sparte/backend:latest
    command: ["sh", "-c", "python manage.py migrate && python manage.py load_param --no-update --file required_parameters.json && python manage.py runserver 0.0.0.0:8080 --nothreading"]
    volumes:
      - .:/app
    env_file: .env
    environment:
      - SCALINGO_REDIS_URL=redis://redis:6379/0
      - EXPORT_SERVER_URL=http://export-server:3000
      - EXPORT_BASE_URL=http://django:8080
      - AWS_S3_ENDPOINT_URL=http://s3:7070
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - s3
      - export-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  s3_data:
