version: 2

models:
  - name: flux_population_region
    columns:
      - name: region
        data_tests:
          - not_null
          - has_all_regions
          - relationships:
              to: ref('region')
              field: code
