version: 2

models:
  - name: flux_population_scot
    columns:
      - name: scot
        data_tests:
          - not_null
          - has_all_scots
          - relationships:
              to: ref('scot')
              field: id_scot
