version: 2
models:
  - name: flux_population_departement
    columns:
      - name: departement
        data_tests:
          - not_null
          - has_all_departements
          - relationships:
              to: ref('departement')
              field: code
