from django.db import models

from public_data.models.administration import AdminRef


class LandDcEmploisLieuTravail(models.Model):
    land_id = models.CharField()
    land_type = models.CharField(choices=AdminRef.CHOICES)

    # year 22 - p_names
    emplois_22 = models.FloatField(null=True)
    emplois_salaries_22 = models.FloatField(null=True)
    emplois_salaries_femmes_22 = models.FloatField(null=True)
    emplois_salaries_temps_partiel_22 = models.FloatField(null=True)
    emplois_non_salaries_22 = models.FloatField(null=True)
    emplois_non_salaries_femmes_22 = models.FloatField(null=True)
    emplois_non_salaries_temps_partiel_22 = models.FloatField(null=True)
    # year 22 - c_names
    c_emplois_22 = models.FloatField(null=True)
    c_emplois_agriculteurs_22 = models.FloatField(null=True)
    c_emplois_artisans_commercants_22 = models.FloatField(null=True)
    c_emplois_cadres_22 = models.FloatField(null=True)
    c_emplois_prof_intermediaires_22 = models.FloatField(null=True)
    c_emplois_employes_22 = models.FloatField(null=True)
    c_emplois_ouvriers_22 = models.FloatField(null=True)
    c_emplois_agriculture_22 = models.FloatField(null=True)
    c_emplois_industrie_22 = models.FloatField(null=True)
    c_emplois_construction_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_22 = models.FloatField(null=True)
    c_emplois_femmes_22 = models.FloatField(null=True)
    c_emplois_agriculture_femmes_22 = models.FloatField(null=True)
    c_emplois_industrie_femmes_22 = models.FloatField(null=True)
    c_emplois_construction_femmes_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_femmes_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_femmes_22 = models.FloatField(null=True)
    c_emplois_salaries_22 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_22 = models.FloatField(null=True)
    c_emplois_industrie_salaries_22 = models.FloatField(null=True)
    c_emplois_construction_salaries_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_22 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_industrie_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_construction_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_22 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_22 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_22 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_femmes_22 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_femmes_22 = models.FloatField(null=True)

    # year 16 - p_names
    emplois_16 = models.FloatField(null=True)
    emplois_salaries_16 = models.FloatField(null=True)
    emplois_salaries_femmes_16 = models.FloatField(null=True)
    emplois_salaries_temps_partiel_16 = models.FloatField(null=True)
    emplois_non_salaries_16 = models.FloatField(null=True)
    emplois_non_salaries_femmes_16 = models.FloatField(null=True)
    emplois_non_salaries_temps_partiel_16 = models.FloatField(null=True)
    # year 16 - c_names
    c_emplois_16 = models.FloatField(null=True)
    c_emplois_agriculteurs_16 = models.FloatField(null=True)
    c_emplois_artisans_commercants_16 = models.FloatField(null=True)
    c_emplois_cadres_16 = models.FloatField(null=True)
    c_emplois_prof_intermediaires_16 = models.FloatField(null=True)
    c_emplois_employes_16 = models.FloatField(null=True)
    c_emplois_ouvriers_16 = models.FloatField(null=True)
    c_emplois_agriculture_16 = models.FloatField(null=True)
    c_emplois_industrie_16 = models.FloatField(null=True)
    c_emplois_construction_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_16 = models.FloatField(null=True)
    c_emplois_femmes_16 = models.FloatField(null=True)
    c_emplois_agriculture_femmes_16 = models.FloatField(null=True)
    c_emplois_industrie_femmes_16 = models.FloatField(null=True)
    c_emplois_construction_femmes_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_femmes_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_femmes_16 = models.FloatField(null=True)
    c_emplois_salaries_16 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_16 = models.FloatField(null=True)
    c_emplois_industrie_salaries_16 = models.FloatField(null=True)
    c_emplois_construction_salaries_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_16 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_industrie_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_construction_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_16 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_16 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_16 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_femmes_16 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_femmes_16 = models.FloatField(null=True)

    # year 11 - p_names
    emplois_11 = models.FloatField(null=True)
    emplois_salaries_11 = models.FloatField(null=True)
    emplois_salaries_femmes_11 = models.FloatField(null=True)
    emplois_salaries_temps_partiel_11 = models.FloatField(null=True)
    emplois_non_salaries_11 = models.FloatField(null=True)
    emplois_non_salaries_femmes_11 = models.FloatField(null=True)
    emplois_non_salaries_temps_partiel_11 = models.FloatField(null=True)
    # year 11 - c_names
    c_emplois_11 = models.FloatField(null=True)
    c_emplois_agriculteurs_11 = models.FloatField(null=True)
    c_emplois_artisans_commercants_11 = models.FloatField(null=True)
    c_emplois_cadres_11 = models.FloatField(null=True)
    c_emplois_prof_intermediaires_11 = models.FloatField(null=True)
    c_emplois_employes_11 = models.FloatField(null=True)
    c_emplois_ouvriers_11 = models.FloatField(null=True)
    c_emplois_agriculture_11 = models.FloatField(null=True)
    c_emplois_industrie_11 = models.FloatField(null=True)
    c_emplois_construction_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_11 = models.FloatField(null=True)
    c_emplois_femmes_11 = models.FloatField(null=True)
    c_emplois_agriculture_femmes_11 = models.FloatField(null=True)
    c_emplois_industrie_femmes_11 = models.FloatField(null=True)
    c_emplois_construction_femmes_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_femmes_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_femmes_11 = models.FloatField(null=True)
    c_emplois_salaries_11 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_11 = models.FloatField(null=True)
    c_emplois_industrie_salaries_11 = models.FloatField(null=True)
    c_emplois_construction_salaries_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_11 = models.FloatField(null=True)
    c_emplois_agriculture_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_industrie_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_construction_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_11 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_11 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_11 = models.FloatField(null=True)
    c_emplois_agriculture_non_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_industrie_non_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_construction_non_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_commerce_transports_services_non_salaries_femmes_11 = models.FloatField(null=True)
    c_emplois_admin_enseignement_sante_non_salaries_femmes_11 = models.FloatField(null=True)

    class Meta:
        managed = False
        db_table = "public_data_dc_emplois_lieu_travail"
