from django.db import models

from public_data.models.administration import AdminRef


class LandDcScolarisationDiplomes(models.Model):
    land_id = models.CharField()
    land_type = models.CharField(choices=AdminRef.CHOICES)

    # scol_names x years 22, 16, 11
    pop_2_5_22 = models.FloatField(null=True)
    pop_6_10_22 = models.FloatField(null=True)
    pop_11_14_22 = models.FloatField(null=True)
    pop_15_17_22 = models.FloatField(null=True)
    pop_18_24_22 = models.FloatField(null=True)
    pop_25_29_22 = models.FloatField(null=True)
    pop_30_plus_22 = models.FloatField(null=True)
    scol_2_5_22 = models.FloatField(null=True)
    scol_6_10_22 = models.FloatField(null=True)
    scol_11_14_22 = models.FloatField(null=True)
    scol_15_17_22 = models.FloatField(null=True)
    scol_18_24_22 = models.FloatField(null=True)
    scol_25_29_22 = models.FloatField(null=True)
    scol_30_plus_22 = models.FloatField(null=True)

    pop_2_5_16 = models.FloatField(null=True)
    pop_6_10_16 = models.FloatField(null=True)
    pop_11_14_16 = models.FloatField(null=True)
    pop_15_17_16 = models.FloatField(null=True)
    pop_18_24_16 = models.FloatField(null=True)
    pop_25_29_16 = models.FloatField(null=True)
    pop_30_plus_16 = models.FloatField(null=True)
    scol_2_5_16 = models.FloatField(null=True)
    scol_6_10_16 = models.FloatField(null=True)
    scol_11_14_16 = models.FloatField(null=True)
    scol_15_17_16 = models.FloatField(null=True)
    scol_18_24_16 = models.FloatField(null=True)
    scol_25_29_16 = models.FloatField(null=True)
    scol_30_plus_16 = models.FloatField(null=True)

    pop_2_5_11 = models.FloatField(null=True)
    pop_6_10_11 = models.FloatField(null=True)
    pop_11_14_11 = models.FloatField(null=True)
    pop_15_17_11 = models.FloatField(null=True)
    pop_18_24_11 = models.FloatField(null=True)
    pop_25_29_11 = models.FloatField(null=True)
    pop_30_plus_11 = models.FloatField(null=True)
    scol_2_5_11 = models.FloatField(null=True)
    scol_6_10_11 = models.FloatField(null=True)
    scol_11_14_11 = models.FloatField(null=True)
    scol_15_17_11 = models.FloatField(null=True)
    scol_18_24_11 = models.FloatField(null=True)
    scol_25_29_11 = models.FloatField(null=True)
    scol_30_plus_11 = models.FloatField(null=True)

    # dipl_22
    non_scol_15_plus_22 = models.FloatField(null=True)
    non_scol_sans_diplome_22 = models.FloatField(null=True)
    non_scol_bepc_22 = models.FloatField(null=True)
    non_scol_cap_bep_22 = models.FloatField(null=True)
    non_scol_bac_22 = models.FloatField(null=True)
    non_scol_bac_plus_2_22 = models.FloatField(null=True)
    non_scol_bac_plus_3_4_22 = models.FloatField(null=True)
    non_scol_bac_plus_5_22 = models.FloatField(null=True)
    hommes_non_scol_15_plus_22 = models.FloatField(null=True)
    hommes_non_scol_sans_diplome_22 = models.FloatField(null=True)
    hommes_non_scol_bepc_22 = models.FloatField(null=True)
    hommes_non_scol_cap_bep_22 = models.FloatField(null=True)
    hommes_non_scol_bac_22 = models.FloatField(null=True)
    hommes_non_scol_bac_plus_2_22 = models.FloatField(null=True)
    hommes_non_scol_bac_plus_3_4_22 = models.FloatField(null=True)
    hommes_non_scol_bac_plus_5_22 = models.FloatField(null=True)
    femmes_non_scol_15_plus_22 = models.FloatField(null=True)
    femmes_non_scol_sans_diplome_22 = models.FloatField(null=True)
    femmes_non_scol_bepc_22 = models.FloatField(null=True)
    femmes_non_scol_cap_bep_22 = models.FloatField(null=True)
    femmes_non_scol_bac_22 = models.FloatField(null=True)
    femmes_non_scol_bac_plus_2_22 = models.FloatField(null=True)
    femmes_non_scol_bac_plus_3_4_22 = models.FloatField(null=True)
    femmes_non_scol_bac_plus_5_22 = models.FloatField(null=True)

    # dipl_16
    non_scol_15_plus_16 = models.FloatField(null=True)
    non_scol_sans_diplome_16 = models.FloatField(null=True)
    non_scol_cap_bep_16 = models.FloatField(null=True)
    non_scol_bac_16 = models.FloatField(null=True)
    non_scol_sup_16 = models.FloatField(null=True)
    hommes_non_scol_15_plus_16 = models.FloatField(null=True)
    hommes_non_scol_sans_diplome_16 = models.FloatField(null=True)
    hommes_non_scol_cap_bep_16 = models.FloatField(null=True)
    hommes_non_scol_bac_16 = models.FloatField(null=True)
    hommes_non_scol_sup_16 = models.FloatField(null=True)
    femmes_non_scol_15_plus_16 = models.FloatField(null=True)
    femmes_non_scol_sans_diplome_16 = models.FloatField(null=True)
    femmes_non_scol_cap_bep_16 = models.FloatField(null=True)
    femmes_non_scol_bac_16 = models.FloatField(null=True)
    femmes_non_scol_sup_16 = models.FloatField(null=True)

    # dipl_11
    non_scol_15_plus_11 = models.FloatField(null=True)
    non_scol_aucun_diplome_11 = models.FloatField(null=True)
    non_scol_cep_11 = models.FloatField(null=True)
    non_scol_bepc_11 = models.FloatField(null=True)
    non_scol_cap_bep_11 = models.FloatField(null=True)
    non_scol_bac_11 = models.FloatField(null=True)
    non_scol_bac_plus_2_11 = models.FloatField(null=True)
    non_scol_sup_11 = models.FloatField(null=True)
    hommes_non_scol_15_plus_11 = models.FloatField(null=True)
    hommes_non_scol_aucun_diplome_11 = models.FloatField(null=True)
    hommes_non_scol_cep_11 = models.FloatField(null=True)
    hommes_non_scol_bepc_11 = models.FloatField(null=True)
    hommes_non_scol_cap_bep_11 = models.FloatField(null=True)
    hommes_non_scol_bac_11 = models.FloatField(null=True)
    hommes_non_scol_bac_plus_2_11 = models.FloatField(null=True)
    hommes_non_scol_sup_11 = models.FloatField(null=True)
    femmes_non_scol_15_plus_11 = models.FloatField(null=True)
    femmes_non_scol_aucun_diplome_11 = models.FloatField(null=True)
    femmes_non_scol_cep_11 = models.FloatField(null=True)
    femmes_non_scol_bepc_11 = models.FloatField(null=True)
    femmes_non_scol_cap_bep_11 = models.FloatField(null=True)
    femmes_non_scol_bac_11 = models.FloatField(null=True)
    femmes_non_scol_bac_plus_2_11 = models.FloatField(null=True)
    femmes_non_scol_sup_11 = models.FloatField(null=True)

    class Meta:
        managed = False
        db_table = "public_data_dc_scolarisation_diplomes"
