from django.db import models

from public_data.models.administration import AdminRef


class LandDcLogementConfort(models.Model):
    land_id = models.CharField()
    land_type = models.CharField(choices=AdminRef.CHOICES)

    # p_names x year 22
    rp_chauffage_gaz_ville_22 = models.FloatField(null=True)
    rp_chauffage_fioul_22 = models.FloatField(null=True)
    rp_chauffage_electricite_22 = models.FloatField(null=True)
    rp_chauffage_gaz_bouteille_22 = models.FloatField(null=True)
    rp_chauffage_autre_22 = models.FloatField(null=True)
    rp_bain_douche_wc_22 = models.FloatField(null=True)
    rp_chauffe_eau_solaire_22 = models.FloatField(null=True)
    rp_climatisation_22 = models.FloatField(null=True)
    rp_tout_a_egout_22 = models.FloatField(null=True)
    rp_habitations_fortune_22 = models.FloatField(null=True)
    rp_cases_traditionnelles_22 = models.FloatField(null=True)
    rp_maisons_bois_22 = models.FloatField(null=True)
    rp_maisons_dur_22 = models.FloatField(null=True)
    rp_1_piece_22 = models.FloatField(null=True)
    rp_2_pieces_22 = models.FloatField(null=True)
    rp_3_pieces_22 = models.FloatField(null=True)
    rp_4_pieces_22 = models.FloatField(null=True)
    rp_5_pieces_plus_22 = models.FloatField(null=True)
    anciennete_rp_22 = models.FloatField(null=True)
    anciennete_rp_proprietaires_22 = models.FloatField(null=True)
    anciennete_rp_locataires_22 = models.FloatField(null=True)
    anciennete_rp_hlm_22 = models.FloatField(null=True)
    anciennete_rp_gratuit_22 = models.FloatField(null=True)
    # c_names x year 22
    rp_occupation_normale_22 = models.FloatField(null=True)
    rp_sous_occupation_moderee_22 = models.FloatField(null=True)
    rp_sous_occupation_accentuee_22 = models.FloatField(null=True)
    rp_sous_occupation_tres_accentuee_22 = models.FloatField(null=True)
    rp_suroccupation_moderee_22 = models.FloatField(null=True)
    rp_suroccupation_accentuee_22 = models.FloatField(null=True)

    # p_names x year 16
    rp_chauffage_gaz_ville_16 = models.FloatField(null=True)
    rp_chauffage_fioul_16 = models.FloatField(null=True)
    rp_chauffage_electricite_16 = models.FloatField(null=True)
    rp_chauffage_gaz_bouteille_16 = models.FloatField(null=True)
    rp_chauffage_autre_16 = models.FloatField(null=True)
    rp_bain_douche_wc_16 = models.FloatField(null=True)
    rp_chauffe_eau_solaire_16 = models.FloatField(null=True)
    rp_climatisation_16 = models.FloatField(null=True)
    rp_tout_a_egout_16 = models.FloatField(null=True)
    rp_habitations_fortune_16 = models.FloatField(null=True)
    rp_cases_traditionnelles_16 = models.FloatField(null=True)
    rp_maisons_bois_16 = models.FloatField(null=True)
    rp_maisons_dur_16 = models.FloatField(null=True)
    rp_1_piece_16 = models.FloatField(null=True)
    rp_2_pieces_16 = models.FloatField(null=True)
    rp_3_pieces_16 = models.FloatField(null=True)
    rp_4_pieces_16 = models.FloatField(null=True)
    rp_5_pieces_plus_16 = models.FloatField(null=True)
    anciennete_rp_16 = models.FloatField(null=True)
    anciennete_rp_proprietaires_16 = models.FloatField(null=True)
    anciennete_rp_locataires_16 = models.FloatField(null=True)
    anciennete_rp_hlm_16 = models.FloatField(null=True)
    anciennete_rp_gratuit_16 = models.FloatField(null=True)
    # c_names x year 16
    rp_occupation_normale_16 = models.FloatField(null=True)
    rp_sous_occupation_moderee_16 = models.FloatField(null=True)
    rp_sous_occupation_accentuee_16 = models.FloatField(null=True)
    rp_sous_occupation_tres_accentuee_16 = models.FloatField(null=True)
    rp_suroccupation_moderee_16 = models.FloatField(null=True)
    rp_suroccupation_accentuee_16 = models.FloatField(null=True)

    # p_names x year 11
    rp_chauffage_gaz_ville_11 = models.FloatField(null=True)
    rp_chauffage_fioul_11 = models.FloatField(null=True)
    rp_chauffage_electricite_11 = models.FloatField(null=True)
    rp_chauffage_gaz_bouteille_11 = models.FloatField(null=True)
    rp_chauffage_autre_11 = models.FloatField(null=True)
    rp_bain_douche_wc_11 = models.FloatField(null=True)
    rp_chauffe_eau_solaire_11 = models.FloatField(null=True)
    rp_climatisation_11 = models.FloatField(null=True)
    rp_tout_a_egout_11 = models.FloatField(null=True)
    rp_habitations_fortune_11 = models.FloatField(null=True)
    rp_cases_traditionnelles_11 = models.FloatField(null=True)
    rp_maisons_bois_11 = models.FloatField(null=True)
    rp_maisons_dur_11 = models.FloatField(null=True)
    rp_1_piece_11 = models.FloatField(null=True)
    rp_2_pieces_11 = models.FloatField(null=True)
    rp_3_pieces_11 = models.FloatField(null=True)
    rp_4_pieces_11 = models.FloatField(null=True)
    rp_5_pieces_plus_11 = models.FloatField(null=True)
    anciennete_rp_11 = models.FloatField(null=True)
    anciennete_rp_proprietaires_11 = models.FloatField(null=True)
    anciennete_rp_locataires_11 = models.FloatField(null=True)
    anciennete_rp_hlm_11 = models.FloatField(null=True)
    anciennete_rp_gratuit_11 = models.FloatField(null=True)
    # c_names x year 11
    rp_occupation_normale_11 = models.FloatField(null=True)
    rp_sous_occupation_moderee_11 = models.FloatField(null=True)
    rp_sous_occupation_accentuee_11 = models.FloatField(null=True)
    rp_sous_occupation_tres_accentuee_11 = models.FloatField(null=True)
    rp_suroccupation_moderee_11 = models.FloatField(null=True)
    rp_suroccupation_accentuee_11 = models.FloatField(null=True)

    class Meta:
        managed = False
        db_table = "public_data_dc_logement_confort"
