from django.db import models

from public_data.models.administration import AdminRef


class LandDcSituationConjugale(models.Model):
    land_id = models.CharField()
    land_type = models.CharField(choices=AdminRef.CHOICES)

    # common_names x years 22, 16, 11
    pop_15_plus_22 = models.FloatField(null=True)
    pop_15_19_22 = models.FloatField(null=True)
    pop_20_24_22 = models.FloatField(null=True)
    pop_25_39_22 = models.FloatField(null=True)
    pop_40_54_22 = models.FloatField(null=True)
    pop_55_64_22 = models.FloatField(null=True)
    pop_65_79_22 = models.FloatField(null=True)
    pop_80_plus_22 = models.FloatField(null=True)
    pop_menages_15_19_22 = models.FloatField(null=True)
    pop_menages_20_24_22 = models.FloatField(null=True)
    pop_menages_25_39_22 = models.FloatField(null=True)
    pop_menages_40_54_22 = models.FloatField(null=True)
    pop_menages_55_64_22 = models.FloatField(null=True)
    pop_menages_65_79_22 = models.FloatField(null=True)
    pop_menages_80_plus_22 = models.FloatField(null=True)
    pop_15_19_seul_22 = models.FloatField(null=True)
    pop_20_24_seul_22 = models.FloatField(null=True)
    pop_25_39_seul_22 = models.FloatField(null=True)
    pop_40_54_seul_22 = models.FloatField(null=True)
    pop_55_64_seul_22 = models.FloatField(null=True)
    pop_65_79_seul_22 = models.FloatField(null=True)
    pop_80_plus_seul_22 = models.FloatField(null=True)
    pop_15_19_couple_22 = models.FloatField(null=True)
    pop_20_24_couple_22 = models.FloatField(null=True)
    pop_25_39_couple_22 = models.FloatField(null=True)
    pop_40_54_couple_22 = models.FloatField(null=True)
    pop_55_64_couple_22 = models.FloatField(null=True)
    pop_65_79_couple_22 = models.FloatField(null=True)
    pop_80_plus_couple_22 = models.FloatField(null=True)

    pop_15_plus_16 = models.FloatField(null=True)
    pop_15_19_16 = models.FloatField(null=True)
    pop_20_24_16 = models.FloatField(null=True)
    pop_25_39_16 = models.FloatField(null=True)
    pop_40_54_16 = models.FloatField(null=True)
    pop_55_64_16 = models.FloatField(null=True)
    pop_65_79_16 = models.FloatField(null=True)
    pop_80_plus_16 = models.FloatField(null=True)
    pop_menages_15_19_16 = models.FloatField(null=True)
    pop_menages_20_24_16 = models.FloatField(null=True)
    pop_menages_25_39_16 = models.FloatField(null=True)
    pop_menages_40_54_16 = models.FloatField(null=True)
    pop_menages_55_64_16 = models.FloatField(null=True)
    pop_menages_65_79_16 = models.FloatField(null=True)
    pop_menages_80_plus_16 = models.FloatField(null=True)
    pop_15_19_seul_16 = models.FloatField(null=True)
    pop_20_24_seul_16 = models.FloatField(null=True)
    pop_25_39_seul_16 = models.FloatField(null=True)
    pop_40_54_seul_16 = models.FloatField(null=True)
    pop_55_64_seul_16 = models.FloatField(null=True)
    pop_65_79_seul_16 = models.FloatField(null=True)
    pop_80_plus_seul_16 = models.FloatField(null=True)
    pop_15_19_couple_16 = models.FloatField(null=True)
    pop_20_24_couple_16 = models.FloatField(null=True)
    pop_25_39_couple_16 = models.FloatField(null=True)
    pop_40_54_couple_16 = models.FloatField(null=True)
    pop_55_64_couple_16 = models.FloatField(null=True)
    pop_65_79_couple_16 = models.FloatField(null=True)
    pop_80_plus_couple_16 = models.FloatField(null=True)

    pop_15_plus_11 = models.FloatField(null=True)
    pop_15_19_11 = models.FloatField(null=True)
    pop_20_24_11 = models.FloatField(null=True)
    pop_25_39_11 = models.FloatField(null=True)
    pop_40_54_11 = models.FloatField(null=True)
    pop_55_64_11 = models.FloatField(null=True)
    pop_65_79_11 = models.FloatField(null=True)
    pop_80_plus_11 = models.FloatField(null=True)
    pop_menages_15_19_11 = models.FloatField(null=True)
    pop_menages_20_24_11 = models.FloatField(null=True)
    pop_menages_25_39_11 = models.FloatField(null=True)
    pop_menages_40_54_11 = models.FloatField(null=True)
    pop_menages_55_64_11 = models.FloatField(null=True)
    pop_menages_65_79_11 = models.FloatField(null=True)
    pop_menages_80_plus_11 = models.FloatField(null=True)
    pop_15_19_seul_11 = models.FloatField(null=True)
    pop_20_24_seul_11 = models.FloatField(null=True)
    pop_25_39_seul_11 = models.FloatField(null=True)
    pop_40_54_seul_11 = models.FloatField(null=True)
    pop_55_64_seul_11 = models.FloatField(null=True)
    pop_65_79_seul_11 = models.FloatField(null=True)
    pop_80_plus_seul_11 = models.FloatField(null=True)
    pop_15_19_couple_11 = models.FloatField(null=True)
    pop_20_24_couple_11 = models.FloatField(null=True)
    pop_25_39_couple_11 = models.FloatField(null=True)
    pop_40_54_couple_11 = models.FloatField(null=True)
    pop_55_64_couple_11 = models.FloatField(null=True)
    pop_65_79_couple_11 = models.FloatField(null=True)
    pop_80_plus_couple_11 = models.FloatField(null=True)

    # Specifiques P22
    pop_15_plus_maries_22 = models.FloatField(null=True)
    pop_15_plus_pacses_22 = models.FloatField(null=True)
    pop_15_plus_concubinage_22 = models.FloatField(null=True)
    pop_15_plus_veufs_22 = models.FloatField(null=True)
    pop_15_plus_divorces_22 = models.FloatField(null=True)
    pop_15_plus_celibataires_22 = models.FloatField(null=True)

    # Specifiques P16
    pop_15_plus_maries_16 = models.FloatField(null=True)
    pop_15_plus_non_maries_16 = models.FloatField(null=True)

    # Specifiques P11
    pop_15_plus_maries_11 = models.FloatField(null=True)
    pop_15_plus_celibataires_11 = models.FloatField(null=True)
    pop_15_plus_veufs_11 = models.FloatField(null=True)
    pop_15_plus_divorces_11 = models.FloatField(null=True)

    class Meta:
        managed = False
        db_table = "public_data_dc_situation_conjugale"
