
version: 2

cs_accepted_values: &cs_accepted_values
  values: [
    "CS1.1.1.1",
    "CS1.1.1.2",
    "CS1.1.2.1",
    "CS1.1.2.2",
    "CS1.2.1",
    "CS1.2.2",
    "CS1.2.3",
    "CS2.1.1.1",
    "CS2.1.1.2",
    "CS2.1.1.3",
    "CS2.1.2",
    "CS2.1.3",
    "CS2.2.1",
    "CS2.2.2"
  ]

us_accepted_values: &us_accepted_values
  values : [
    "US1.1",
    "US1.2",
    "US1.3",
    "US1.4",
    "US2",
    "US3",
    "US5",
    "US235",
    "US4.1.1",
    "US4.1.2",
    "US4.1.3",
    "US4.1.4",
    "US4.1.5",
    "US4.2",
    "US4.3",
    "US6.1",
    "US6.2",
    "US6.3",
    "US6.6"
  ]

difference_test: &difference_test
  - name: geom
    tests:
      - not_null
      - unique
      - is_valid_geom
  - name: cs_new
    tests:
      - not_null
      - accepted_values: *cs_accepted_values
  - name: cs_old
    tests:
      - not_null
      - accepted_values: *cs_accepted_values
  - name: us_new
    tests:
      - not_null
      - accepted_values: *us_accepted_values
  - name: us_old
    tests:
      - not_null
      - accepted_values: *us_accepted_values

occupation_du_sol_test: &occupation_du_sol_test
  - name: geom
    tests:
      - not_null
      - unique
      - is_valid_geom
  - name: departement
    tests:
      - not_null
  - name: year
    tests:
      - not_null
  - name: id
    tests:
      - unique
      - not_null
  - name: guid
    tests:
      - unique
      - not_null
  - name: code_cs
    tests:
      - not_null
      - accepted_values: *cs_accepted_values
  - name: code_us
    tests:
      - not_null
      - accepted_values: *us_accepted_values


zone_construite_test: &zone_construite_test
  - name: geom
    tests:
      - not_null
      - unique
      - is_valid_geom
  - name: departement
    tests:
      - not_null
  - name: year
    tests:
      - not_null
  - name: id
    tests:
      - unique
      - not_null
  - name: guid
    tests:
      - unique
      - not_null

models:
  - name: zone_construite
  - name: occupation_du_sol
  - name: difference

sources:
  - name: public
    tables:
    - name: ocsge_diff
      columns: *difference_test
    - name: ocsge_occupation_du_sol
      columns: *occupation_du_sol_test
    - name: ocsge_zone_construite
