# Generated by Django 3.2.5 on 2021-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(max_length=40, unique=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("STR", "String"),
                            ("FLT", "Float"),
                            ("DCL", "Decimal"),
                            ("JSN", "JSON"),
                        ],
                        default="STR",
                        max_length=3,
                        verbose_name="Casting type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("value", models.CharField(max_length=250, verbose_name="value")),
            ],
        ),
    ]
