
version: 2

models:
  - name: zonage_urbanisme
    columns:
    - name: gpu_timestamp
      data_tests:
      - not_null
    - name: geom
      data_tests:
      - unique
      - is_valid_geom
      - is_not_empty_geom

sources:
  - name: public
    tables:
    - name: gpu_zone_urba
