version: 2

valid_srids: &valid_srids
  values: [
    32620,
    2972,
    2975,
    2154
  ]

models:
  - name: zonage_urbanisme
    columns:
    - name: gpu_timestamp
      data_tests:
      - not_null
    - name: geom
      data_tests:
      - unique
      - is_valid_geom
      - is_not_empty_geom
    - name: srid_source
      data_tests:
      - not_null
      - accepted_values: *valid_srids

sources:
  - name: public
    tables:
    - name: gpu_zone_urba
