
version: 2

models:
  - name: consommation
    columns:
    - name: commune_code
      data_tests:
      - not_null
      - unique
    - name: commune_name
      data_tests:
      - not_null
    - name: region_code
      data_tests:
      - not_null
      - relationships:
          to: ref('region')
          field: code
    - name: region_name
      data_tests:
      - not_null
    - name: departement_code
      data_tests:
      - not_null
      - relationships:
          to: ref('departement')
          field: code
    - name: departement_name
      data_tests:
      - not_null
    - name: epci_code
      data_tests:
      - not_null
    - name: epci_name
      data_tests:
      - not_null

sources:
  - name: public
    tables:
    - name: majic_france_metropolitaine
    - name: majic_guadeloupe
    - name: majic_guyane
    - name: majic_martinique
    - name: majic_la_reunion
