
version: 2

models:
  - name: consommation
    columns:
    - name: commune_code
      data_tests:
      - not_null
      - unique
  - name: consommation_cog_2024
    columns:
    - name: commune_code
      data_tests:
      - not_null
      - unique
      - relationships:
          to: ref('commune')
          field: code

sources:
  - name: public
    tables:
    - name: majic_france_metropolitaine
    - name: majic_guadeloupe
    - name: majic_guyane
    - name: majic_martinique
    - name: majic_la_reunion
