# Generated by Django 3.2.18 on 2023-02-24 13:14

from typing import Callable
from django.db import migrations, connection


def forwards(apps, schema_editor):
    WordTemplate: Callable = apps.get_model("diagnostic_word", "WordTemplate")  # type: ignore

    with connection.cursor() as cursor:
        cursor.execute("SELECT docx FROM django_docx_template_docxtemplate;")
        old_docx = cursor.fetchone()[0]
    WordTemplate.objects.create(
        slug="template-bilan-1",
        description="Modèle Word pour générer le diagnostic téléchargeable",
        docx=old_docx,
        filename_mask="{diagnostic_name} - {start_date} à {end_date} - issu de SPARTE.docx",
    )


def backwards(apps, schema_editor):
    WordTemplate: Callable = apps.get_model("diagnostic_word", "WordTemplate")  # type: ignore
    WordTemplate.objects.filter(slug="template-bilan-1").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostic_word", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
        migrations.RunSQL("DROP TABLE django_docx_template_docxtemplate;"),
    ]
