# Generated by Django 4.2.20 on 2025-05-15 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostic_word", "0003_alter_wordtemplate_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WordTemplate",
        ),
    ]
