
version: 2

cs_accepted_values: &cs_accepted_values
  values: [
    "CS1.1.1.1",
    "CS1.1.1.2",
    "CS1.1.2.1",
    "CS1.1.2.2",
    "CS1.2.1",
    "CS1.2.2",
    "CS1.2.3",
    "CS2.1.1.1",
    "CS2.1.1.2",
    "CS2.1.1.3",
    "CS2.1.2",
    "CS2.1.3",
    "CS2.2.1",
    "CS2.2.2"
  ]

us_accepted_values: &us_accepted_values
  values : [
    "US1.1",
    "US1.2",
    "US1.3",
    "US1.4",
    "US2",
    "US3",
    "US5",
    "US235",
    "US4.1.1",
    "US4.1.2",
    "US4.1.3",
    "US4.1.4",
    "US4.1.5",
    "US4.2",
    "US4.3",
    "US6.1",
    "US6.2",
    "US6.3",
    "US6.6"
  ]

not_null_cs_us_config_staging: &not_null_cs_us_config_staging
  config:
    error_if: ">100"
    warn_if: ">0"

models:
  - name: occupation_du_sol_commune
  - name: artificial_commune
  - name: zone_construite
    columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
          # - unique -> the same object can be present in different departement. TODO: replace the departement field by an array
      - name: year
        data_tests:
          - not_null
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: geom
        data_tests:
          - not_null
          - is_valid_geom
          - is_not_empty_geom
      - name: surface
        data_tests:
          - not_null
      - name: uuid
        data_tests:
          - not_null
          - unique
  - name: occupation_du_sol
    columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
          # - unique -> the same object can be present in different departement. TODO: replace the departement field by an array
      - name: code_cs
        data_tests:
          - not_null
          - accepted_values: *cs_accepted_values
      - name: code_us
        data_tests:
          - not_null
          - accepted_values: *us_accepted_values
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: year
        data_tests:
          - not_null
      - name: surface
        data_tests:
          - not_null
      - name: is_impermeable
        data_tests:
          - not_null
      - name: is_artificial
        data_tests:
          - not_null
      - name: uuid
        data_tests:
          - not_null
          - unique
      - name: geom
        data_tests:
          - not_null
          - is_valid_geom
          - is_not_empty_geom
  - name: difference
    columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: year_old
        data_tests:
          - not_null
      - name: year_new
        data_tests:
          - not_null
      - name: cs_new
        data_tests:
          - not_null
          - accepted_values: *cs_accepted_values
      - name: cs_old
        data_tests:
          - not_null
          - accepted_values: *cs_accepted_values
      - name: us_new
        data_tests:
          - not_null
          - accepted_values: *us_accepted_values
      - name: us_old
        data_tests:
          - not_null
          - accepted_values: *us_accepted_values
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: surface
        data_tests:
          - not_null
      - name: uuid
        data_tests:
          - not_null
          - unique
      - name: new_is_impermeable
        data_tests:
          - not_null
      - name: new_not_impermeable
        data_tests:
          - not_null
      - name: new_is_artificial
        data_tests:
          - not_null
      - name: new_not_artificial
        data_tests:
          - not_null
      - name: geom
        data_tests:
          - not_null
          - is_valid_geom
          - is_not_empty_geom

sources:
  - name: public
    tables:
    - name: ocsge_zone_construite_staging
      columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
          - unique
      - name: year
        data_tests:
          - not_null
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: uuid
        data_tests:
          - not_null
          - unique
      - name: geom
        data_tests:
          - unique:
              config:
                error_if: ">5"
                warn_if: ">0"
          - not_null
          - is_valid_geom_warning
          - is_not_empty_geom
    - name: ocsge_occupation_du_sol_staging
      columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
          - unique
      - name: code_cs
        data_tests:
          - not_null
          - accepted_values: *cs_accepted_values
      - name: code_us
        data_tests:
          - not_null
          - accepted_values: *us_accepted_values
      - name: geom
        data_tests:
          - unique
          - not_null
          - is_valid_geom_warning
          - is_not_empty_geom
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: year
        data_tests:
          - not_null
      - name: uuid
        data_tests:
          - not_null
          - unique
    - name: ocsge_difference_staging
      columns:
      - name: loaded_date
        data_tests:
          - not_null
      - name: year_old
        data_tests:
          - not_null
      - name: year_new
        data_tests:
          - not_null
      - name: cs_new
        data_tests:
          - not_null: *not_null_cs_us_config_staging
          - accepted_values: *cs_accepted_values
      - name: cs_old
        data_tests:
          - not_null: *not_null_cs_us_config_staging
          - accepted_values: *cs_accepted_values
      - name: us_new
        data_tests:
          - not_null: *not_null_cs_us_config_staging
          - accepted_values: *us_accepted_values
      - name: us_old
        data_tests:
          - not_null: *not_null_cs_us_config_staging
          - accepted_values: *us_accepted_values
      - name: departement
        data_tests:
          - not_null
          - relationships:
              to: ref('departement')
              field: code
      - name: uuid
        data_tests:
          - not_null
          - unique
      - name: geom
        data_tests:
          - unique
          - not_null
          - is_valid_geom_warning
          - is_not_empty_geom
    - name: ocsge_difference
    - name: ocsge_occupation_du_sol
    - name: ocsge_zone_construite
