
version: 2

models:
  - name: app_usagesol
  - name: app_couverturesol
  - name: app_couvertureusagematrix

sources:
  - name: public
    tables:
    - name: app_usagesol
    - name: app_couverturesol
    - name: app_couvertureusagematrix
