# flake8: noqa: E501
from inline_snapshot import snapshot

from project.tests.charts.helpers import normalize


def test_annual_conso_by_determinant_chart(client, metropole_de_lyon):
    response = client.get(
        "/api/chart/chart_determinant/EPCI/200046977",
        {"start_date": 2011, "end_date": 2022},
    )
    assert response.status_code == 200
    assert normalize(response.json()) == snapshot(
        {
            "highcharts_options": {
                "noData": {
                    "style": {
                        "position": "absolute",
                        "backgroundColor": "#ffffff",
                        "textAlign": "center",
                        "textAlignLast": "center",
                        "fontSize": "0.85em",
                        "padding": "15px",
                    }
                },
                "legend": {
                    "itemWidth": 200,
                    "itemStyle": {"textOverflow": None},
                    "layout": "horizontal",
                    "align": "center",
                    "verticalAlign": "bottom",
                },
                "chart": {"type": "column"},
                "title": {
                    "text": "Évolution annuelle de la consommation d'espaces par destination à Métropole de Lyon (2011 - 2022)"
                },
                "yAxis": {
                    "title": {"text": "Consommation d'espaces (en ha)"},
                    "stackLabels": {"enabled": True, "format": "{total:,.2f}"},
                },
                "tooltip": {
                    "headerFormat": "<b>{point.key}</b><br/>",
                    "pointFormat": "{series.name}: {point.y}",
                    "valueSuffix": " Ha",
                    "valueDecimals": 2,
                },
                "xAxis": {"type": "category"},
                "plotOptions": {"series": {"grouping": False, "borderWidth": 0}},
                "series": [
                    {
                        "name": "Total",
                        "data": [
                            {"name": 2011, "y": 80.3176},
                            {"name": 2012, "y": 107.927},
                            {"name": 2013, "y": 123.8875},
                            {"name": 2014, "y": 82.5823},
                            {"name": 2015, "y": 116.128},
                            {"name": 2016, "y": 73.6576},
                            {"name": 2017, "y": 65.4311},
                            {"name": 2018, "y": 68.8792},
                            {"name": 2019, "y": 44.2812},
                            {"name": 2020, "y": 64.6539},
                            {"name": 2021, "y": 81.1762},
                            {"name": 2022, "y": 32.31},
                        ],
                        "id": "main",
                        "type": "column",
                        "stacking": None,
                        "zIndex": 0,
                        "color": "#CFD1E5",
                    },
                    {
                        "name": "Inconnu",
                        "data": [
                            {"name": 2011, "y": 0.0436},
                            {"name": 2012, "y": 0.1015},
                            {"name": 2013, "y": 0.1064},
                            {"name": 2014, "y": 2.3278},
                            {"name": 2015, "y": 7.2192},
                            {"name": 2016, "y": 3.4773},
                            {"name": 2017, "y": 0.2065},
                            {"name": 2018, "y": 3.0245},
                            {"name": 2019, "y": 0.4777},
                            {"name": 2020, "y": 0.0003},
                            {"name": 2021, "y": 0.0007},
                            {"name": 2022, "y": 0.0001},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Ferré",
                        "data": [
                            {"name": 2011, "y": 0.0},
                            {"name": 2012, "y": 0.0},
                            {"name": 2013, "y": 0.0},
                            {"name": 2014, "y": 0.0},
                            {"name": 2015, "y": 0.0},
                            {"name": 2016, "y": 0.1022},
                            {"name": 2017, "y": 0.0},
                            {"name": 2018, "y": 0.0445},
                            {"name": 2019, "y": 0.0396},
                            {"name": 2020, "y": 0.0},
                            {"name": 2021, "y": 0.0},
                            {"name": 2022, "y": 0.0},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Activité",
                        "data": [
                            {"name": 2011, "y": 30.9557},
                            {"name": 2012, "y": 34.5523},
                            {"name": 2013, "y": 58.1581},
                            {"name": 2014, "y": 33.0668},
                            {"name": 2015, "y": 62.4376},
                            {"name": 2016, "y": 31.7628},
                            {"name": 2017, "y": 33.9507},
                            {"name": 2018, "y": 24.53},
                            {"name": 2019, "y": 9.7384},
                            {"name": 2020, "y": 29.2484},
                            {"name": 2021, "y": 28.4569},
                            {"name": 2022, "y": 5.6605},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Mixte",
                        "data": [
                            {"name": 2011, "y": 4.4223},
                            {"name": 2012, "y": 4.0398},
                            {"name": 2013, "y": 1.9489},
                            {"name": 2014, "y": 4.781},
                            {"name": 2015, "y": 1.3961},
                            {"name": 2016, "y": 1.1028},
                            {"name": 2017, "y": 2.6513},
                            {"name": 2018, "y": 1.5756},
                            {"name": 2019, "y": 1.0651},
                            {"name": 2020, "y": 2.4193},
                            {"name": 2021, "y": 2.1525},
                            {"name": 2022, "y": 0.5777},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Route",
                        "data": [
                            {"name": 2011, "y": 4.7758},
                            {"name": 2012, "y": 13.0623},
                            {"name": 2013, "y": 8.4369},
                            {"name": 2014, "y": 7.0336},
                            {"name": 2015, "y": 8.8408},
                            {"name": 2016, "y": 8.7505},
                            {"name": 2017, "y": 5.4197},
                            {"name": 2018, "y": 6.2615},
                            {"name": 2019, "y": 5.2006},
                            {"name": 2020, "y": 5.2296},
                            {"name": 2021, "y": 12.2749},
                            {"name": 2022, "y": 5.4929},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Habitat",
                        "data": [
                            {"name": 2011, "y": 40.1202},
                            {"name": 2012, "y": 56.1711},
                            {"name": 2013, "y": 55.2372},
                            {"name": 2014, "y": 35.3731},
                            {"name": 2015, "y": 36.2343},
                            {"name": 2016, "y": 28.462},
                            {"name": 2017, "y": 23.2029},
                            {"name": 2018, "y": 33.4431},
                            {"name": 2019, "y": 27.7598},
                            {"name": 2020, "y": 27.7563},
                            {"name": 2021, "y": 38.2912},
                            {"name": 2022, "y": 20.5788},
                        ],
                        "type": "column",
                        "zIndex": 1,
                        "stacking": "normal",
                    },
                ],
                "navigation": {"buttonOptions": {"enabled": False}},
                "credits": {"enabled": False},
                "responsive": {
                    "rules": [
                        {
                            "condition": {"maxWidth": 600},
                            "chartOptions": {
                                "legend": {"align": "center", "verticalAlign": "bottom", "layout": "horizontal"}
                            },
                        }
                    ]
                },
                "exporting": {
                    "filename": "Évolution annuelle de la consommation d'espaces par destination à Métropole de Lyon (2011 - 2022)",
                    "url": "https://highcharts-export.osc-fr1.scalingo.io",
                    "chartOptions": {"chart": {"style": {"fontSize": "8px"}}},
                },
                "colors": [
                    "#4e9c79",
                    "#6a6af4",
                    "#6b8abc",
                    "#86cdf2",
                    "#8ecac7",
                    "#91e8e1",
                    "#bce3f9",
                    "#c9e7c9",
                    "#cab8ee",
                    "#eeb088",
                    "#f5d3b5",
                    "#fd8970",
                ],
            },
            "data_table": {
                "headers": [
                    "2011",
                    "2012",
                    "2013",
                    "2014",
                    "2015",
                    "2016",
                    "2017",
                    "2018",
                    "2019",
                    "2020",
                    "2021",
                    "2022",
                    "Destination",
                    "Total",
                ],
                "rows": [
                    {
                        "name": "",
                        "data": [
                            "Activité",
                            24.53,
                            28.46,
                            29.25,
                            30.96,
                            31.76,
                            33.07,
                            33.95,
                            34.55,
                            382.53,
                            5.66,
                            58.16,
                            62.44,
                            9.74,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Ferré",
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.04,
                            0.04,
                            0.1,
                            0.18000000000000002,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Habitat",
                            20.58,
                            23.2,
                            27.76,
                            27.76,
                            28.46,
                            33.44,
                            35.37,
                            36.23,
                            38.29,
                            40.12,
                            422.62,
                            55.24,
                            56.17,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Inconnu",
                            0.0,
                            0.0,
                            0.0,
                            0.04,
                            0.1,
                            0.11,
                            0.21,
                            0.48,
                            16.990000000000002,
                            2.33,
                            3.02,
                            3.48,
                            7.22,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Mixte",
                            0.58,
                            1.07,
                            1.1,
                            1.4,
                            1.58,
                            1.95,
                            2.15,
                            2.42,
                            2.65,
                            28.14,
                            4.04,
                            4.42,
                            4.78,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Route",
                            12.27,
                            13.06,
                            4.78,
                            5.2,
                            5.23,
                            5.42,
                            5.49,
                            6.26,
                            7.03,
                            8.44,
                            8.75,
                            8.84,
                            90.77,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Total",
                            107.92,
                            116.13,
                            123.9,
                            32.309999999999995,
                            44.29,
                            64.66000000000001,
                            65.42999999999999,
                            68.87,
                            73.64999999999999,
                            80.32000000000001,
                            81.17,
                            82.58,
                            941.2299999999998,
                        ],
                    },
                ],
                "boldFirstColumn": True,
                "boldLastColumn": True,
                "boldLastRow": True,
            },
        }
    )
