# flake8: noqa: E501
from inline_snapshot import snapshot


def test_annual_total_conso_chart(client, hauts_de_seine):
    response = client.get(
        "/api/chart/annual_total_conso_chart/DEPART/92",
        {"start_date": 2011, "end_date": 2022},
    )
    assert response.status_code == 200
    assert response.json() == snapshot(
        {
            "highcharts_options": {
                "noData": {
                    "style": {
                        "position": "absolute",
                        "backgroundColor": "#ffffff",
                        "textAlign": "center",
                        "textAlignLast": "center",
                        "fontSize": "0.85em",
                        "padding": "15px",
                    }
                },
                "legend": {"enabled": False},
                "chart": {"type": "column", "height": 280},
                "title": {"text": "Consommation annuelle d'espaces NAF - Hauts-de-Seine (2011 - 2022)"},
                "yAxis": {"title": {"text": "Consommation d'espaces NAF (ha)"}},
                "xAxis": {"type": "category"},
                "tooltip": {
                    "headerFormat": "<b>{series.name}</b><br/>",
                    "pointFormat": "{point.name}: {point.y}",
                    "valueDecimals": 2,
                },
                "series": [
                    {
                        "name": "Hauts-de-Seine",
                        "data": [
                            {"name": "2011", "y": 1.5031},
                            {"name": "2012", "y": 3.8072},
                            {"name": "2013", "y": 3.3231},
                            {"name": "2014", "y": 2.5464},
                            {"name": "2015", "y": 23.8342},
                            {"name": "2016", "y": 0.6894},
                            {"name": "2017", "y": 1.1492},
                            {"name": "2018", "y": 2.5004},
                            {"name": "2019", "y": 1.0057},
                            {"name": "2020", "y": 2.1544},
                            {"name": "2021", "y": 0.3791},
                            {"name": "2022", "y": 0.4198},
                        ],
                    }
                ],
                "navigation": {"buttonOptions": {"enabled": False}},
                "credits": {"enabled": False},
                "responsive": {
                    "rules": [
                        {
                            "condition": {"maxWidth": 600},
                            "chartOptions": {
                                "legend": {"align": "center", "verticalAlign": "bottom", "layout": "horizontal"}
                            },
                        }
                    ]
                },
                "exporting": {
                    "filename": "Consommation annuelle d'espaces NAF - Hauts-de-Seine (2011 - 2022)",
                    "url": "https://highcharts-export.osc-fr1.scalingo.io",
                    "chartOptions": {"chart": {"style": {"fontSize": "8px"}}},
                },
                "colors": [
                    "#6a6af4",
                    "#8ecac7",
                    "#eeb088",
                    "#cab8ee",
                    "#6b8abc",
                    "#86cdf2",
                    "#fd8970",
                    "#c9e7c9",
                    "#f5d3b5",
                    "#91e8e1",
                    "#4e9c79",
                    "#bce3f9",
                ],
            },
            "data_table": {
                "headers": [
                    "Commune",
                    "2011",
                    "2012",
                    "2013",
                    "2014",
                    "2015",
                    "2016",
                    "2017",
                    "2018",
                    "2019",
                    "2020",
                    "2021",
                    "2022",
                    "Total",
                ],
                "rows": [
                    {
                        "name": "",
                        "data": ["Antony", 0.15, 0.06, 0.25, 0.03, 0.03, 0.0, 0.06, 0.03, 0.0, 0.12, 0.03, 0.0, 0.76],
                    },
                    {
                        "name": "",
                        "data": ["Asnières-sur-Seine", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": ["Bagneux", 0.08, 0.0, 0.06, 0.12, 0.0, 0.04, 0.13, 0.06, 0.0, 0.0, 0.0, 0.0, 0.49],
                    },
                    {
                        "name": "",
                        "data": ["Bois-Colombes", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": [
                            "Boulogne-Billancourt",
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Bourg-la-Reine", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {"name": "", "data": ["Chaville", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": [
                            "Châtenay-Malabry",
                            0.53,
                            0.19,
                            0.28,
                            0.0,
                            3.25,
                            0.34,
                            0.09,
                            0.24,
                            0.07,
                            0.63,
                            0.35,
                            0.0,
                            5.97,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Châtillon", 0.0, 0.0, 0.03, 0.0, 0.32, 0.08, 0.08, 0.13, 0.05, 0.0, 0.0, 0.0, 0.69],
                    },
                    {
                        "name": "",
                        "data": ["Clamart", 0.17, 0.63, 0.1, 0.0, 0.01, 0.0, 0.36, 1.17, 0.07, 0.0, 0.0, 0.06, 2.57],
                    },
                    {
                        "name": "",
                        "data": ["Clichy", 0.0, 0.0, 0.0, 0.0, 0.07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07],
                    },
                    {"name": "", "data": ["Colombes", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": ["Courbevoie", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": ["Fontenay-aux-Roses", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {"name": "", "data": ["Garches", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": [
                            "Gennevilliers",
                            0.0,
                            2.54,
                            0.04,
                            0.0,
                            20.12,
                            0.0,
                            0.25,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            22.95,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Issy-les-Moulineaux", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": ["La Garenne-Colombes", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": [
                            "Le Plessis-Robinson",
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.01,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.01,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Levallois-Perret", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": ["Malakoff", 0.0, 0.12, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.12],
                    },
                    {
                        "name": "",
                        "data": [
                            "Marnes-la-Coquette",
                            0.14,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.14,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Meudon", 0.0, 0.0, 0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03],
                    },
                    {"name": "", "data": ["Montrouge", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": [
                            "Nanterre",
                            0.0,
                            0.15,
                            0.04,
                            0.38,
                            0.03,
                            0.01,
                            0.11,
                            0.08,
                            0.14,
                            0.42,
                            0.0,
                            0.09,
                            1.45,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Neuilly-sur-Seine", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {"name": "", "data": ["Puteaux", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": [
                            "Rueil-Malmaison",
                            0.34,
                            0.11,
                            0.0,
                            0.24,
                            0.0,
                            0.0,
                            0.07,
                            0.8,
                            0.67,
                            0.97,
                            0.0,
                            0.26,
                            3.46,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Saint-Cloud", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {"name": "", "data": ["Sceaux", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {"name": "", "data": ["Suresnes", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": ["Sèvres", 0.09, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.49],
                    },
                    {"name": "", "data": ["Vanves", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0]},
                    {
                        "name": "",
                        "data": ["Vaucresson", 0.0, 0.0, 2.51, 1.37, 0.0, 0.21, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.09],
                    },
                    {
                        "name": "",
                        "data": ["Ville-d'Avray", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
                    },
                    {
                        "name": "",
                        "data": [
                            "Villeneuve-la-Garenne",
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Total",
                            1.5,
                            3.8,
                            3.34,
                            2.5399999999999996,
                            23.830000000000002,
                            0.68,
                            1.1600000000000001,
                            2.51,
                            1.0,
                            2.1399999999999997,
                            0.38,
                            0.41000000000000003,
                            43.28999999999999,
                        ],
                    },
                ],
                "boldFirstColumn": True,
                "boldLastColumn": True,
                "boldLastRow": True,
            },
        }
    )
