# flake8: noqa: E501
from inline_snapshot import snapshot


def test_annual_conso_by_determinant_chart(client, hauts_de_seine):
    response = client.get(
        "/api/chart/chart_determinant/DEPART/92",
        {"start_date": 2011, "end_date": 2022},
    )
    assert response.status_code == 200
    assert response.json() == snapshot(
        {
            "highcharts_options": {
                "noData": {
                    "style": {
                        "position": "absolute",
                        "backgroundColor": "#ffffff",
                        "textAlign": "center",
                        "textAlignLast": "center",
                        "fontSize": "0.85em",
                        "padding": "15px",
                    }
                },
                "legend": {
                    "itemWidth": 200,
                    "itemStyle": {"textOverflow": None},
                    "layout": "horizontal",
                    "align": "center",
                    "verticalAlign": "bottom",
                },
                "chart": {"type": "column"},
                "title": {
                    "text": "Évolution annuelle de la consommation d'espaces par destination à Hauts-de-Seine (2011 - 2022)"
                },
                "yAxis": {
                    "title": {"text": "Consommation d'espaces (en ha)"},
                    "stackLabels": {"enabled": True, "format": "{total:,.2f}"},
                },
                "tooltip": {
                    "headerFormat": "<b>{point.key}</b><br/>",
                    "pointFormat": "{series.name}: {point.y}",
                    "valueSuffix": " Ha",
                    "valueDecimals": 2,
                },
                "xAxis": {"type": "category"},
                "plotOptions": {"series": {"grouping": False, "borderWidth": 0}},
                "series": [
                    {
                        "name": "Habitat",
                        "data": [
                            {"name": 2011, "y": 0.3703},
                            {"name": 2012, "y": 0.7327},
                            {"name": 2013, "y": 0.5899},
                            {"name": 2014, "y": 0.3906},
                            {"name": 2015, "y": 0.8507},
                            {"name": 2016, "y": 0.2206},
                            {"name": 2017, "y": 0.7079},
                            {"name": 2018, "y": 1.3939},
                            {"name": 2019, "y": 0.8293},
                            {"name": 2020, "y": 1.5012},
                            {"name": 2021, "y": 0.243},
                            {"name": 2022, "y": 0.3194},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Activité",
                        "data": [
                            {"name": 2011, "y": 0.3074},
                            {"name": 2012, "y": 2.0766},
                            {"name": 2013, "y": 0.933},
                            {"name": 2014, "y": 0.7905},
                            {"name": 2015, "y": 16.6242},
                            {"name": 2016, "y": 0.2955},
                            {"name": 2017, "y": 0.2588},
                            {"name": 2018, "y": 0.2579},
                            {"name": 2019, "y": 0.0003},
                            {"name": 2020, "y": 0.5417},
                            {"name": 2021, "y": 0.1328},
                            {"name": 2022, "y": 0.0102},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Mixte",
                        "data": [
                            {"name": 2011, "y": 0.0},
                            {"name": 2012, "y": 0.0},
                            {"name": 2013, "y": 0.0},
                            {"name": 2014, "y": 0.0},
                            {"name": 2015, "y": 0.0455},
                            {"name": 2016, "y": 0.0146},
                            {"name": 2017, "y": 0.0601},
                            {"name": 2018, "y": 0.3249},
                            {"name": 2019, "y": 0.0651},
                            {"name": 2020, "y": 0.0839},
                            {"name": 2021, "y": 0.0},
                            {"name": 2022, "y": 0.0839},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Route",
                        "data": [
                            {"name": 2011, "y": 0.8254},
                            {"name": 2012, "y": 0.9238},
                            {"name": 2013, "y": 1.8002},
                            {"name": 2014, "y": 1.3653},
                            {"name": 2015, "y": 5.6335},
                            {"name": 2016, "y": 0.1587},
                            {"name": 2017, "y": 0.0834},
                            {"name": 2018, "y": 0.5237},
                            {"name": 2019, "y": 0.044},
                            {"name": 2020, "y": 0.0276},
                            {"name": 2021, "y": 0.0033},
                            {"name": 2022, "y": 0.0063},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Ferré",
                        "data": [
                            {"name": 2011, "y": 0.0},
                            {"name": 2012, "y": 0.0},
                            {"name": 2013, "y": 0.0},
                            {"name": 2014, "y": 0.0},
                            {"name": 2015, "y": 0.5821},
                            {"name": 2016, "y": 0.0},
                            {"name": 2017, "y": 0.039},
                            {"name": 2018, "y": 0.0},
                            {"name": 2019, "y": 0.0},
                            {"name": 2020, "y": 0.0},
                            {"name": 2021, "y": 0.0},
                            {"name": 2022, "y": 0.0},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Inconnu",
                        "data": [
                            {"name": 2011, "y": 0.0},
                            {"name": 2012, "y": 0.0741},
                            {"name": 2013, "y": 0.0},
                            {"name": 2014, "y": 0.0},
                            {"name": 2015, "y": 0.0982},
                            {"name": 2016, "y": 0.0},
                            {"name": 2017, "y": 0.0},
                            {"name": 2018, "y": 0.0},
                            {"name": 2019, "y": 0.067},
                            {"name": 2020, "y": 0.0},
                            {"name": 2021, "y": 0.0},
                            {"name": 2022, "y": 0.0},
                        ],
                        "type": "column",
                        "stacking": "normal",
                        "zIndex": 1,
                    },
                    {
                        "name": "Total",
                        "data": [
                            {"name": 2011, "y": 1.5031},
                            {"name": 2012, "y": 3.8072},
                            {"name": 2013, "y": 3.3231},
                            {"name": 2014, "y": 2.5464},
                            {"name": 2015, "y": 23.8342},
                            {"name": 2016, "y": 0.6894},
                            {"name": 2017, "y": 1.1492},
                            {"name": 2018, "y": 2.5004},
                            {"name": 2019, "y": 1.0057},
                            {"name": 2020, "y": 2.1544},
                            {"name": 2021, "y": 0.3791},
                            {"name": 2022, "y": 0.4198},
                        ],
                        "id": "main",
                        "type": "column",
                        "zIndex": 0,
                        "stacking": None,
                        "color": "#CFD1E5",
                    },
                ],
                "navigation": {"buttonOptions": {"enabled": False}},
                "credits": {"enabled": False},
                "responsive": {
                    "rules": [
                        {
                            "condition": {"maxWidth": 600},
                            "chartOptions": {
                                "legend": {"align": "center", "verticalAlign": "bottom", "layout": "horizontal"}
                            },
                        }
                    ]
                },
                "exporting": {
                    "filename": "Évolution annuelle de la consommation d'espaces par destination à Hauts-de-Seine (2011 - 2022)",
                    "url": "https://highcharts-export.osc-fr1.scalingo.io",
                    "chartOptions": {"chart": {"style": {"fontSize": "8px"}}},
                },
                "colors": [
                    "#6a6af4",
                    "#8ecac7",
                    "#eeb088",
                    "#cab8ee",
                    "#6b8abc",
                    "#86cdf2",
                    "#fd8970",
                    "#c9e7c9",
                    "#f5d3b5",
                    "#91e8e1",
                    "#4e9c79",
                    "#bce3f9",
                ],
            },
            "data_table": {
                "headers": [
                    "Destination",
                    "2011",
                    "2012",
                    "2013",
                    "2014",
                    "2015",
                    "2016",
                    "2017",
                    "2018",
                    "2019",
                    "2020",
                    "2021",
                    "2022",
                    "Total",
                ],
                "rows": [
                    {
                        "name": "",
                        "data": [
                            "Habitat",
                            0.37,
                            0.73,
                            0.59,
                            0.39,
                            0.85,
                            0.22,
                            0.71,
                            1.39,
                            0.83,
                            1.5,
                            0.24,
                            0.32,
                            8.14,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Activité",
                            0.31,
                            2.08,
                            0.93,
                            0.79,
                            16.62,
                            0.3,
                            0.26,
                            0.26,
                            0.0,
                            0.54,
                            0.13,
                            0.01,
                            22.230000000000004,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Mixte",
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.05,
                            0.01,
                            0.06,
                            0.32,
                            0.07,
                            0.08,
                            0.0,
                            0.08,
                            0.6699999999999999,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Route",
                            0.83,
                            0.92,
                            1.8,
                            1.37,
                            5.63,
                            0.16,
                            0.08,
                            0.52,
                            0.04,
                            0.03,
                            0.0,
                            0.01,
                            11.389999999999999,
                        ],
                    },
                    {
                        "name": "",
                        "data": ["Ferré", 0.0, 0.0, 0.0, 0.0, 0.58, 0.0, 0.04, 0.0, 0.0, 0.0, 0.0, 0.0, 0.62],
                    },
                    {
                        "name": "",
                        "data": [
                            "Inconnu",
                            0.0,
                            0.07,
                            0.0,
                            0.0,
                            0.1,
                            0.0,
                            0.0,
                            0.0,
                            0.07,
                            0.0,
                            0.0,
                            0.0,
                            0.24000000000000002,
                        ],
                    },
                    {
                        "name": "",
                        "data": [
                            "Total",
                            1.5099999999999998,
                            3.8,
                            3.3200000000000003,
                            2.5500000000000003,
                            23.830000000000002,
                            0.6900000000000001,
                            1.1500000000000001,
                            2.49,
                            1.01,
                            2.15,
                            0.37,
                            0.42000000000000004,
                            43.29,
                        ],
                    },
                ],
                "boldFirstColumn": True,
                "boldLastColumn": True,
                "boldLastRow": True,
            },
        }
    )
