# Generated by Django 3.2.5 on 2021-08-13 22:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunesSybarval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_source", models.CharField(max_length=24, verbose_name="id")),
                (
                    "prec_plani",
                    models.FloatField(max_length=6, verbose_name="prec_plani"),
                ),
                ("nom", models.CharField(max_length=45, verbose_name="nom")),
                (
                    "code_insee",
                    models.CharField(max_length=5, verbose_name="code_insee"),
                ),
                ("statut", models.CharField(max_length=22, verbose_name="statut")),
                (
                    "arrondisst",
                    models.CharField(max_length=45, verbose_name="arrondisst"),
                ),
                ("depart", models.CharField(max_length=30, verbose_name="depart")),
                ("region", models.CharField(max_length=35, verbose_name="region")),
                ("pop_2014", models.IntegerField(verbose_name="pop_2014")),
                ("pop_2015", models.IntegerField(verbose_name="pop_2015")),
                ("_commune", models.CharField(max_length=254, verbose_name="_commune")),
                ("_n_arrdt", models.IntegerField(verbose_name="_n_arrdt")),
                ("_n_canton", models.IntegerField(verbose_name="_n_canton")),
                (
                    "_nom_epci",
                    models.CharField(max_length=254, verbose_name="_nom_epci"),
                ),
                ("_siren_epc", models.IntegerField(verbose_name="_siren_epc")),
                (
                    "_nom_scot",
                    models.CharField(max_length=254, verbose_name="_nom_scot"),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                ("a_brute_20", models.IntegerField(verbose_name="a_brute_20")),
                ("a_b_2015_2", models.IntegerField(verbose_name="a_b_2015_2")),
                ("a_b_2018_2", models.IntegerField(verbose_name="a_b_2018_2")),
                ("z_baties_2", models.IntegerField(verbose_name="z_baties_2")),
                ("voirie_201", models.IntegerField(verbose_name="voirie_201")),
                ("tache_2018", models.IntegerField(verbose_name="tache_2018")),
                (
                    "d_brute_20",
                    models.FloatField(max_length=24, verbose_name="d_brute_20"),
                ),
                (
                    "d_batie_20",
                    models.FloatField(max_length=24, verbose_name="d_batie_20"),
                ),
                (
                    "d_voirie_2",
                    models.FloatField(max_length=24, verbose_name="d_voirie_2"),
                ),
                ("mpoly", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
