# Generated by Django 3.2.5 on 2021-08-16 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0002_alter_communessybarval_mpoly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artificialisee2015to2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                ("cs_2018", models.CharField(max_length=254, verbose_name="cs_2018")),
                ("us_2018", models.CharField(max_length=254, verbose_name="us_2018")),
                ("cs_2015", models.CharField(max_length=254, verbose_name="cs_2015")),
                ("us_2015", models.CharField(max_length=254, verbose_name="us_2015")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artificielle2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couverture",
                    models.CharField(max_length=254, verbose_name="couverture"),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnveloppeUrbaine2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couverture",
                    models.CharField(max_length=254, verbose_name="couverture"),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                ("a_brute_20", models.IntegerField(verbose_name="a_brute_20")),
                ("z_batie_20", models.IntegerField(verbose_name="z_batie_20")),
                ("d_brute_20", models.FloatField(verbose_name="d_brute_20")),
                ("d_batie_20", models.FloatField(verbose_name="d_batie_20")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Renaturee2018to2015",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                ("cs_2018", models.CharField(max_length=254, verbose_name="cs_2018")),
                ("us_2018", models.CharField(max_length=254, verbose_name="us_2018")),
                ("cs_2015", models.CharField(max_length=254, verbose_name="cs_2015")),
                ("us_2015", models.CharField(max_length=254, verbose_name="us_2015")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sybarval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.IntegerField(verbose_name="surface")),
                ("a_brute_20", models.IntegerField(verbose_name="a_brute_20")),
                ("a_b_2015_2", models.IntegerField(verbose_name="a_b_2015_2")),
                ("a_b_2018_2", models.IntegerField(verbose_name="a_b_2018_2")),
                ("z_baties_2", models.IntegerField(verbose_name="z_baties_2")),
                ("voirie_201", models.IntegerField(verbose_name="voirie_201")),
                ("tache_2018", models.IntegerField(verbose_name="tache_2018")),
                ("d_brute_20", models.FloatField(verbose_name="d_brute_20")),
                ("d_batie_20", models.FloatField(verbose_name="d_batie_20")),
                ("d_voirie_2", models.FloatField(verbose_name="d_voirie_2")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voirie2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couverture",
                    models.CharField(max_length=254, verbose_name="couverture"),
                ),
                ("usage", models.CharField(max_length=254, verbose_name="usage")),
                ("surface", models.IntegerField(verbose_name="surface")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZonesBaties2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couverture",
                    models.CharField(max_length=254, verbose_name="couverture"),
                ),
                ("usage", models.CharField(max_length=254, verbose_name="usage")),
                ("surface", models.IntegerField(verbose_name="surface")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="d_batie_20",
            field=models.FloatField(verbose_name="d_batie_20"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="d_brute_20",
            field=models.FloatField(verbose_name="d_brute_20"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="d_voirie_2",
            field=models.FloatField(verbose_name="d_voirie_2"),
        ),
    ]
