# Generated by Django 3.2.5 on 2021-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0004_alter_artificialisee2015to2018_cs_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="cs_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="cs_2018"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="us_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="us_2015"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="us_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="us_2018"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="a_brute_20",
            field=models.IntegerField(null=True, verbose_name="a_brute_20"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="d_batie_20",
            field=models.FloatField(null=True, verbose_name="d_batie_20"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="d_brute_20",
            field=models.FloatField(null=True, verbose_name="d_brute_20"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="z_batie_20",
            field=models.IntegerField(null=True, verbose_name="z_batie_20"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="cs_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="cs_2015"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="cs_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="cs_2018"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="us_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="us_2015"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="us_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="us_2018"),
        ),
        migrations.AlterField(
            model_name="voirie2018",
            name="usage",
            field=models.CharField(max_length=254, null=True, verbose_name="usage"),
        ),
        migrations.AlterField(
            model_name="zonesbaties2018",
            name="usage",
            field=models.CharField(max_length=254, null=True, verbose_name="usage"),
        ),
    ]
