# Generated by Django 3.2.5 on 2021-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0005_auto_20210816_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="couverture"),
        ),
        migrations.AlterField(
            model_name="voirie2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="couverture"),
        ),
        migrations.AlterField(
            model_name="zonesbaties2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="couverture"),
        ),
    ]
