# Generated by Django 3.2.5 on 2021-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0007_auto_20210816_1724"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifCommune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("insee", models.CharField(max_length=10, verbose_name="code INSEE")),
                (
                    "surface",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="surface (ha)"),
                ),
                (
                    "artif_before_2009",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Artificial before 2009 (ha)",
                    ),
                ),
                (
                    "artif_2009",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2009 (ha)",
                    ),
                ),
                (
                    "artif_2010",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2010 (ha)",
                    ),
                ),
                (
                    "artif_2011",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2011 (ha)",
                    ),
                ),
                (
                    "artif_2012",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2012 (ha)",
                    ),
                ),
                (
                    "artif_2013",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2013 (ha)",
                    ),
                ),
                (
                    "artif_2014",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2014 (ha)",
                    ),
                ),
                (
                    "artif_2015",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2015 (ha)",
                    ),
                ),
                (
                    "artif_2016",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2016 (ha)",
                    ),
                ),
                (
                    "artif_2017",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2017 (ha)",
                    ),
                ),
                (
                    "artif_2018",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="New artificial 2018 (ha)",
                    ),
                ),
            ],
        ),
    ]
