# Generated by Django 3.2.5 on 2021-08-17 21:31

from django.core.management import call_command
from django.db import migrations


def forwards(apps, schema_editor):
    klasses = [
        "public_data.models.CommunesSybarval",
        "public_data.models.Artificialisee2015to2018",
        "public_data.models.Renaturee2018to2015",
        "public_data.models.Artificielle2018",
        "public_data.models.EnveloppeUrbaine2018",
        "public_data.models.Voirie2018",
        "public_data.models.ZonesBaties2018",
        "public_data.models.Sybarval",
    ]
    for klass in klasses:
        try:
            call_command("load_data", klass)
        except Exception as e:
            print("Error=", e)


def backwards(apps, schema_editor):
    """this migration only load data in tables, nothing to reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0007_auto_20210816_1724"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
