# Generated by Django 3.2.5 on 2021-09-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0008_artifcommune"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouvertureSol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="Nomenclature")),
                ("label", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "is_artificial",
                    models.BooleanField(default=False, verbose_name="Est artificielle"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="public_data.couverturesol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageSol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="Nomenclature")),
                ("label", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="public_data.couverturesol",
                    ),
                ),
            ],
        ),
    ]
