# Generated by Django 3.2.5 on 2021-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0010_alter_usagesol_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifcommune",
            name="insee",
            field=models.CharField(max_length=10, verbose_name="Code INSEE"),
        ),
        migrations.AlterField(
            model_name="artifcommune",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="cs_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture 2015"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="cs_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture 2018"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="us_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage 2015"),
        ),
        migrations.AlterField(
            model_name="artificialisee2015to2018",
            name="us_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage 2018"),
        ),
        migrations.AlterField(
            model_name="artificielle2018",
            name="couverture",
            field=models.CharField(max_length=254, verbose_name="Couverture"),
        ),
        migrations.AlterField(
            model_name="artificielle2018",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_commune",
            field=models.CharField(max_length=254, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_n_arrdt",
            field=models.IntegerField(verbose_name="nb arrdt"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_n_canton",
            field=models.IntegerField(verbose_name="nb cantons"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_nom_epci",
            field=models.CharField(max_length=254, verbose_name="Nom EPCI"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_nom_scot",
            field=models.CharField(max_length=254, verbose_name="Nom SCOT"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="_siren_epc",
            field=models.IntegerField(verbose_name="siren epc"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="code_insee",
            field=models.CharField(max_length=5, verbose_name="Code INSEE"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="depart",
            field=models.CharField(max_length=30, verbose_name="departement"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="nom",
            field=models.CharField(max_length=45, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="pop_2014",
            field=models.IntegerField(verbose_name="Population 2014"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="pop_2015",
            field=models.IntegerField(verbose_name="Population 2015"),
        ),
        migrations.AlterField(
            model_name="communessybarval",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="couverturesol",
            name="code",
            field=models.CharField(max_length=8, unique=True, verbose_name="Nomenclature"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture"),
        ),
        migrations.AlterField(
            model_name="enveloppeurbaine2018",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="cs_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture 2015"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="cs_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture 2018"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="us_2015",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage 2015"),
        ),
        migrations.AlterField(
            model_name="renaturee2018to2015",
            name="us_2018",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage 2018"),
        ),
        migrations.AlterField(
            model_name="sybarval",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="usagesol",
            name="code",
            field=models.CharField(max_length=8, unique=True, verbose_name="Nomenclature"),
        ),
        migrations.AlterField(
            model_name="voirie2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture"),
        ),
        migrations.AlterField(
            model_name="voirie2018",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="voirie2018",
            name="usage",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage"),
        ),
        migrations.AlterField(
            model_name="zonesbaties2018",
            name="couverture",
            field=models.CharField(max_length=254, null=True, verbose_name="Couverture"),
        ),
        migrations.AlterField(
            model_name="zonesbaties2018",
            name="surface",
            field=models.IntegerField(verbose_name="Surface"),
        ),
        migrations.AlterField(
            model_name="zonesbaties2018",
            name="usage",
            field=models.CharField(max_length=254, null=True, verbose_name="Usage"),
        ),
    ]
