# Generated by Django 3.2.5 on 2021-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0014_auto_20210924_0019"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsge2015",
            name="map_color",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Couleur"),
        ),
    ]
