# Generated by Django 3.2.5 on 2021-09-24 21:37

from django.db import migrations, models


def set_couverture(apps, schema_editor):
    pass


def set_usage(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0015_ocsge2015_map_color"),
    ]

    operations = [
        # process CouvertureSol
        migrations.AddField(
            model_name="couverturesol",
            name="code_prefix",
            field=models.CharField(
                max_length=10,
                null=True,
                blank=True,
                verbose_name="Nomenclature préfixée",
            ),
        ),
        migrations.RunPython(set_couverture, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="couverturesol",
            name="code_prefix",
            field=models.CharField(max_length=10, unique=True, verbose_name="Nomenclature préfixée"),
        ),
        migrations.AddField(
            model_name="usagesol",
            name="code_prefix",
            field=models.CharField(
                max_length=10,
                null=True,
                blank=True,
                verbose_name="Nomenclature préfixée",
            ),
        ),
        migrations.RunPython(set_usage, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usagesol",
            name="code_prefix",
            field=models.CharField(max_length=10, unique=True, verbose_name="Nomenclature préfixée"),
        ),
    ]
