# Generated by Django 3.2.5 on 2021-09-26 23:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import public_data.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0018_auto_20210926_2332"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocsge2018",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couverture",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Couverture du sol",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Usage du sol",
                    ),
                ),
                (
                    "millesime",
                    models.DateField(blank=True, null=True, verbose_name="Millésime"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=254, null=True, verbose_name="Source"),
                ),
                (
                    "origine",
                    models.CharField(blank=True, max_length=254, null=True, verbose_name="Origine"),
                ),
                (
                    "origine2",
                    models.CharField(blank=True, max_length=254, null=True, verbose_name="Origine1"),
                ),
                (
                    "ossature",
                    models.IntegerField(blank=True, null=True, verbose_name="Ossature"),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "couverture_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Libellé couverture du sol",
                    ),
                ),
                (
                    "usage_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Libellé usage du sol",
                    ),
                ),
                (
                    "map_color",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Couleur"),
                ),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                public_data.models.mixins.AutoLoadMixin,
                public_data.models.mixins.DataColorationMixin,
            ),
        ),
    ]
