# Generated by Django 3.2.5 on 2021-09-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0019_ocsge2018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couverturesol",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="public_data.couverturesol",
            ),
        ),
        migrations.AlterField(
            model_name="usagesol",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="public_data.usagesol",
            ),
        ),
        migrations.AddIndex(
            model_name="ocsge2015",
            index=models.Index(fields=["couverture"], name="public_data_couvert_99b082_idx"),
        ),
        migrations.AddIndex(
            model_name="ocsge2015",
            index=models.Index(fields=["usage"], name="public_data_usage_06ac50_idx"),
        ),
        migrations.AddIndex(
            model_name="ocsge2018",
            index=models.Index(fields=["couverture"], name="public_data_couvert_9b2e27_idx"),
        ),
        migrations.AddIndex(
            model_name="ocsge2018",
            index=models.Index(fields=["usage"], name="public_data_usage_e45f3b_idx"),
        ),
    ]
