# Generated by Django 3.2.5 on 2021-10-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0023_auto_20211027_1241"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couverturesol",
            name="is_artificial",
        ),
        migrations.CreateModel(
            name="CouvertureUsageMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_artificial", models.BooleanField(default=False)),
                ("is_consumed", models.BooleanField(default=False)),
                (
                    "couverture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="public_data.couverturesol",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="public_data.usagesol",
                    ),
                ),
            ],
        ),
    ]
