# Generated by Django 3.2.5 on 2021-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0024_auto_20211027_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="couvertureusagematrix",
            name="is_natural",
            field=models.BooleanField(default=False),
        ),
    ]
