# Generated by Django 3.2.5 on 2021-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0025_couvertureusagematrix_is_natural"),
    ]

    operations = [
        migrations.AddField(
            model_name="couvertureusagematrix",
            name="label",
            field=models.CharField(
                choices=[
                    ("ARTIF", "Artificiel"),
                    ("CONSU", "Consommé"),
                    ("NAF", "NAF"),
                    ("ARTIF_NOT_CONSU", "Artificiel non consommé"),
                    ("NONE", "Non renseigné"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_artificial",
            field=models.BooleanField(default=False, verbose_name="Artificiel"),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_consumed",
            field=models.BooleanField(default=False, verbose_name="Consommé"),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_natural",
            field=models.BooleanField(default=False, verbose_name="Naturel"),
        ),
    ]
