# Generated by Django 3.2.5 on 2021-12-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0028_consocerema"),
    ]

    operations = [
        migrations.AddField(
            model_name="consocerema",
            name="arti_hab",
            field=models.FloatField(default=0, verbose_name="arti_hab"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consocerema",
            name="naf_arti",
            field=models.FloatField(verbose_name="naf_arti"),
        ),
    ]
