# Generated by Django 3.2.5 on 2021-12-16 21:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0029_auto_20211216_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consocerema",
            name="mpoly",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
