# Generated by Django 3.2.5 on 2021-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0033_departement_epci_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="epci",
            name="departement",
            field=models.ManyToManyField(to="public_data.Departement"),
        ),
        migrations.AlterField(
            model_name="departement",
            name="is_artif_ready",
            field=models.BooleanField(
                default=False, verbose_name="Données artif disponibles"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="name",
            field=models.CharField(max_length=23, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="departement",
            name="source_id",
            field=models.CharField(max_length=3, verbose_name="Identifiant source"),
        ),
        migrations.AlterField(
            model_name="epci",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="epci",
            name="source_id",
            field=models.CharField(max_length=9, verbose_name="Identifiant source"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=27, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="region",
            name="source_id",
            field=models.CharField(max_length=2, verbose_name="Identifiant source"),
        ),
    ]
