# Generated by Django 3.2.5 on 2021-12-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0034_auto_20211224_1615"),
    ]

    operations = [
        migrations.RenameField(
            model_name="epci",
            old_name="departement",
            new_name="departements",
        ),
    ]
