# Generated by Django 3.2.5 on 2022-01-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0035_rename_departement_epci_departements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="public_data.region"
            ),
        ),
    ]
