# Generated by Django 3.2.5 on 2022-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0036_alter_departement_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="refplan",
            name="naf11art20",
            field=models.FloatField(null=True),
        ),
    ]
