# Generated by Django 3.2.5 on 2022-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0038_commune"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="ocsge_millesimes",
            field=models.CharField(max_length=100, null=True, verbose_name="Millesimes OCSGE dispo"),
        ),
    ]
