# Generated by Django 3.2.5 on 2022-01-12 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0039_departement_ocsge_millesimes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refplan",
            old_name="naf11art20",
            new_name="naf11art21",
        ),
    ]
