# Generated by Django 3.2.5 on 2022-01-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0041_auto_20220114_1613"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cerema",
            table=None,
        ),
    ]
