# Generated by Django 3.2.11 on 2022-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0043_alter_cerema_city_insee"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="colour",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Couleur d'afficgage"
            ),
        ),
    ]
