# Generated by Django 3.2.11 on 2022-04-04 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0044_commune_colour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commune",
            old_name="colour",
            new_name="map_color",
        ),
    ]
