# Generated by Django 3.2.11 on 2022-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0045_rename_colour_commune_map_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsge",
            name="code_or",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Code OR"),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="id_origine",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="ID origine"),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="id_source",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="ID source"),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="millesime_source",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="SOurce du millesime",
            ),
        ),
    ]
