# Generated by Django 3.2.11 on 2022-04-26 16:45

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import public_data.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0046_auto_20220425_1607"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcsgeDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_old",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Ancienne année",
                    ),
                ),
                (
                    "year_new",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Nouvelle année",
                    ),
                ),
                (
                    "cs_new",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Code nouvelle couverture",
                    ),
                ),
                (
                    "cs_old",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Code ancienne couverture",
                    ),
                ),
                (
                    "us_new",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Code nouveau usage",
                    ),
                ),
                (
                    "us_old",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Code ancien usage",
                    ),
                ),
                (
                    "oss_old",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Ancien OSS"
                    ),
                ),
                (
                    "oss_new",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nouveau OSS",
                    ),
                ),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="surface",
                    ),
                ),
                (
                    "cs_old_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Ancienne couverture",
                    ),
                ),
                (
                    "us_old_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Ancien usage",
                    ),
                ),
                (
                    "cs_new_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Nouvelle couverture",
                    ),
                ),
                (
                    "us_new_label",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Nouveau usage",
                    ),
                ),
                ("old_is_artif", models.BooleanField(blank=True, null=True)),
                ("new_is_artif", models.BooleanField(blank=True, null=True)),
                ("is_new_artif", models.BooleanField(blank=True, null=True)),
                ("is_new_naf", models.BooleanField(blank=True, null=True)),
            ],
            bases=(
                public_data.models.mixins.AutoLoadMixin,
                public_data.models.mixins.DataColorationMixin,
                models.Model,
            ),
        ),
    ]
