# Generated by Django 3.2.13 on 2022-05-04 10:41

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models

import public_data.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0047_ocsgediff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneConstruite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_source",
                    models.CharField(max_length=200, verbose_name="ID Source"),
                ),
                (
                    "millesime",
                    models.CharField(max_length=200, verbose_name="Millesime"),
                ),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Année",
                    ),
                ),
            ],
            bases=(
                public_data.models.mixins.AutoLoadMixin,
                public_data.models.mixins.DataColorationMixin,
                models.Model,
            ),
        ),
        migrations.AlterField(
            model_name="ocsge",
            name="millesime_source",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Source du millesime",
            ),
        ),
    ]
