# Generated by Django 3.2.13 on 2022-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0048_auto_20220504_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneconstruite",
            name="surface",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="surface",
            ),
        ),
    ]
