# Generated by Django 3.2.13 on 2022-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0049_zoneconstruite_surface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_artificial",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Artificiel"
            ),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_consumed",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Consommé"
            ),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_natural",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Naturel"
            ),
        ),
    ]
