# Generated by Django 3.2.13 on 2022-05-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0050_auto_20220509_0838"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsge",
            name="map_color",
        ),
        migrations.AddField(
            model_name="ocsge",
            name="is_artificial",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Est artificiel"
            ),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="matrix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.couvertureusagematrix",
            ),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="surface",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="surface",
            ),
        ),
    ]
