# Generated by Django 3.2.13 on 2022-05-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0051_auto_20220509_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsgediff",
            name="new_matrix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocsge_difnew",
                to="public_data.couvertureusagematrix",
            ),
        ),
        migrations.AddField(
            model_name="ocsgediff",
            name="old_matrix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocsge_dif_old",
                to="public_data.couvertureusagematrix",
            ),
        ),
    ]
