# Generated by Django 3.2.13 on 2022-05-10 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0052_auto_20220509_1245"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocsgediff",
            old_name="is_new_naf",
            new_name="is_new_natural",
        ),
    ]
