# Generated by Django 3.2.13 on 2022-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0055_communediff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsge",
            name="code_or",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="commentaire",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="origine",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="origine2",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="ossature",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="oss_new",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="oss_old",
        ),
    ]
