# Generated by Django 3.2.13 on 2022-05-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0058_communesol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communesol",
            old_name="surface_artif",
            new_name="surface",
        ),
    ]
