# Generated by Django 3.2.13 on 2022-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0059_rename_surface_artif_communesol_surface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="couverture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.couverturesol",
            ),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="usage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.usagesol",
            ),
        ),
    ]
