# Generated by Django 3.2.13 on 2022-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0062_auto_20220512_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="cerema",
            name="art11act21",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art11hab21",
            field=models.FloatField(null=True),
        ),
    ]
