# Generated by Django 3.2.13 on 2022-05-16 07:03

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import public_data.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0063_auto_20220513_0833"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtificialArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Année",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(decimal_places=4, max_digits=15, verbose_name="surface"),
                ),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_data.commune",
                    ),
                ),
            ],
            bases=(
                public_data.models.mixins.DataColorationMixin,
                models.Model,
            ),
        ),
    ]
