# Generated by Django 3.2.13 on 2022-05-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0064_artificialarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artificialarea",
            name="city",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="public_data.commune"),
        ),
    ]
