# Generated by Django 3.2.13 on 2022-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0066_auto_20220516_0720"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneconstruite",
            name="builded_density",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Densité construite",
            ),
        ),
    ]
