# Generated by Django 3.2.13 on 2022-06-09 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0067_zoneconstruite_builded_density"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zoneconstruite",
            old_name="builded_density",
            new_name="built_density",
        ),
    ]
