# Generated by Django 3.2.13 on 2022-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0068_rename_builded_density_zoneconstruite_built_density"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ocsge",
            index=models.Index(fields=["year"], name="public_data_year_3fae3a_idx"),
        ),
    ]
