# Generated by Django 3.2.14 on 2022-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0074_auto_20220726_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="insee",
            field=models.CharField(max_length=7, verbose_name="Code INSEE"),
        ),
        migrations.AlterField(
            model_name="commune",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="departement",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="departement",
            name="source_id",
            field=models.CharField(max_length=50, verbose_name="Identifiant source"),
        ),
        migrations.AlterField(
            model_name="epci",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="epci",
            name="source_id",
            field=models.CharField(max_length=50, verbose_name="Identifiant source"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="region",
            name="source_id",
            field=models.CharField(max_length=50, verbose_name="Identifiant source"),
        ),
    ]
