# Generated by Django 3.2.15 on 2022-08-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0075_auto_20220728_1543"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArtifCommune",
        ),
        migrations.DeleteModel(
            name="Artificialisee2015to2018",
        ),
        migrations.DeleteModel(
            name="Artificielle2018",
        ),
        migrations.DeleteModel(
            name="CommunesSybarval",
        ),
        migrations.DeleteModel(
            name="EnveloppeUrbaine2018",
        ),
        migrations.DeleteModel(
            name="Renaturee2018to2015",
        ),
        migrations.DeleteModel(
            name="Sybarval",
        ),
        migrations.DeleteModel(
            name="Voirie2018",
        ),
        migrations.DeleteModel(
            name="ZonesBaties2018",
        ),
        migrations.DeleteModel(
            name="Ocsge2015",
        ),
        migrations.DeleteModel(
            name="Ocsge2018",
        ),
    ]
