# Generated by Django 3.2.15 on 2022-08-25 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0076_auto_20220825_1423"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunePop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Millésime",
                    ),
                ),
                ("pop", models.IntegerField(verbose_name="Population")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pop",
                        to="public_data.commune",
                        verbose_name="Commune",
                    ),
                ),
            ],
        ),
    ]
