# Generated by Django 3.2.15 on 2022-08-26 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0078_auto_20220826_1010"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communepop",
            old_name="menage",
            new_name="household",
        ),
    ]
