# Generated by Django 3.2.16 on 2022-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0081_auto_20221215_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scot",
            name="detailed_state_statut",
            field=models.CharField(
                max_length=250, verbose_name="Libellé Etat détaillé"
            ),
        ),
        migrations.AlterField(
            model_name="scot",
            name="is_ene_law",
            field=models.BooleanField(
                default=False, verbose_name="Intégration disposition loi ENE"
            ),
        ),
        migrations.AlterField(
            model_name="scot",
            name="is_inter_departement",
            field=models.BooleanField(default=False, verbose_name="interdépartemental"),
        ),
        migrations.AlterField(
            model_name="scot",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="scot",
            name="scot_type",
            field=models.CharField(max_length=250, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="scot",
            name="siren",
            field=models.CharField(max_length=12, verbose_name="Siren"),
        ),
        migrations.AlterField(
            model_name="scot",
            name="state_statut",
            field=models.CharField(
                max_length=250, verbose_name="Libellé Etat simplifié"
            ),
        ),
    ]
