# Generated by Django 3.2.16 on 2023-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0082_auto_20221216_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couverturesol",
            name="label_short",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Libellé court"),
        ),
        migrations.AlterField(
            model_name="usagesol",
            name="label_short",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Libellé court"),
        ),
    ]
