# Generated by Django 4.2 on 2023-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0084_auto_20230120_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cerema",
            name="city_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="dept_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="dept_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="epci_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="epci_name",
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="region_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="region_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
