# Generated by Django 4.2.1 on 2023-05-15 07:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0085_alter_cerema_city_name_alter_cerema_dept_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneUrba",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gid", models.CharField(max_length=80, verbose_name="gid")),
                ("libelle", models.CharField(max_length=80, verbose_name="libelle")),
                ("libelong", models.CharField(max_length=254, verbose_name="libelong")),
                ("typezone", models.CharField(max_length=80, verbose_name="typezone")),
                ("insee", models.CharField(max_length=80, verbose_name="insee")),
                ("idurba", models.CharField(max_length=80, verbose_name="idurba")),
                ("idzone", models.CharField(max_length=80, verbose_name="idzone")),
                ("lib_idzone", models.CharField(max_length=80, verbose_name="lib_idzone")),
                ("partition", models.CharField(max_length=80, verbose_name="partition")),
                ("destdomi", models.CharField(max_length=80, verbose_name="destdomi")),
                ("nomfic", models.CharField(max_length=80, verbose_name="nomfic")),
                ("urlfic", models.CharField(max_length=178, verbose_name="urlfic")),
                ("datappro", models.CharField(max_length=80, verbose_name="datappro")),
                ("datvalid", models.CharField(max_length=80, verbose_name="datvalid")),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
