# Generated by Django 4.2.1 on 2023-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0086_zoneurba"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoneurba",
            name="datappro",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="datappro"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="datvalid",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="datvalid"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="destdomi",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="destdomi"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="gid",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="gid"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="idurba",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="idurba"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="idzone",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="idzone"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="insee",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="insee"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="lib_idzone",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="lib_idzone"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="libelle",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="libelle"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="libelong",
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name="libelong"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="nomfic",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="nomfic"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="partition",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="partition"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="typezone",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="typezone"),
        ),
        migrations.AlterField(
            model_name="zoneurba",
            name="urlfic",
            field=models.CharField(blank=True, max_length=178, null=True, verbose_name="urlfic"),
        ),
    ]
