# Generated by Django 4.2.1 on 2023-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0087_alter_zoneurba_datappro_alter_zoneurba_datvalid_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ocsge",
            index=models.Index(fields=["is_artificial"], name="public_data_is_arti_05643d_idx"),
        ),
    ]
