# Generated by Django 4.2.3 on 2023-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0092_artifareazoneurba_remove_zoneurba_artificial_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="area",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name="Surface"),
        ),
    ]
