# Generated by Django 4.2.4 on 2023-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0094_cerema_art09fer10_cerema_art09rou10_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cerema",
            old_name="art09act21",
            new_name="art09act22",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09hab21",
            new_name="art09hab22",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09inc21",
            new_name="art09inc22",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09mix21",
            new_name="art09mix22",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="artcom0921",
            new_name="artcom0922",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="artpop1318",
            new_name="artpop1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="emp1318",
            new_name="emp1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="emp18",
            new_name="emp19",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="men1318",
            new_name="men1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="men18",
            new_name="men19",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="menhab1318",
            new_name="menhab1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="mepart1318",
            new_name="mepart1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="naf09art21",
            new_name="naf09art22",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="pop1318",
            new_name="pop1319",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="pop18",
            new_name="pop19",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="surfcom202",
            new_name="surfcom2022",
        ),
    ]
