# Generated by Django 4.2.4 on 2023-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0095_rename_art09act21_cerema_art09act22_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cerema",
            name="aav2020txt",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art09fer22",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art09rou22",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="artcom2020",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="cerema",
            name="aav2020_ty",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
