# Generated by Django 4.2.5 on 2023-09-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0098_alter_scot_siren"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cerema",
            index=models.Index(fields=["scot"], name="public_data_scot_3f2e32_idx"),
        ),
        migrations.AddIndex(
            model_name="cerema",
            index=models.Index(fields=["region_id"], name="public_data_region__3542c1_idx"),
        ),
        migrations.AddIndex(
            model_name="cerema",
            index=models.Index(fields=["dept_id"], name="public_data_dept_id_005d86_idx"),
        ),
        migrations.AddIndex(
            model_name="cerema",
            index=models.Index(fields=["epci_id"], name="public_data_epci_id_4b2686_idx"),
        ),
    ]
