# Generated by Django 4.2.5 on 2023-09-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0099_cerema_public_data_scot_3f2e32_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="epci",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="public_data.epci"
            ),
        ),
    ]
