# Generated by Django 4.2.6 on 2023-10-23 14:23

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0100_alter_commune_epci"),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
