# Generated by Django 4.2.6 on 2023-11-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0101_auto_20231023_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsge",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.departement",
            ),
        ),
    ]
