# Generated by Django 4.2.6 on 2023-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0101_auto_20231023_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="artificialarea",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="cerema",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="departement",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="epci",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="ocsge",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="ocsgediff",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="scot",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="zoneconstruite",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AddField(
            model_name="zoneurba",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "Lambert 93"),
                    (32620, "Wgs 84 Utm Zone 20"),
                    (2972, "Rgfg 95 Utm Zone 22N"),
                    (2975, "Rgr 92 Utm Zone 40S"),
                    (4326, "Wgs 84"),
                    (3857, "Web Mercator"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
    ]
