# Generated by Django 4.2.6 on 2023-11-17 14:56

from django.core.management import call_command
from django.db import migrations

from logging import getLogger

logger = getLogger(__name__)


def reimport_ocsge(apps, schema_editor):
    call_command("load_ocsge", item="GersOcsge2016")
    # TODO after updating load_ocsge to import data with departements


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0102_ocsge_departement"),
    ]

    operations = [
        migrations.RunPython(reimport_ocsge),
    ]
