# Generated by Django 4.2.6 on 2023-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0102_ocsge_departement"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsgediff",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.departement",
            ),
        ),
        migrations.AddField(
            model_name="zoneconstruite",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.departement",
            ),
        ),
    ]
