# Generated by Django 4.2.6 on 2023-11-22 08:43

from django.db import migrations, models
import django.db.models.deletion

from logging import getLogger

logger = getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0104_ocsgediff_departement_zoneconstruite_departement"),
    ]

    operations = [
        migrations.AddField(
            model_name="artificialarea",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="public_data.departement",
            ),
        ),
    ]
