# Generated by Django 4.2.6 on 2023-11-22 08:43

from django.core.management import call_command
from django.db import migrations

from logging import getLogger

logger = getLogger(__name__)


def reimport_ocsge(apps, schema_editor):
    Ocsge = apps.get_model("public_data", "Ocsge")
    OcsgeDiff = apps.get_model("public_data", "OcsgeDiff")
    ZoneConstruite = apps.get_model("public_data", "ZoneConstruite")

    Ocsge.objects.all().delete()
    OcsgeDiff.objects.all().delete()
    ZoneConstruite.objects.all().delete()

    call_command(command_name="load_ocsge", item="GersOcsge2016")
    call_command(command_name="load_ocsge", item="GersOcsge2019")
    call_command(command_name="load_ocsge", item="GersOcsgeDiff")
    call_command(command_name="load_ocsge", item="GersZoneConstruite2016")
    call_command(command_name="load_ocsge", item="GersZoneConstruite2019")

    call_command(command_name="load_ocsge", item="EssonneOcsge2018")
    call_command(command_name="load_ocsge", item="EssonneOcsge2021")
    call_command(command_name="load_ocsge", item="EssonneOcsgeDiff1821")
    call_command(command_name="load_ocsge", item="EssonneOcsgeZoneConstruite2018")
    call_command(command_name="load_ocsge", item="EssonneOcsgeZoneConstruite2021")

    call_command(command_name="load_ocsge", item="SeineEtMarneOcsge2017")
    call_command(command_name="load_ocsge", item="SeineEtMarneOcsge2021")
    call_command(command_name="load_ocsge", item="SeineEtMarneOcsgeDiff1721")
    call_command(command_name="load_ocsge", item="SeineEtMarneOcsgeZoneConstruite2017")
    call_command(command_name="load_ocsge", item="SeineEtMarneOcsgeZoneConstruite2021")


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0104_ocsgediff_departement_zoneconstruite_departement"),
    ]

    operations = [
        migrations.RunPython(reimport_ocsge),
    ]
