# Generated by Django 4.2.6 on 2023-11-29 10:56

from django.db import migrations


def set_gers_to_ocsge_related_departement(apps, schema_editor):
    Departement = apps.get_model("public_data", "Departement")

    Ocsge = apps.get_model("public_data", "Ocsge")
    OcsgeDiff = apps.get_model("public_data", "OcsgeDiff")
    ZoneConstruite = apps.get_model("public_data", "ZoneConstruite")
    ArtificialArea = apps.get_model("public_data", "ArtificialArea")

    gers = Departement.objects.get(name="Gers")

    Ocsge.objects.update(departement=gers)
    OcsgeDiff.objects.update(departement=gers)
    ZoneConstruite.objects.update(departement=gers)
    ArtificialArea.objects.update(departement=gers)


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0105_auto_20231122_0843"),
    ]

    operations = [
        migrations.RunPython(set_gers_to_ocsge_related_departement),
    ]
