# Generated by Django 4.2.6 on 2023-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0105_auto_20231122_0843"),
    ]

    operations = []
