# Generated by Django 4.2.7 on 2023-11-30 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0102_remove_zoneconstruite_built_density"),
        ("public_data", "0106_artificialarea_departement"),
    ]

    operations = []
