# Generated by Django 4.2.7 on 2023-11-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0107_merge_20231130_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="ocsge_coverage_status",
            field=models.CharField(
                choices=[
                    ("COMPlETE_NOT_UNIFORM", "Complète mais non uniforme"),
                    ("COMPLETE_UNIFORM", "Complète et uniforme"),
                    ("PARTIAL", "Partielle"),
                    ("NOT_AVAILABLE", "Non disponible"),
                ],
                default="NOT_AVAILABLE",
                max_length=50,
                verbose_name="Statut de couverture OCSGE",
            ),
        ),
    ]
