# Generated by Django 4.2.7 on 2023-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0108_commune_ocsge_coverage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="ocsge_coverage_status",
            field=models.CharField(
                choices=[("AVAILABLE", "Disponible"), ("NOT_AVAILABLE", "Non disponible")],
                default="NOT_AVAILABLE",
                max_length=50,
                verbose_name="Statut de couverture OCSGE",
            ),
        ),
    ]
