# Generated by Django 4.2.7 on 2023-11-30 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0109_alter_commune_ocsge_coverage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="first_millesime",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Premier millésime disponible",
            ),
        ),
    ]
