# Generated by Django 4.2.6 on 2023-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0110_commune_first_millesime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="ocsge_coverage_status",
        ),
        migrations.AddField(
            model_name="commune",
            name="ocsge_available",
            field=models.BooleanField(default=False, verbose_name="Statut de couverture OCSGE"),
        ),
    ]
