# Generated by Django 4.2.7 on 2024-01-09 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0102_artificialarea_srid_source_cerema_srid_source_and_more"),
        ("public_data", "0112_rename_ocsge_millesimes_departement_ocsge_millesimes_old"),
    ]

    operations = []
