# Generated by Django 4.2.7 on 2024-01-23 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0113_datasource"),
        ("public_data", "0113_merge_20240109_0833"),
    ]

    operations = []
