# Generated by Django 4.2.9 on 2024-01-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0116_alter_datasource_millesimes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="official_land_id",
            field=models.CharField(
                default="no set",
                help_text=(
                    "\nID officiel du territoire (code INSEE, SIREN, etc.) <br />"
                    "\nPeut-être vide si la donnée ne concerne pas un territoire spécifique"
                    "\n(par exemple, s'il concerne la France entière, ou un DROM-COM entier)"
                ),
                max_length=255,
                verbose_name="ID du territoire",
            ),
            preserve_default=False,
        ),
    ]
