# Generated by Django 4.2.7 on 2024-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0117_alter_datasource_official_land_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifareazoneurba",
            name="area",
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name="Surface artificialisée"),
        ),
    ]
