# Generated by Django 4.2.7 on 2024-02-20 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0117_alter_datasource_official_land_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="couvertureusagematrix",
            unique_together={("couverture", "usage")},
        ),
    ]
