# Generated by Django 4.2.9 on 2024-03-27 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0118_alter_artifareazoneurba_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsge",
            name="couverture_label",
        ),
        migrations.RemoveField(
            model_name="ocsge",
            name="usage_label",
        ),
    ]
