# Generated by Django 4.2.9 on 2024-04-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0118_alter_artifareazoneurba_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sudocuh",
            fields=[
                ("code_insee", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("code_departement", models.CharField(max_length=200)),
                ("nom_region", models.CharField(max_length=200)),
                ("nom_commune", models.CharField(max_length=200)),
                (
                    "collectivite_porteuse",
                    models.CharField(
                        help_text="Nom de la collectivité qui a la compétence PLU (DU)",
                        max_length=200,
                        verbose_name="Collectivité porteuse",
                    ),
                ),
                (
                    "siren_epci",
                    models.CharField(
                        blank=True,
                        help_text="Indiqué lorsque la collectivité porteuse est de type EPCI",
                        max_length=200,
                        null=True,
                        verbose_name="SIREN EPCI",
                    ),
                ),
                (
                    "code_etat",
                    models.CharField(
                        help_text="Sur 2 caracteres, le premier codifie le document opposable (1-CC, 2-POS, 3-PLU, 9-RNU), le 2e caractere codifie le type de DU de la procédure en cours (1-CC, 3-PLU, 9- Aucune procédure en cours)",
                        max_length=2,
                        verbose_name="Code état",
                    ),
                ),
                (
                    "du_opposable",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Carte communale"),
                            ("POS", "Plan d'occupation des sols"),
                            ("PLU", "Plan local d'urbanisme"),
                            ("RNU", "Règlement national d'urbanisme"),
                            ("PLUi", "Plan local d'urbanisme intercommunal"),
                            ("PLUiS", "Plan local d'urbanisme intercommunal simplifié"),
                        ],
                        help_text="DU opposable sur la commune (RNU, CC, POS, PLU, PLUi ou PLUiS)",
                        max_length=200,
                        null=True,
                        verbose_name="Document d'urbanisme opposable",
                    ),
                ),
                (
                    "du_en_cours",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Carte communale"),
                            ("POS", "Plan d'occupation des sols"),
                            ("PLU", "Plan local d'urbanisme"),
                            ("RNU", "Règlement national d'urbanisme"),
                            ("PLUi", "Plan local d'urbanisme intercommunal"),
                            ("PLUiS", "Plan local d'urbanisme intercommunal simplifié"),
                        ],
                        help_text="DU en cours sur la commune (Aucun, CC, PLU, PLUi ou PLUiS)",
                        max_length=200,
                        null=True,
                        verbose_name="Document d'urbanisme en cours",
                    ),
                ),
                ("code_bcsi", models.CharField(max_length=200)),
                ("etat_commune", models.CharField(max_length=200)),
                ("etat_detaille", models.CharField(max_length=200)),
                (
                    "prescription_du_en_vigueur",
                    models.DateField(blank=True, null=True, verbose_name="Prescription du DU en vigueur"),
                ),
                (
                    "approbation_du_en_vigueur",
                    models.DateField(blank=True, null=True, verbose_name="Approbation du DU en vigueur"),
                ),
                (
                    "executoire_du_en_vigueur",
                    models.DateField(blank=True, null=True, verbose_name="Executoire du DU en vigueur"),
                ),
                (
                    "prescription_proc_en_cours",
                    models.DateField(blank=True, null=True, verbose_name="Prescription de la procédure en cours"),
                ),
                ("population_municipale", models.IntegerField()),
                ("population_totale", models.IntegerField()),
                ("superficie", models.FloatField(verbose_name="Superficie (en ha)")),
            ],
        ),
    ]
