# Generated by Django 4.2.9 on 2024-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0119_remove_ocsge_couverture_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsge",
            name="temp_departement",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Département"),
        ),
    ]
