# Generated by Django 4.2.7 on 2024-02-21 18:59

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    OcsgeDiff = apps.get_model("public_data", "OcsgeDiff")
    CouvertureUsageMatrix = apps.get_model("public_data", "CouvertureUsageMatrix")

    OcsgeDiff.objects.filter(Q(us_new=None) | Q(us_old=None) | Q(cs_new=None) | Q(cs_old=None)).delete()

    CouvertureUsageMatrix.objects.filter(Q(usage=None) | Q(couverture=None)).delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("public_data", "0119_remove_couvertureusagematrix_is_consumed_and_more"),
    ]

    operations = [
        migrations.RunPython(code=forwards_func),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="couverture",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="public_data.couverturesol"),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="is_artificial",
            field=models.BooleanField(default=False, verbose_name="Artificiel"),
        ),
        migrations.AlterField(
            model_name="couvertureusagematrix",
            name="usage",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="public_data.usagesol"),
        ),
    ]
