# Generated by Django 4.2.9 on 2024-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0120_alter_sudocuh_du_en_cours_alter_sudocuh_du_opposable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudocuh",
            name="code_etat",
            field=models.CharField(
                help_text="Sur 2 caracteres, le premier codifie le document opposable(1-CC, 2-POS, 3-PLU, 9-RNU), le 2e caractere codifie le type de DU de la procédure en cours (1-CC, 3-PLU, 9- Aucune procédure en cours)",
                max_length=2,
                verbose_name="Code état",
            ),
        ),
        migrations.AlterField(
            model_name="sudocuh",
            name="du_en_cours",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Carte communale"),
                    ("POS", "Plan d'occupation des sols"),
                    ("PLU", "Plan local d'urbanisme"),
                    ("RNU", "Règlement national d'urbanisme"),
                    ("PLUi", "Plan local d'urbanisme intercommunal"),
                    ("PLUiS", "Plan local d'urbanisme intercommunal simplifié"),
                ],
                help_text="Document d'urbanisme en cours de création / révision sur la commune (CC, POS, PLU, RNU, PLUi, PLUiS)",
                max_length=200,
                null=True,
                verbose_name="Document d'urbanisme en cours",
            ),
        ),
    ]
