# Generated by Django 4.2.9 on 2024-03-25 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0118_alter_artifareazoneurba_area"),
        ("public_data", "0120_alter_couvertureusagematrix_couverture_and_more"),
    ]

    operations = []
