# Generated by Django 4.2.9 on 2024-03-27 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0121_auto_20240327_1105"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsge",
            name="departement",
        ),
    ]
