# Generated by Django 4.2.9 on 2024-03-27 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0122_remove_ocsge_temp_departement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocsge",
            old_name="temp_departement",
            new_name="departement",
        )
    ]
