# Generated by Django 4.2.9 on 2024-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0124_remove_ocsge_matrix_alter_ocsge_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocsge",
            name="couverture",
            field=models.CharField(max_length=254, verbose_name="Couverture du sol"),
        ),
        migrations.AlterField(
            model_name="ocsge",
            name="id_source",
            field=models.CharField(max_length=200, verbose_name="ID source"),
        ),
        migrations.AlterField(
            model_name="ocsge",
            name="is_artificial",
            field=models.BooleanField(verbose_name="Est artificiel"),
        ),
        migrations.AlterField(
            model_name="ocsge",
            name="surface",
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name="surface"),
        ),
        migrations.AlterField(
            model_name="ocsge",
            name="usage",
            field=models.CharField(max_length=254, verbose_name="Usage du sol"),
        ),
    ]
