# Generated by Django 4.2.9 on 2024-03-27 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0125_alter_ocsge_couverture_alter_ocsge_id_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneconstruite",
            name="temp_departement",
            field=models.CharField(max_length=15, verbose_name="Département", blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="zoneconstruite",
            name="departement",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="public_data.departement"),
        ),
        migrations.AlterField(
            model_name="zoneconstruite",
            name="surface",
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name="surface"),
        ),
        migrations.AlterField(
            model_name="zoneconstruite",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Année",
            ),
        ),
    ]
