# Generated by Django 4.2.9 on 2024-03-27 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0126_zoneconstruite_temp_departement_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public_data_zoneconstruite
            SET temp_departement = (
                SELECT source_id FROM
                    public_data_departement WHERE id = departement_id
            )
            WHERE temp_departement IS NULL;
            """
        )
    ]
