# Generated by Django 4.2.9 on 2024-03-27 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0128_remove_zoneconstruite_departement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zoneconstruite",
            old_name="temp_departement",
            new_name="departement",
        ),
    ]
