# Generated by Django 4.2.9 on 2024-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0129_rename_temp_departement_zoneconstruite_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoneconstruite",
            name="departement",
            field=models.CharField(max_length=15, verbose_name="Département"),
        ),
    ]
