# Generated by Django 4.2.9 on 2024-03-27 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0131_artificialarea_temp_departement"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public_data_artificialarea
            SET temp_departement = COALESCE((
                SELECT source_id FROM
                    public_data_departement WHERE id = departement_id
            ), (
                SELECT source_id FROM
                    public_data_departement WHERE ST_intersects(
                    mpoly,
                    ST_PointOnSurface(public_data_artificialarea.mpoly)
                )
            ))
            WHERE temp_departement IS NULL;
            """
        )
    ]
