# Generated by Django 4.2.9 on 2024-03-27 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0132_auto_20240327_1604"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artificialarea",
            name="departement",
        ),
    ]
