# Generated by Django 4.2.9 on 2024-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0133_remove_artificialarea_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artificialarea",
            name="temp_departement",
            field=models.CharField(max_length=15, verbose_name="Département"),
        ),
    ]
