# Generated by Django 4.2.9 on 2024-03-27 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0134_alter_artificialarea_temp_departement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artificialarea",
            old_name="temp_departement",
            new_name="departement",
        ),
    ]
