# Generated by Django 4.2.9 on 2024-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0136_ocsgediff_temp_departement"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public_data_ocsgediff
            SET temp_departement = (
                SELECT source_id FROM
                    public_data_departement WHERE id = departement_id
            )
            WHERE temp_departement IS NULL;
            """
        )
    ]
