# Generated by Django 4.2.9 on 2024-03-27 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0138_remove_ocsgediff_departement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocsgediff",
            old_name="temp_departement",
            new_name="departement",
        ),
    ]
