# Generated by Django 4.2.9 on 2024-03-27 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0139_rename_temp_departement_ocsgediff_departement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsgediff",
            name="new_matrix",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="old_matrix",
        ),
    ]
