# Generated by Django 4.2.9 on 2024-03-27 17:37

from django.db import migrations
from django.db.models import Q


def remove_invalid_diff_objects(apps, schema_editor):
    OcsgeDiff = apps.get_model("public_data", "OcsgeDiff")
    OcsgeDiff.objects.filter(Q(us_new=None) | Q(us_old=None) | Q(cs_new=None) | Q(cs_old=None)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0140_remove_ocsgediff_new_matrix_and_more"),
    ]

    operations = [
        migrations.RunPython(code=remove_invalid_diff_objects),
    ]
