# Generated by Django 4.2.9 on 2024-03-27 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0141_auto_20240327_1737"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsgediff",
            name="cs_new_label",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="cs_old_label",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="us_new_label",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="us_old_label",
        ),
    ]
