# Generated by Django 4.2.9 on 2024-03-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0143_alter_ocsgediff_cs_new_alter_ocsgediff_cs_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocsgediff",
            name="departement",
            field=models.CharField(max_length=15, verbose_name="Département"),
        ),
        migrations.AlterField(
            model_name="ocsgediff",
            name="is_new_artif",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="ocsgediff",
            name="is_new_natural",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="ocsgediff",
            name="new_is_artif",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="ocsgediff",
            name="old_is_artif",
            field=models.BooleanField(),
        ),
    ]
