# Generated by Django 4.2.9 on 2024-03-27 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0144_alter_ocsgediff_departement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocsgediff",
            name="new_is_artif",
        ),
        migrations.RemoveField(
            model_name="ocsgediff",
            name="old_is_artif",
        ),
    ]
