# Generated by Django 4.2.9 on 2024-03-27 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0145_remove_ocsgediff_new_is_artif_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocsge",
            unique_together={("id_source", "year", "departement")},
        ),
    ]
