# Generated by Django 4.2.9 on 2024-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0146_alter_ocsge_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="shapefile_name",
            field=models.CharField(default="", max_length=255, verbose_name="Nom du shapefile"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datasource",
            name="productor",
            field=models.CharField(
                choices=[
                    ("IGN", "Institut national de l'information géographique et forestière"),
                    (
                        "CEREMA",
                        "Centre d'études et d'expertise sur les risques, l'environnement, la mobilité et l'aménagement",
                    ),
                    ("MDA", "Mon Diagnostic Artficialisation"),
                ],
                max_length=255,
                verbose_name="Producteur",
            ),
        ),
    ]
