# Generated by Django 4.2.9 on 2024-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0147_datasource_shapefile_name_alter_datasource_productor"),
    ]

    operations = [
        migrations.AddField(
            model_name="artificialarea",
            name="city_temp",
            field=models.CharField(default=" ", max_length=254, verbose_name="Commune"),
            preserve_default=False,
        ),
    ]
