# Generated by Django 4.2.9 on 2024-04-04 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0148_artificialarea_city_temp"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public_data_artificialarea
            SET city_temp = (
                SELECT insee FROM public_data_commune
                WHERE id = city_id
            )
            WHERE city_temp = ' ';
            """
        )
    ]
