# Generated by Django 4.2.9 on 2024-04-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0149_auto_20240404_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artificialarea",
            name="city",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="public_data.commune"),
        ),
    ]
