# Generated by Django 4.2.9 on 2024-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0150_alter_artificialarea_city"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artificialarea",
            name="artificialarea-city-year-unique",
        ),
        migrations.RemoveIndex(
            model_name="artificialarea",
            name="public_data_city_id_764b05_idx",
        ),
        migrations.RemoveIndex(
            model_name="artificialarea",
            name="public_data_city_id_26b070_idx",
        ),
        migrations.RemoveField(
            model_name="artificialarea",
            name="city",
        ),
    ]
