# Generated by Django 4.2.9 on 2024-04-04 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0151_remove_artificialarea_artificialarea_city_year_unique_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artificialarea",
            old_name="city_temp",
            new_name="city",
        ),
    ]
