# Generated by Django 4.2.9 on 2024-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0152_rename_city_temp_artificialarea_city"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artificialarea",
            index=models.Index(fields=["city"], name="public_data_city_201666_idx"),
        ),
    ]
