# Generated by Django 4.2.9 on 2024-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0153_artificialarea_public_data_city_201666_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(
                choices=[
                    ("OCCUPATION_DU_SOL", "Couverture et usage du sol"),
                    ("DIFFERENCE", "Différence entre deux OCSGE"),
                    ("ZONE_CONSTRUITE", "Zone construite"),
                    ("ZONE_ARTIFICIELLE", "Zone artificielle"),
                    ("CONSOMMATION_ESPACE", "Consommation d'espace"),
                ],
                help_text="Nom de la couche de données au sein du jeu de donnée",
                max_length=255,
                verbose_name="Nom",
            ),
        ),
    ]
