# Generated by Django 4.2.9 on 2024-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0155_ocsge_public_data_departe_688545_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artificialarea",
            index=models.Index(fields=["departement"], name="public_data_departe_f0a42d_idx"),
        ),
        migrations.AddIndex(
            model_name="ocsgediff",
            index=models.Index(fields=["departement"], name="public_data_departe_0f69ff_idx"),
        ),
        migrations.AddIndex(
            model_name="zoneconstruite",
            index=models.Index(fields=["departement"], name="public_data_departe_cd76cc_idx"),
        ),
    ]
