# Generated by Django 4.2.9 on 2024-04-17 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0119_sudocuh"),
        ("public_data", "0157_alter_datasource_dataset_alter_datasource_name"),
    ]

    operations = []
