# Generated by Django 4.2.9 on 2024-04-18 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0121_alter_sudocuh_code_etat_alter_sudocuh_du_en_cours"),
        ("public_data", "0158_merge_20240417_1100"),
    ]

    operations = []
