# Generated by Django 4.2.11 on 2024-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0160_alter_sudocuh_du_en_cours"),
    ]

    operations = [
        migrations.AddField(
            model_name="cerema",
            name="art22act23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art22fer23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art22hab23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art22inc23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art22mix23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="art22rou23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cerema",
            name="naf22art23",
            field=models.FloatField(null=True),
        ),
    ]
