# Generated by Django 4.2.11 on 2024-05-02 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0161_cerema_art22act23_cerema_art22fer23_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cerema",
            old_name="art09act22",
            new_name="art09act23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09fer22",
            new_name="art09fer23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09hab22",
            new_name="art09hab23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09inc22",
            new_name="art09inc23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09mix22",
            new_name="art09mix23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="art09rou22",
            new_name="art09rou23",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="naf09art22",
            new_name="naf09art23",
        ),
    ]
