# Generated by Django 4.2.11 on 2024-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0162_rename_art09act22_cerema_art09act23_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cerema",
            old_name="artcom0922",
            new_name="artcom0923",
        ),
    ]
