# Generated by Django 4.2.11 on 2024-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0163_rename_artcom0922_cerema_artcom0923"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cerema",
            name="libaav2020",
        ),
    ]
