# Generated by Django 4.2.11 on 2024-05-02 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0165_rename_emp13_cerema_emp14_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cerema",
            old_name="artpop1319",
            new_name="artpop1420",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="menhab1319",
            new_name="menhab1420",
        ),
        migrations.RenameField(
            model_name="cerema",
            old_name="mepart1319",
            new_name="mepart1420",
        ),
    ]
