# Generated by Django 4.2.13 on 2024-06-07 18:42

from django.db import migrations


def clean_scots(apps, schema_editor):
    Scot = apps.get_model("public_data", "Scot")
    Project = apps.get_model("project", "Project")
    Commune = apps.get_model("public_data", "Commune")

    Commune.objects.all().update(scot=None)
    Scot.objects.all().delete()
    Project.objects.filter(land_type="SCOT").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0170_auto_20240607_1350"),
    ]

    operations = [
        migrations.RunPython(clean_scots),
    ]
