# Generated by Django 4.2.13 on 2024-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0170_auto_20240607_1350"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneArtificielle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("millesime", models.CharField(max_length=200, verbose_name="Millesime")),
                (
                    "srid_source",
                    models.IntegerField(
                        choices=[
                            (2154, "France Métropolitaine et Corse"),
                            (32620, "Guadeloupe et Martinique"),
                            (2972, "Guyane Française"),
                            (2975, "La réunion"),
                            (4326, "Monde (GPS)"),
                            (3857, "Monde (Google Maps, OpenStreetMap etc.)"),
                        ],
                        default=2154,
                        verbose_name="SRID",
                    ),
                ),
                ("surface", models.DecimalField(decimal_places=4, max_digits=15, verbose_name="surface")),
                ("departement", models.CharField(max_length=15, verbose_name="Département")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["millesime"], name="public_data_millesi_5fb7c5_idx"),
                    models.Index(fields=["departement"], name="public_data_departe_00439b_idx"),
                ],
            },
        ),
    ]
