# Generated by Django 4.2.13 on 2024-06-21 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0170_auto_20240607_1350"),
    ]

    operations = []
