# Generated by Django 4.2.13 on 2024-06-11 09:04

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0171_zoneartificielle"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="zoneartificielle",
            name="public_data_millesi_5fb7c5_idx",
        ),
        migrations.RemoveField(
            model_name="zoneartificielle",
            name="millesime",
        ),
        migrations.AddField(
            model_name="zoneartificielle",
            name="mpoly",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default="MULTIPOLYGON EMPTY", srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zoneartificielle",
            name="year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Année",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="zoneartificielle",
            index=models.Index(fields=["year"], name="public_data_year_2f3a22_idx"),
        ),
    ]
