# Generated by Django 4.2.13 on 2024-06-15 16:35

from django.db import migrations
from logging import getLogger

logger = getLogger(__name__)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("public_data", "0173_alter_zoneartificielle_departement"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
