# Generated by Django 4.2.13 on 2024-06-15 16:35

from django.db import migrations
from logging import getLogger

logger = getLogger(__name__)


def fix_commune_mpoly(apps, schema_editor):
    Commune = apps.get_model("public_data", "Commune")
    Cerema = apps.get_model("public_data", "Cerema")

    to_update = []

    progress_in_percent = 0
    communes = Commune.objects.all()
    commune_count = communes.count()

    for commune in communes:
        cerema = Cerema.objects.get(city_insee=commune.insee)

        if commune.mpoly == cerema.mpoly:
            # no need to update
            break
        commune.mpoly = cerema.mpoly
        commune.srid_source = cerema.srid_source
        to_update.append(commune)
        progress_in_percent = round((len(to_update) / commune_count) * 100, 2)
        logger.info(f"Progress: {progress_in_percent}%")

    Commune.objects.bulk_update(
        to_update,
        ["mpoly", "srid_source"],
        batch_size=1000,
    )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("public_data", "0173_alter_zoneartificielle_departement"),
    ]

    operations = [
        migrations.RunPython(fix_commune_mpoly),
    ]
