# Generated by Django 4.2.13 on 2024-06-17 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0174_auto_20240615_1835"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="artificialarea",
            unique_together={("year", "city")},
        ),
    ]
