# Generated by Django 4.2.13 on 2024-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0175_alter_artificialarea_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="artificialarea",
            name="new_method",
            field=models.BooleanField(default=False, verbose_name="Issu de la nouvelle méthode de calcul"),
        ),
    ]
