# Generated by Django 4.2.13 on 2024-06-22 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0177_alter_artificialarea_new_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artificialarea",
            name="new_method",
        ),
    ]
