# Generated by Django 4.2.13 on 2024-06-24 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0172_auto_20240621_0655"),
        ("public_data", "0178_remove_artificialarea_new_method"),
    ]

    operations = []
