# Generated by Django 4.2.13 on 2024-06-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0179_merge_20240624_0952"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZoneArtificielle",
        ),
        migrations.AlterModelOptions(
            name="artificialarea",
            options={
                "verbose_name": "OCSGE - Artificialisation (par commune)",
                "verbose_name_plural": "OCSGE - Artificialisation (par commune)",
            },
        ),
        migrations.AlterModelOptions(
            name="cerema",
            options={"verbose_name": "Données du cerema", "verbose_name_plural": "Données du cerema"},
        ),
        migrations.AlterModelOptions(
            name="communediff",
            options={
                "verbose_name": "OCSGE - Différence (par commune)",
                "verbose_name_plural": "OCSGE - Différence (par commune)",
            },
        ),
        migrations.AlterModelOptions(
            name="communepop",
            options={"verbose_name": "Population (par commune)", "verbose_name_plural": "Populations (par commune)"},
        ),
        migrations.AlterModelOptions(
            name="communesol",
            options={
                "verbose_name": "OCSGE - Couverture x usage des sols (par commune)",
                "verbose_name_plural": "OCSGE - Couverture x usage des sols (par commune)",
            },
        ),
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "ordering": ["official_land_id", "millesimes", "name"],
                "verbose_name": "Source de données",
                "verbose_name_plural": "Sources de données",
            },
        ),
        migrations.AlterModelOptions(
            name="departement",
            options={"verbose_name": "Département"},
        ),
        migrations.AlterModelOptions(
            name="epci",
            options={"verbose_name": "EPCI", "verbose_name_plural": "EPCIs"},
        ),
        migrations.AlterModelOptions(
            name="ocsge",
            options={"verbose_name": "OCSGE", "verbose_name_plural": "OCSGE"},
        ),
        migrations.AlterModelOptions(
            name="ocsgediff",
            options={"verbose_name": "OCSGE - Différence", "verbose_name_plural": "OCSGE - Différence"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Région"},
        ),
        migrations.AlterModelOptions(
            name="sudocuh",
            options={
                "verbose_name": "Données Sudocuh (par commune)",
                "verbose_name_plural": "Données Sudocuh (par commune)",
            },
        ),
        migrations.AlterModelOptions(
            name="sudocuhepci",
            options={
                "verbose_name": "Données Sudocuh (par EPCI)",
                "verbose_name_plural": "Données Sudocuh (par EPCI)",
            },
        ),
        migrations.AlterModelOptions(
            name="zoneconstruite",
            options={"verbose_name": "OCSGE - Zone construite", "verbose_name_plural": "OCSGE - Zone construite"},
        ),
        migrations.AddField(
            model_name="artificialarea",
            name="new_method",
            field=models.BooleanField(default=True, verbose_name="Issu de la nouvelle méthode de calcul"),
        ),
    ]
