# Generated by Django 4.2.13 on 2024-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0180_delete_zoneartificielle_alter_artificialarea_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epci",
            options={"verbose_name": "EPCI"},
        ),
        migrations.RemoveField(
            model_name="artificialarea",
            name="new_method",
        ),
    ]
