# Generated by Django 4.2.13 on 2024-06-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0181_alter_epci_options_remove_artificialarea_new_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocsge",
            name="is_impermeable",
            field=models.BooleanField(blank=True, null=True, verbose_name="Est imperméable"),
        ),
        migrations.AddField(
            model_name="ocsgediff",
            name="is_new_impermeable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocsgediff",
            name="is_new_not_impermeable",
            field=models.BooleanField(blank=True, null=True, verbose_name="Aussi appelé désimperméabilisation"),
        ),
        migrations.AlterField(
            model_name="ocsgediff",
            name="is_new_natural",
            field=models.BooleanField(verbose_name="Aussi appelé désartificialisation"),
        ),
    ]
