# Generated by Django 4.2.13 on 2024-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0184_alter_ocsge_is_impermeable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couvertureusagematrix",
            name="is_consumed",
        ),
        migrations.AddField(
            model_name="couvertureusagematrix",
            name="is_impermeable",
            field=models.BooleanField(blank=True, null=True, verbose_name="Imperméable"),
        ),
    ]
