# Generated by Django 4.2.13 on 2024-06-25 07:06

from django.db import migrations


def add_is_impermeable_to_couverture_usage_matrix(apps, schema_editor):
    CouvertureUsageMatrix = apps.get_model("public_data", "CouvertureUsageMatrix")

    CouvertureUsageMatrix.objects.filter(
        is_impermeable=None,
        couverture__code_prefix__in=[
            "CS1.1.1.1",
            "CS1.1.1.2",
        ],
    ).update(is_impermeable=True)

    CouvertureUsageMatrix.objects.filter(
        is_impermeable=None,
    ).update(is_impermeable=False)


def reverse_add_is_impermeable_to_couverture_usage_matrix(apps, schema_editor):
    CouvertureUsageMatrix = apps.get_model("public_data", "CouvertureUsageMatrix")

    CouvertureUsageMatrix.objects.update(is_impermeable=None)


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0185_remove_couvertureusagematrix_is_consumed_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=add_is_impermeable_to_couverture_usage_matrix,
            reverse_code=reverse_add_is_impermeable_to_couverture_usage_matrix,
        ),
    ]
