# Generated by Django 4.2.13 on 2024-07-03 15:04

from django.db import migrations, connection


def fix_cerema_names(apps, schema_editor):
    Cerema = apps.get_model("public_data", "Cerema")
    broken_names_are_present = Cerema.objects.filter(epci_name="CA Grand Auch C?ur de Gascogne").exists()

    if not broken_names_are_present:
        return

    with connection.cursor() as cursor:
        sql = """
        WITH cerema_join AS (
            SELECT
                cerema.id as cerema_id,
                departement.name as departement_name,
                region.name as region_name,
                commune.name as commune_name,
                epci.name as epci_name
            FROM
                public_data_cerema AS cerema
            INNER JOIN
                public_data_epci AS epci
            ON
                epci.source_id =
                cerema.epci_id
            INNER JOIN
                public_data_departement AS departement
            ON
                departement.source_id =
                cerema.dept_id
            INNER JOIN
                public_data_region AS region
            ON
                region.source_id =
                cerema.region_id
            INNER JOIN
                public_data_commune AS commune
            ON
                commune.insee =
                cerema.city_insee
            WHERE
                cerema.epci_id != 'N/A - hor'
                /* Filtering out Cerema object without EPCI */
        )
        UPDATE public_data_cerema AS cerema
        SET
            epci_name = cerema_join.epci_name,
            dept_name = cerema_join.departement_name,
            region_name = cerema_join.region_name,
            city_name = cerema_join.commune_name
        FROM
            cerema_join
        WHERE
            cerema_join.cerema_id = cerema.id
        """
        cursor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0186_auto_20240625_0906"),
    ]

    operations = [migrations.RunPython(fix_cerema_names)]
