# Generated by Django 4.2.13 on 2024-07-03 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0186_auto_20240625_0906"),
    ]

    operations = []
