# Generated by Django 4.2.13 on 2024-06-26 09:41

import config.storages
from django.db import migrations, models

from public_data.models.LandStaticFigure import upload_in_land_folder


class Migration(migrations.Migration):
    run_before = [("project", "0084_remove_historicalproject_cover_image_and_more")]

    dependencies = [
        ("public_data", "0186_auto_20240625_0906"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandStaticFigure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_type", models.CharField(max_length=200)),
                ("land_id", models.CharField(max_length=200)),
                ("params", models.JSONField()),
                (
                    "figure",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=config.storages.PublicMediaStorage(),
                        upload_to=upload_in_land_folder,
                    ),
                ),
            ],
        ),
    ]
