# Generated by Django 4.2.13 on 2024-08-17 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0187_auto_20240703_1704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="id",
        ),
        migrations.AddField(
            model_name="zoneurba",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="UUID"),
        ),
    ]
