# Generated by Django 4.2.13 on 2024-06-26 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    run_before = [("project", "0084_remove_historicalproject_cover_image_and_more")]
    dependencies = [
        ("public_data", "0187_landstaticfigure"),
    ]

    operations = [
        migrations.AddField(
            model_name="landstaticfigure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landstaticfigure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
