# Generated by Django 4.2.13 on 2024-06-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    run_before = [("project", "0084_remove_historicalproject_cover_image_and_more")]
    dependencies = [
        ("public_data", "0188_landstaticfigure_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landstaticfigure",
            options={"verbose_name": "Figure statique", "verbose_name_plural": "Figures statiques"},
        ),
        migrations.AddField(
            model_name="landstaticfigure",
            name="figure_name",
            field=models.CharField(default="cover", max_length=200),
            preserve_default=False,
        ),
    ]
