# Generated by Django 4.2.13 on 2024-08-17 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0188_remove_zoneurba_id_zoneurba_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="gid",
        ),
    ]
