# Generated by Django 4.2.13 on 2024-09-11 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0188_alter_artifareazoneurba_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commune",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="departement",
            options={"managed": False, "verbose_name": "Département"},
        ),
        migrations.AlterModelOptions(
            name="epci",
            options={"managed": False, "verbose_name": "EPCI"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"managed": False, "verbose_name": "Région"},
        ),
        migrations.AlterModelOptions(
            name="scot",
            options={"managed": False},
        ),
    ]
