# Generated by Django 4.2.13 on 2024-08-17 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0189_remove_zoneurba_gid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="origin_insee",
        ),
        migrations.RemoveField(
            model_name="zoneurba",
            name="origin_typezone",
        ),
    ]
