# Generated by Django 4.2.13 on 2024-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    run_before = [("project", "0084_remove_historicalproject_cover_image_and_more")]
    dependencies = [
        ("public_data", "0189_alter_landstaticfigure_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landstaticfigure",
            name="params_hash",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
