# Generated by Django 4.2.13 on 2024-10-02 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0189_alter_commune_options_alter_departement_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataSource",
        ),
        migrations.DeleteModel(
            name="RefPlan",
        ),
    ]
