# Generated by Django 4.2.13 on 2024-11-26 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0190_delete_datasource_delete_refplan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommunePop",
        ),
    ]
