# Generated by Django 4.2.13 on 2024-08-17 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0190_remove_zoneurba_origin_insee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="destdomi",
        ),
    ]
