# Generated by Django 4.2.13 on 2024-08-17 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0191_remove_zoneurba_destdomi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="idzone",
        ),
        migrations.RemoveField(
            model_name="zoneurba",
            name="lib_idzone",
        ),
        migrations.RemoveField(
            model_name="zoneurba",
            name="nomfic",
        ),
        migrations.RemoveField(
            model_name="zoneurba",
            name="urlfic",
        ),
    ]
