# Generated by Django 4.2.13 on 2024-08-17 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0192_remove_zoneurba_idzone_remove_zoneurba_lib_idzone_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="zoneurba",
            name="public_data_insee_3f872f_idx",
        ),
        migrations.RemoveField(
            model_name="zoneurba",
            name="insee",
        ),
    ]
