# Generated by Django 4.2.13 on 2025-01-13 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0193_landconso_landconsocomparison_landconsostats_landpop_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couvertureusagematrix",
            options={"managed": False},
        ),
    ]
