# Generated by Django 4.2.17 on 2025-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0193_landconso_landconsocomparison_landconsostats_landpop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorisationLogement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField()),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("logements_autorises", models.IntegerField()),
                ("logements_commences", models.IntegerField()),
                ("surface_de_plancher_autorisee", models.FloatField()),
                ("surface_de_plancher_commencee", models.FloatField()),
                ("percent_autorises_on_parc_general", models.FloatField()),
                ("percent_autorises_on_vacants_parc_general", models.FloatField()),
            ],
            options={
                "db_table": "public_data_autorisationlogement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LogementVacant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField()),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("logements_parc_prive", models.IntegerField()),
                ("logements_vacants_parc_prive", models.IntegerField()),
                ("logements_parc_social", models.IntegerField()),
                ("logements_vacants_parc_social", models.IntegerField()),
                ("logements_vacants_parc_general", models.IntegerField()),
                ("logements_vacants_parc_general_percent", models.FloatField()),
                ("logements_vacants_parc_prive_percent", models.FloatField()),
                ("logements_vacants_parc_social_percent", models.FloatField()),
                ("logements_vacants_parc_prive_on_parc_general_percent", models.FloatField()),
                ("logements_vacants_parc_social_on_parc_general_percent", models.FloatField()),
            ],
            options={
                "db_table": "public_data_logementvacant",
                "managed": False,
            },
        ),
    ]
