# Generated by Django 4.2.13 on 2025-02-10 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0194_autorisationlogement_logementvacant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifZonage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField()),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ]
                    ),
                ),
                ("departements", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ("year", models.IntegerField()),
                ("surface", models.FloatField()),
                ("artificial_surface", models.FloatField()),
                ("zonage_type", models.CharField()),
                ("zonage_count", models.IntegerField()),
                ("artificial_percent", models.FloatField()),
            ],
            options={
                "db_table": "public_data_artifzonage",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ArtifAreaZoneUrba",
        ),
    ]
