# Generated by Django 4.2.13 on 2024-08-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0194_artifareazoneurba_departement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneurba",
            name="uuid",
        ),
        migrations.AddField(
            model_name="zoneurba",
            name="id",
            field=models.TextField(default="", primary_key=True, serialize=False, verbose_name="id"),
            preserve_default=False,
        ),
    ]
