# Generated by Django 4.2.13 on 2024-08-18 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0195_remove_zoneurba_uuid_zoneurba_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artifareazoneurba",
            name="unique_zone_year",
        ),
        migrations.RemoveIndex(
            model_name="artifareazoneurba",
            name="public_data_zone_ur_cb8473_idx",
        ),
        migrations.RemoveIndex(
            model_name="artifareazoneurba",
            name="public_data_zone_ur_57615b_idx",
        ),
        migrations.RemoveField(
            model_name="artifareazoneurba",
            name="zone_urba",
        ),
    ]
