# Generated by Django 4.2.19 on 2025-02-26 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0195_artifzonage_delete_artifareazoneurba"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couvertureusagematrix",
            options={"managed": False},
        ),
    ]
