# Generated by Django 4.2.13 on 2024-08-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0196_remove_artifareazoneurba_unique_zone_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifareazoneurba",
            name="zone_urba",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="public_data.zoneurba"
            ),
            preserve_default=False,
        ),
    ]
