# Generated by Django 4.2.19 on 2025-03-27 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0196_delete_zoneconstruite_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArtificialArea",
        ),
        migrations.DeleteModel(
            name="LandPopComparison",
        ),
        migrations.DeleteModel(
            name="Ocsge",
        ),
        migrations.DeleteModel(
            name="OcsgeDiff",
        ),
        migrations.DeleteModel(
            name="ZoneConstruite",
        ),
    ]
