# Generated by Django 4.2.13 on 2024-08-19 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0197_artifareazoneurba_zone_urba"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="map_color",
        ),
    ]
