# Generated by Django 4.2.20 on 2025-06-23 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0198_artifzonageindex_landartifstock_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZoneUrba",
        ),
    ]
