# Generated by Django 4.2.20 on 2025-11-24 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0200_imperzonage_imperzonageindex_landimperflux_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandArtifFlux",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                ("year_old", models.IntegerField()),
                ("year_new", models.IntegerField()),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
                ("departement", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "public_data_landartifflux",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandArtifFluxCouvertureComposition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                ("departement", models.CharField(max_length=10)),
                ("year_old", models.IntegerField()),
                ("year_new", models.IntegerField()),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("couverture", models.CharField(max_length=100)),
                ("color", models.CharField()),
                ("label_short", models.CharField()),
                ("label", models.CharField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
            ],
            options={
                "db_table": "public_data_landartiffluxcouverturecomposition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandArtifFluxCouvertureCompositionIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                (
                    "departements",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
                ),
                ("years_old", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("years_new", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("couverture", models.CharField(max_length=100)),
                ("color", models.CharField()),
                ("label_short", models.CharField()),
                ("label", models.CharField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
            ],
            options={
                "db_table": "public_data_landartiffluxcouverturecompositionindex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandArtifFluxIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                ("years_old", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("years_new", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
                (
                    "departements",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
                ),
            ],
            options={
                "db_table": "public_data_landartiffluxindex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandArtifFluxUsageComposition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                ("departement", models.CharField(max_length=10)),
                ("year_old", models.IntegerField()),
                ("year_new", models.IntegerField()),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("usage", models.CharField(max_length=100)),
                ("color", models.CharField()),
                ("label_short", models.CharField()),
                ("label", models.CharField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
            ],
            options={
                "db_table": "public_data_landartiffluxusagecomposition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandArtifFluxUsageCompositionIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=50)),
                ("land_type", models.CharField(max_length=50)),
                (
                    "departements",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
                ),
                ("years_old", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("years_new", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ("millesime_old_index", models.IntegerField()),
                ("millesime_new_index", models.IntegerField()),
                ("usage", models.CharField(max_length=100)),
                ("color", models.CharField()),
                ("label_short", models.CharField()),
                ("label", models.CharField()),
                ("flux_artif", models.FloatField(help_text="Surface artificialisée en ha")),
                ("flux_desartif", models.FloatField(help_text="Surface désartificialisée en ha")),
                ("flux_artif_net", models.FloatField(help_text="Flux net d'artificialisation en ha")),
            ],
            options={
                "db_table": "public_data_landartiffluxusagecompositionindex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandPopulationDensity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField()),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("population", models.IntegerField()),
                ("surface", models.FloatField()),
                ("density_ha", models.FloatField()),
                ("density_km2", models.FloatField()),
            ],
            options={
                "db_table": "public_data_landpopulationdensity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NearestTerritories",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField()),
                ("land_name", models.CharField(help_text="Nom du territoire source")),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ]
                    ),
                ),
                ("nearest_land_id", models.CharField()),
                ("nearest_land_name", models.CharField(help_text="Nom du territoire le plus proche")),
                (
                    "distance_km",
                    models.FloatField(help_text="Distance en kilomètres entre les centroïdes des territoires"),
                ),
                (
                    "distance_rank",
                    models.IntegerField(help_text="Rang de proximité (1 = le plus proche, 8 = le 8ème plus proche)"),
                ),
            ],
            options={
                "db_table": "public_data_nearestterritories",
                "ordering": ["land_id", "land_type", "distance_rank"],
                "managed": False,
            },
        ),
    ]
