# Generated by Django 4.2.23 on 2025-12-16 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0201_landartifflux_landartiffluxcouverturecomposition_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimilarTerritories",
        ),
    ]
