# Generated by Django 5.2.9 on 2026-01-20 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0202_delete_similarterritories"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmodel",
            name="key",
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name="TerritorialisationObjectif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "objectif_de_reduction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Objectif en pourcentage (max 100)",
                        max_digits=5,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Objectif de réduction",
                    ),
                ),
                (
                    "nom_document",
                    models.CharField(
                        default="SRADDET",
                        help_text="Nom du document dans lequel doit s'inscrire l'objectif",
                        max_length=255,
                        verbose_name="Nom du document",
                    ),
                ),
                (
                    "is_in_document",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si l'objectif est inscrit dans le document d'urbanisme",
                        verbose_name="Inscrit dans le document",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le document source",
                        max_length=500,
                        null=True,
                        verbose_name="URL du document",
                    ),
                ),
                (
                    "document_comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Commentaire ou précision sur l'objectif",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="Territoire qui reçoit l'objectif",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs",
                        to="public_data.landmodel",
                        to_field="key",
                        verbose_name="Territoire",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Territoire qui donne l'objectif",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs_as_parent",
                        to="public_data.landmodel",
                        to_field="key",
                        verbose_name="Parent",
                    ),
                ),
            ],
        ),
    ]
