# Generated by Django 4.2.23 on 2025-12-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0202_delete_similarterritories"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmodel",
            name="key",
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name="TerritorialisationObjectif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "objectif_de_reduction",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Objectif de réduction"),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs",
                        to="public_data.landmodel",
                        to_field="key",
                        verbose_name="Territoire",
                        db_constraint=False,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs_as_parent",
                        to="public_data.landmodel",
                        to_field="key",
                        verbose_name="Parent",
                        db_constraint=False,
                    ),
                ),
            ],
        ),
    ]
