# Generated by Django 4.2.23 on 2025-12-29 09:47

from django.db import migrations, models
import django.db.models.deletion


def create_land_table_if_not_exists(apps, schema_editor):
    """Create the LandModel table if it doesn't exist (for tests)."""
    LandModel = apps.get_model("public_data", "LandModel")

    # Check if table exists
    table_name = LandModel._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = %s)", [table_name])
        exists = cursor.fetchone()[0]

    if not exists:
        schema_editor.create_model(LandModel)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0202_delete_similarterritories"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="landmodel",
                    name="key",
                    field=models.TextField(unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(create_land_table_if_not_exists, noop),
        migrations.CreateModel(
            name="TerritorialisationObjectif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "objectif_de_reduction",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Objectif de réduction"),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs",
                        to="public_data.landmodel",
                        verbose_name="Territoire",
                        db_constraint=False,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="territorialisation_objectifs_as_parent",
                        to="public_data.landmodel",
                        verbose_name="Parent",
                        db_constraint=False,
                    ),
                ),
            ],
        ),
    ]
