# Generated by Django 5.2.11 on 2026-02-20 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0203_territorialisationobjectif"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sudocuh",
        ),
        migrations.DeleteModel(
            name="SudocuhEpci",
        ),
    ]
