# Generated by Django 4.2.23 on 2025-12-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0203_territorialisationobjectif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="land",
            field=models.ForeignKey(
                help_text="Territoire qui reçoit l'objectif",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="territorialisation_objectifs",
                to="public_data.landmodel",
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="objectif_de_reduction",
            field=models.DecimalField(
                decimal_places=2, help_text="Objectif en hectares", max_digits=5, verbose_name="Objectif de réduction"
            ),
        ),
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Territoire qui donne l'objectif",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="territorialisation_objectifs_as_parent",
                to="public_data.landmodel",
                verbose_name="Parent",
            ),
        ),
    ]
