# Generated by Django 4.2.23 on 2025-12-29 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0204_alter_territorialisationobjectif_land_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="objectif_de_reduction",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Objectif en pourcentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Objectif de réduction",
            ),
        ),
    ]
