# Generated by Django 5.2.11 on 2026-02-20 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0204_delete_sudocuh_delete_sudocuhepci"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departement",
            name="region",
        ),
        migrations.RemoveField(
            model_name="epci",
            name="departements",
        ),
        migrations.RemoveField(
            model_name="scot",
            name="departements",
        ),
        migrations.RemoveField(
            model_name="scot",
            name="regions",
        ),
        migrations.DeleteModel(
            name="Commune",
        ),
        migrations.DeleteModel(
            name="Epci",
        ),
        migrations.DeleteModel(
            name="Departement",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.DeleteModel(
            name="Scot",
        ),
    ]
