# Generated by Django 4.2.23 on 2025-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0205_alter_territorialisationobjectif_objectif_de_reduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="territorialisationobjectif",
            name="nom_document",
            field=models.CharField(
                default="SRADDET",
                help_text="Nom du document source de l'objectif",
                max_length=255,
                verbose_name="Nom du document",
            ),
        ),
    ]
