# Generated by Django 4.2.23 on 2025-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0206_territorialisationobjectif_nom_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="territorialisationobjectif",
            name="is_in_document",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l'objectif est inscrit dans le document d'urbanisme",
                verbose_name="Inscrit dans le document",
            ),
        ),
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="nom_document",
            field=models.CharField(
                default="SRADDET",
                help_text="Nom du document dans lequel doit s'inscrire l'objectif",
                max_length=255,
                verbose_name="Nom du document",
            ),
        ),
    ]
