# Generated by Django 4.2.23 on 2025-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0207_add_is_in_document_to_territorialisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="territorialisationobjectif",
            name="document_comment",
            field=models.TextField(
                blank=True, help_text="Commentaire ou précision sur l'objectif", null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="territorialisationobjectif",
            name="document_url",
            field=models.URLField(
                blank=True,
                help_text="Lien vers le document source",
                max_length=500,
                null=True,
                verbose_name="URL du document",
            ),
        ),
    ]
