# Generated by Django 4.2.23 on 2025-12-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0208_add_document_fields_to_territorialisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="document_comment",
            field=models.TextField(
                blank=True, default="", help_text="Commentaire ou précision sur l'objectif", verbose_name="Commentaire"
            ),
        ),
    ]
