# Generated by Django 4.2.23 on 2025-12-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0210_load_territorialisation_objectif_fixture"),
    ]

    operations = [
        # Add key field to LandModel state (already exists in DB since managed=False)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="landmodel",
                    name="key",
                    field=models.TextField(unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="land",
            field=models.ForeignKey(
                help_text="Territoire qui reçoit l'objectif",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="territorialisation_objectifs",
                to="public_data.landmodel",
                to_field="key",
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Territoire qui donne l'objectif",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="territorialisation_objectifs_as_parent",
                to="public_data.landmodel",
                to_field="key",
                verbose_name="Parent",
            ),
        ),
    ]
