# Generated by Django 5.2.9 on 2026-01-20 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0211_alter_territorialisationobjectif_land_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territorialisationobjectif",
            name="objectif_de_reduction",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Objectif en pourcentage (max 100)",
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Objectif de réduction",
            ),
        ),
    ]
