# Generated by Django 3.2.5 on 2021-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=400, verbose_name="Titre")),
                (
                    "menu_entry",
                    models.CharField(max_length=100, verbose_name="Titre dans le menu"),
                ),
                ("md_content", models.TextField(verbose_name="Contenu en markdown")),
            ],
        ),
    ]
