# Generated by Django 3.2.5 on 2021-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frequentlyaskedquestion",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Rendre public"),
        ),
    ]
