# Generated by Django 3.2.5 on 2022-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_frequentlyaskedquestion_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frequentlyaskedquestion",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="frequentlyaskedquestion",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order d'affichage"),
        ),
    ]
