# Generated by Django 3.2.5 on 2022-01-19 14:12

from django.db import migrations
from django.utils.text import slugify


TITLE = "Les données utilisées"
MD_CONTENT = """
Cette section est en construction, mais vous pouvez déjà y trouver des informations
intéressantes.

## Provenance des données

Nous utilisons 2 sources de données externes :

* L'OCuppation des Sols à Grande Echelle (OCSGE)
* Les fichiers fonciers fournis par le CEREMA

## L'occupation des sols à grande échelle (OCSGE)

La documentation officielle est disponible au format PDF ici :
[https://drive.google.com/drive/u/0/folders/1cDmEpUmIdtop6cOBCe9w3J-dPqhGd8V9]
(https://drive.google.com/drive/u/0/folders/1cDmEpUmIdtop6cOBCe9w3J-dPqhGd8V9)

**TODO** fournir la description de la table stockant les données dans SPARTE ainsi que
le endpoint public

## Les fichiers fonciers

La documentation officielle est disponible sur le site du CEREMA :
[http://doc-datafoncier.cerema.fr/ff/docff/](http://doc-datafoncier.cerema.fr/ff/docff/)

**TODO** fournir la description de la table, le endpoint et les champs calculés.
"""


def forwards(apps, schema_editor):
    FAQ = apps.get_model("home", "FrequentlyAskedQuestion")
    entry = FAQ(
        slug=slugify(TITLE),
        title=TITLE,
        menu_entry=TITLE,
        md_content=MD_CONTENT,
        is_published=True,
        order=3,
    )
    entry.save()


def reverse(apps, schema_editor):
    FAQ = apps.get_model("home", "FrequentlyAskedQuestion")
    try:
        FAQ.objects.get(slug=slugify(TITLE)).delete()
    except FAQ.DoesNotExists:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20220105_2014"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
