# Generated by Django 3.2.14 on 2022-07-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20220119_1412"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrequentlyAskedQuestion",
        ),
    ]
