# Generated by Django 3.2.15 on 2022-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0005_delete_frequentlyaskedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Votre courriel"),
                ),
                ("content", models.TextField(verbose_name="Votre message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting celery to process the task"),
                            ("SUCCESS", "Task done with success"),
                            ("FAILED", "Task failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
