# Generated by Django 3.2.15 on 2022-09-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_newsletter_confirm_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "verbose_name": "Formulaire de contact",
                "verbose_name_plural": "Formulaires de contact",
            },
        ),
    ]
