# Generated by Django 4.2.6 on 2023-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_newsletter_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AliveTimeStamp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("queue_name", models.CharField(max_length=20)),
            ],
        ),
    ]
