# Generated by Django 4.2.7 on 2023-11-02 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alivetimestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alivetimestamp",
            options={"ordering": ["-timestamp"]},
        ),
    ]
