# Generated by Django 4.2.13 on 2024-11-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_alivetimestamp_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET default_toast_compression = 'lz4'",
            reverse_sql="SET default_toast_compression = 'pglz'",
        ),
    ]
