# Generated by Django 4.2.20 on 2025-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_auto_20241105_1333"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatisfactionFormEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("test", models.BooleanField(default=False, verbose_name="Test")),
            ],
        ),
    ]
