# Generated by Django 4.2.20 on 2025-06-19 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_satisfactionformentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="satisfactionformentry",
            name="test",
        ),
        migrations.AddField(
            model_name="satisfactionformentry",
            name="nps",
            field=models.IntegerField(
                default=0,
                help_text="Note de satisfaction de 0 à 10, où 0 est très insatisfait et 10 très satisfait.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="NPS",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="satisfactionformentry",
            name="suggested_change",
            field=models.TextField(
                blank=True,
                help_text="Suggérez un changement pour améliorer le service.",
                null=True,
                verbose_name="Changement suggéré",
            ),
        ),
    ]
