# Generated by Django 4.2.20 on 2025-07-01 08:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_satisfactionformentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="satisfactionformentry",
            name="recorded_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date à laquelle le formulaire a été enregistré.",
                verbose_name="Date d'enregistrement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="satisfactionformentry",
            name="nps",
            field=models.IntegerField(
                help_text="Note de satisfaction de 0 à 10, où 0 est très insatisfait et 10 très satisfait.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Score NPS",
            ),
        ),
    ]
