# Generated by Django 4.2.20 on 2025-09-02 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_satisfactionformentry_recorded_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satisfactionformentry",
            name="nps",
            field=models.IntegerField(
                help_text="A quel point êtes-vous succeptible de recommander ce service ? 0 étant peu probable et 10 très probable.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Score NPS",
            ),
        ),
        migrations.AlterField(
            model_name="satisfactionformentry",
            name="suggested_change",
            field=models.TextField(
                blank=True,
                help_text="Suggérez un changement ou une nouvelle fonctionnalité pour nous permettre d'améliorer le service.",
                null=True,
                verbose_name="Changement suggéré",
            ),
        ),
    ]
