# Generated by Django 5.2.9 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_remove_alivetimestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente de traitement"),
                    ("SUCCESS", "Traité avec succès"),
                    ("FAILED", "Échec du traitement"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
