# Generated by Django 5.2.11 on 2026-03-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_pagefeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagefeedback",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
