# Generated by Django 3.2.5 on 2021-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="project name")),
                (
                    "shape_files",
                    models.FileField(upload_to=None, verbose_name="shape files"),
                ),
                ("analyse_start_date", models.DateField()),
                ("analyse_end_date", models.DateField()),
            ],
        ),
    ]
