# Generated by Django 3.2.5 on 2021-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_auto_20210824_0125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Import pending to be processed"),
                    ("SUCCESS", "Import successfuly processed"),
                    ("FAILED", "Import failed, see import message"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="import status",
            ),
        ),
    ]
