# Generated by Django 3.2.5 on 2021-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0007_auto_20210816_1724"),
        ("project", "0004_auto_20210824_0125"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cities",
            field=models.ManyToManyField(
                to="public_data.CommunesSybarval", verbose_name="cities"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_manually_linked",
            field=models.BooleanField(
                default=False, verbose_name="Is manually linked to cities"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Import pending to be processed"),
                    ("SUCCESS", "Import successfuly processed"),
                    ("FAILED", "Import failed, see import message"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="import status",
            ),
        ),
    ]
