# Generated by Django 3.2.5 on 2021-08-25 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_auto_20210825_1559"),
    ]

    operations = []
