# Generated by Django 3.2.5 on 2021-08-27 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_project_cities"),
    ]

    operations = []
