# Generated by Django 3.2.5 on 2021-09-13 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("public_data", "0008_artifcommune"),
        ("project", "0008_alter_project_import_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_manually_linked",
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[("2015", "2015"), ("2018", "2018")],
                default="2018",
                max_length=4,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[("2015", "2015"), ("2018", "2018")],
                default="2015",
                max_length=4,
                verbose_name="Date de début",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cities",
            field=models.ManyToManyField(
                blank=True, to="public_data.ArtifCommune", verbose_name="Communes"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="import_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date et heure d'import"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="import_error",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Message d'erreur traitement emprise",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("MISSING", "Emprise à renseigner"),
                    ("PENDING", "Traitement du fichier Shape en cours"),
                    ("SUCCESS", "Emprise renseignée"),
                    ("FAILED", "Création de l'emprise échouée"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Statut import",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="project",
            name="shape_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=project.models.user_directory_path,
                verbose_name="Fichier .shp",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
    ]
