# Generated by Django 3.2.5 on 2021-09-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_auto_20210913_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprise",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
                verbose_name="project",
            ),
        ),
    ]
