# Generated by Django 3.2.5 on 2021-09-23 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_auto_20210920_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planemprise",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emprise_set",
                to="project.plan",
            ),
        ),
    ]
