# Generated by Django 3.2.5 on 2021-12-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_auto_20211102_1103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                ],
                default="2018",
                max_length=4,
                verbose_name="Date de fin de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Date de début de période d'analyse",
            ),
        ),
    ]
