# Generated by Django 3.2.5 on 2022-01-06 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0018_auto_20211231_0446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="cities",
        ),
    ]
