# Generated by Django 3.2.5 on 2022-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0038_commune"),
        ("project", "0019_remove_project_cities"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cities",
            field=models.ManyToManyField(
                blank=True, to="public_data.Commune", verbose_name="Communes"
            ),
        ),
    ]
