# Generated by Django 3.2.5 on 2022-01-06 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_remove_project_cities"),
    ]

    operations = []
