# Generated by Django 3.2.11 on 2022-02-16 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_auto_20220216_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="first_year_ocsge",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="Premier millésime OCSGE",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_year_ocsge",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="Dernier millésime OCSGE",
            ),
        ),
    ]
