# Generated by Django 3.2.11 on 2022-03-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public_data", "0042_alter_cerema_table"),
        ("project", "0028_auto_20220216_2144"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE project_project_cities RENAME TO "
                        "project_projectcommune"
                    ),
                    reverse_sql=(
                        "ALTER TABLE project_projectcommune RENAME TO "
                        "project_project_cities"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProjectCommune",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "commune",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="public_data.commune",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="project.project",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="project",
                    name="cities",
                    field=models.ManyToManyField(
                        to="public_data.Commune",
                        through="project.ProjectCommune",
                        verbose_name="Communes",
                        blank=True,
                    ),
                ),
            ],
        )
    ]
