# Generated by Django 3.2.11 on 2022-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_auto_20220308_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcommune",
            name="group_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du groupe"
            ),
        ),
    ]
