# Generated by Django 3.2.13 on 2022-05-12 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_projectcommune_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="first_year_ocsge",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="Premier millésime OCSGE",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_year_ocsge",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="Dernier millésime OCSGE",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="look_a_like",
            field=models.CharField(
                blank=True,
                help_text="We need a way to find Project related within Cerema's data. this is the purpose of this field which has a very specific rule of construction, it's like a slug: EPCI_[ID], DEPART_[ID] (département), REGION_[ID], COMMUNE_[ID]. field can contain several public key separate by ;",
                max_length=250,
                null=True,
                verbose_name="Territoire pour se comparer",
            ),
        ),
    ]
