# Generated by Django 3.2.13 on 2022-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0031_auto_20220512_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Date de début de période d'analyse",
            ),
        ),
    ]
