# Generated by Django 3.2.13 on 2022-06-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0032_project_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPT", "Département"),
                    ("REGI", "Région"),
                ],
                default="COMM",
                max_length=4,
                verbose_name="Niveau d'analyse",
            ),
        ),
    ]
