# Generated by Django 3.2.13 on 2022-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0033_alter_project_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="land_ids",
            field=models.CharField(
                blank=True,
                help_text="Contient les identifiants qui composent le territoire du diagnostic. Il faut croiser cette donnée avec 'land_type' pour être en mesure de de récupérer dans la base les instances correspondantes.",
                max_length=255,
                null=True,
                verbose_name="Type de territoire",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMUNE", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("REGION", "Région"),
                    ("COMP", "Composite"),
                ],
                default="EPCI",
                help_text="Indique le niveau administratif des territoires sélectionnés par l'utilisateur lors de la création du diagnostic. Cela va de la commune à la région.",
                max_length=7,
                null=True,
                verbose_name="Type de territoire",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="emprise_origin",
            field=models.CharField(
                choices=[
                    ("UNSET", "Origine non renseignée"),
                    ("FROM_SHP", "Construit depuis un fichier shape"),
                    ("FROM_CITIES", "Construit depuis une liste de villes"),
                    ("WITH_EMPRISE", "Emprise déjà fournie"),
                ],
                default="UNSET",
                max_length=20,
                verbose_name="Origine de l'emprise",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="emprise_origin",
            field=models.CharField(
                choices=[
                    ("UNSET", "Origine non renseignée"),
                    ("FROM_SHP", "Construit depuis un fichier shape"),
                    ("FROM_CITIES", "Construit depuis une liste de villes"),
                    ("WITH_EMPRISE", "Emprise déjà fournie"),
                ],
                default="UNSET",
                max_length=20,
                verbose_name="Origine de l'emprise",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMMUNE", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("REGION", "Région"),
                    ("COMP", "Composite"),
                ],
                default="COMMUNE",
                help_text="Utilisé lors de la création des rapports afin de déterminer le niveau d'aggrégation des données à afficher. Si l'utilisateur a sélectionné EPCI, alors les rapports doivent montrer des données EPCI par EPCI.",
                max_length=7,
                verbose_name="Niveau d'analyse",
            ),
        ),
    ]
