# Generated by Django 3.2.14 on 2022-08-01 14:45

import django.db.models.deletion
from django.db import migrations, models

import project.models.request


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0040_request_sent_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="sent_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=project.models.request.upload_in_project_folder,
            ),
        ),
        migrations.CreateModel(
            name="ErrorTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("exception", models.TextField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="project.request",
                    ),
                ),
            ],
        ),
    ]
