# Generated by Django 3.2.15 on 2022-09-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_auto_20220829_1616"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Diagnostic en ligne",
                "verbose_name_plural": "Diagnostics en lignes",
            },
        ),
        migrations.AlterModelOptions(
            name="request",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Demande d'un diagnostic",
                "verbose_name_plural": "Demandes de diagnostics",
            },
        ),
    ]
