# Generated by Django 3.2.15 on 2022-10-20 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0044_auto_20220922_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="target_2031",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Objectif 2031",
            ),
        ),
    ]
