# Generated by Django 3.2.16 on 2022-10-24 10:48

import django.core.validators
from django.db import migrations, models

import config.storages
import project.models.project_base


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0045_project_target_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                ],
                default="2018",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de fin de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                ],
                default="2015",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de début de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.upload_in_project_folder,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Si non coché, le diagnostic n'est accessible que par vous. Si coché tous ceux qui ont l'URL peuvent y accéder. Utile pour partager le diagnostic par e-mail à vos collègues par exemple.",
                verbose_name="Est publiquement accessible",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("REGION", "Région"),
                    ("COMP", "Composite"),
                ],
                default="COMMUNE",
                help_text="Utilisé dans les rapports afin de déterminer le niveau d'aggrégation des données à afficher. Si EPCI est sélectionné, alors les rapports montre des données EPCI par EPCI.",
                max_length=7,
                verbose_name="Niveau d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_2031",
            field=models.IntegerField(
                default=50,
                help_text="A date, l'objectif nationnal est de réduire de 50% la consommation d'espace d'ici à 2031. Cet objectif doit être personnalisé localement par les SRADDET. Vous pouvez changer l'objectif pour tester différents scénarios.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Objectif 2031 (en %)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="territory_name",
            field=models.CharField(
                blank=True,
                help_text="C'est le nom qui est utilisé pour désigner votre territoire, notamment dans le rapport word.",
                max_length=250,
                null=True,
                verbose_name="Territoire",
            ),
        ),
    ]
