# Generated by Django 3.2.16 on 2022-11-28 14:29

from django.db import migrations, models

import config.storages
import project.models.project_base


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0046_auto_20221024_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="theme_map_artif",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.upload_in_project_folder,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="theme_map_conso",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.upload_in_project_folder,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="theme_map_understand_artif",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.upload_in_project_folder,
            ),
        ),
    ]
