# Generated by Django 3.2.16 on 2022-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0047_auto_20221128_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="async_add_neighboors_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_city_and_combined_emprise_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_cover_image_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_find_first_and_last_ocsge_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_generate_theme_map_artif_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_generate_theme_map_conso_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_theme_map_understand_artif_done",
            field=models.BooleanField(default=False),
        ),
    ]
