# Generated by Django 4.2.3 on 2023-08-02 13:38

import config.storages
from django.db import migrations, models
import project.models.project_base


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0055_alter_historicalproject_target_2031_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="async_theme_map_gpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="theme_map_gpu",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="async_theme_map_gpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="theme_map_gpu",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.upload_in_project_folder,
            ),
        ),
    ]
