# Generated by Django 4.2.3 on 2023-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0056_historicalproject_async_theme_map_gpu_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="public_keys",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Clé publiques"),
        ),
        migrations.AddField(
            model_name="project",
            name="public_keys",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Clé publiques"),
        ),
    ]
