# Generated by Django 4.2.5 on 2023-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0058_historicalproject_async_theme_map_fill_gpu_done_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2018",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de fin de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2015",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de début de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2018",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de fin de période d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2015",
                help_text="Utile pour analyser votre territoire sur une période différente.",
                max_length=4,
                verbose_name="Année de début de période d'analyse",
            ),
        ),
    ]
