# Generated by Django 4.2.6 on 2023-11-22 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0059_alter_historicalproject_analyse_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errortracking",
            options={"ordering": ["-created_date"]},
        ),
    ]
