# Generated by Django 4.2.6 on 2023-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0060_alter_errortracking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="async_ocsge_status_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="async_ocsge_status_done",
            field=models.BooleanField(default=False),
        ),
    ]
