# Generated by Django 4.2.6 on 2023-12-04 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0062_historicalproject_ocsge_coverage_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalproject",
            old_name="async_ocsge_status_done",
            new_name="async_ocsge_coverage_status_done",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="async_ocsge_status_done",
            new_name="async_ocsge_coverage_status_done",
        ),
    ]
