# Generated by Django 4.2.6 on 2023-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0063_rename_async_ocsge_status_done_historicalproject_async_ocsge_coverage_status_done_and_more"),
    ]

    operations = []
