# Generated by Django 4.2.7 on 2024-01-09 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0061_emprise_srid_source"),
        ("project", "0064_alter_historicalproject_ocsge_coverage_status_and_more"),
    ]

    operations = []
