# Generated by Django 4.2.7 on 2024-02-06 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0064_alter_historicalproject_ocsge_coverage_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalproject",
            old_name="async_add_neighboors_done",
            new_name="async_add_similar_lands_done",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="async_add_neighboors_done",
            new_name="async_add_similar_lands_done",
        ),
    ]
