# Generated by Django 4.2.7 on 2024-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0065_merge_20240109_0833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprise",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "France Métropolitaine et Corse"),
                    (32620, "Guadeloupe et Martinique"),
                    (2972, "Guyane Française"),
                    (2975, "La réunion"),
                    (4326, "Monde (GPS)"),
                    (3857, "Monde (Google Maps, OpenStreetMap etc.)"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2018",
                max_length=4,
                verbose_name="Année de fin de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Année de début de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2018",
                max_length=4,
                verbose_name="Année de fin de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Année de début de période du diagnostic",
            ),
        ),
    ]
