# Generated by Django 4.2.7 on 2024-02-07 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0066_alter_emprise_srid_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="target_2031",
            field=models.IntegerField(
                default=50,
                help_text="L'objectif fixé au niveau national par la loi Climat et résilience est de réduire de 50% la consommation d'espaces sur 2021-2031 par rapport à la décennie précédente.<br /><br />Cet objectif doit être territorialisé et peut être modulé via les documents de planification régionale ainsi que les documents d'urbanisme (SCOT, PLU(i), cartes communales).<br /><br /> Aussi, l'objectif de réduction fixé à défaut à -50% est indicatif et ne correspond pas nécessairement à l'objectif qui sera fixé pour le territoire sélectionné.",  # noqa: E501
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Objectif de réduction à 2031 (en %)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_2031",
            field=models.IntegerField(
                default=50,
                help_text="L'objectif fixé au niveau national par la loi Climat et résilience est de réduire de 50% la consommation d'espaces sur 2021-2031 par rapport à la décennie précédente.<br /><br />Cet objectif doit être territorialisé et peut être modulé via les documents de planification régionale ainsi que les documents d'urbanisme (SCOT, PLU(i), cartes communales).<br /><br /> Aussi, l'objectif de réduction fixé à défaut à -50% est indicatif et ne correspond pas nécessairement à l'objectif qui sera fixé pour le territoire sélectionné.",  # noqa: E501
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Objectif de réduction à 2031 (en %)",
            ),
        ),
    ]
