# Generated by Django 4.2.7 on 2024-02-14 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0065_rename_async_add_neighboors_done_historicalproject_async_add_similar_lands_done_and_more"),
        ("project", "0067_alter_historicalproject_history_user"),
    ]

    operations = []
