# Generated by Django 4.2.7 on 2024-02-14 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0068_merge_20240214_1612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalproject",
            old_name="land_ids",
            new_name="land_id",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="land_ids",
            new_name="land_id",
        ),
    ]
