# Generated by Django 4.2.7 on 2024-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0069_remove_historicalproject_land_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="land_id",
            field=models.CharField(
                blank=True,
                help_text="Contient l'indentifiant du territoire du diagnostic. Il faut croiser cette donnée avec 'land_type' pour être en mesure de de récupérer dans la base l'instances correspondante.",  # noqa: E501
                max_length=255,
                null=True,
                verbose_name="Identifiants du territoire du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="land_id",
            field=models.CharField(
                blank=True,
                help_text="Contient l'indentifiant du territoire du diagnostic. Il faut croiser cette donnée avec 'land_type' pour être en mesure de de récupérer dans la base l'instances correspondante.",  # noqa: E501
                max_length=255,
                null=True,
                verbose_name="Identifiants du territoire du diagnostic",
            ),
        ),
    ]
