# Generated by Django 4.2.9 on 2024-03-18 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0067_alter_historicalproject_target_2031_and_more"),
        (
            "project",
            "0071_rename_async_add_similar_lands_done_historicalproject_async_add_comparison_lands_done_and_more",
        ),
    ]

    operations = []
