# Generated by Django 4.2.9 on 2024-04-17 10:49

from django.db import migrations
from project.models.enums import ProjectChangeReason

VALUES_TO_UPDATE = {
    "Remove look a like": ProjectChangeReason.USER_REMOVED_A_LOOK_A_LIKE,
    "new_ocsge_has_been_delivered": ProjectChangeReason.NEW_OCSGE_HAS_BEEN_DELIVERED,
    "update_project_period": ProjectChangeReason.USER_UPDATED_PROJECT_FROM_PARAMS,
    "add look a like": ProjectChangeReason.USER_ADDED_A_LOOK_A_LIKE,
    "set folder_name": ProjectChangeReason.FOLDER_CHANGED,
    "create_from_public_key": ProjectChangeReason.CREATED_FROM_PUBLIC_KEY,
    "user_updated_project_from_params": ProjectChangeReason.USER_UPDATED_PROJECT_FROM_PARAMS,
    "update_project": ProjectChangeReason.USER_UPDATED_PROJECT_FROM_PARAMS,
    "user_updated_period_from_params": ProjectChangeReason.USER_UPDATED_PROJECT_FROM_PARAMS,
    "Claim": ProjectChangeReason.USER_CLAIMED_PROJECT,
}


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0072_merge_20240318_1326"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            UPDATE  project_historicalproject
            SET     history_change_reason = '{new}'
            WHERE   history_change_reason = '{old}';
        """
        )
        for old, new in VALUES_TO_UPDATE.items()
    ]
