# Generated by Django 4.2.9 on 2024-04-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0072_merge_20240318_1326"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS trajectory_trajectory;",
        )
    ]
