# Generated by Django 4.2.9 on 2024-04-18 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0073_auto_20240417_1049"),
        ("project", "0073_auto_20240418_1144"),
    ]

    operations = []
