# Generated by Django 4.2.11 on 2024-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0074_merge_0073_auto_20240417_1049_0073_auto_20240418_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2018",
                max_length=4,
                verbose_name="Année de fin de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Année de début de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_end_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2018",
                max_length=4,
                verbose_name="Année de fin de période du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analyse_start_date",
            field=models.CharField(
                choices=[
                    ("2009", "2009"),
                    ("2010", "2010"),
                    ("2011", "2011"),
                    ("2012", "2012"),
                    ("2013", "2013"),
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2015",
                max_length=4,
                verbose_name="Année de début de période du diagnostic",
            ),
        ),
    ]
