# Generated by Django 4.2.11 on 2024-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0076_alter_historicalrequest_requested_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="requested_document",
            field=models.CharField(
                choices=[("rapport-complet", "Rapport complet"), ("rapport-local", "Rapport local")],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_document",
            field=models.CharField(
                choices=[("rapport-complet", "Rapport complet"), ("rapport-local", "Rapport local")],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
    ]
