# Generated by Django 4.2.11 on 2024-05-08 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0075_alter_historicalproject_analyse_end_date_and_more"),
        ("project", "0077_alter_historicalrequest_requested_document_and_more"),
    ]

    operations = []
