# Generated by Django 4.2.13 on 2024-06-05 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0078_merge_20240508_1022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="emprise_origin",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="shape_file",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="emprise_origin",
        ),
        migrations.RemoveField(
            model_name="project",
            name="shape_file",
        ),
    ]
