# Generated by Django 4.2.7 on 2024-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0078_merge_20240508_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport conso"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport conso"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
    ]
