# Generated by Django 4.2.13 on 2024-06-07 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0079_historicalrequest_competence_urba_and_more"),
        ("project", "0079_remove_historicalproject_description_and_more"),
    ]

    operations = []
