# Generated by Django 4.2.7 on 2024-06-07 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0079_alter_historicalrequest_requested_document_and_more"),
        ("project", "0079_remove_historicalproject_description_and_more"),
    ]

    operations = []
