# Generated by Django 4.2.7 on 2024-06-07 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0080_merge_20240607_1001"),
        ("project", "0080_merge_20240607_1045"),
    ]

    operations = []
