# Generated by Django 4.2.13 on 2024-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0081_merge_20240607_1127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="competence_urba",
            field=models.BooleanField(
                default=False, verbose_name="Le territoire a-t-il la compétence urbanisme (au moment de la demande)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="du_en_cours",
            field=models.BooleanField(
                default=False,
                verbose_name="Le document d'urbanisme du territoire est-il en cours de revision (au moment de la demande)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport de consommation"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="competence_urba",
            field=models.BooleanField(
                default=False, verbose_name="Le territoire a-t-il la compétence urbanisme (au moment de la demande)"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="du_en_cours",
            field=models.BooleanField(
                default=False,
                verbose_name="Le document d'urbanisme du territoire est-il en cours de revision (au moment de la demande)",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport de consommation"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                verbose_name="Document demandé",
            ),
        ),
    ]
