# Generated by Django 4.2.7 on 2024-06-17 15:59

from django.db import migrations, models


def ventilate_project_request_organisms(apps, schema_editor):
    Request = apps.get_model("project", "Request")
    HistoricalRequest = apps.get_model("project", "HistoricalRequest")

    mapping = {
        "AMENAG": "AUTRE",
        "EPF": "AUTRE",
        "GIP": "AUTRE",
        "DEPART": "DDT",
        "REGION": "DREAL",
    }

    for old, new in mapping.items():
        Request.objects.filter(organism=old).update(organism=new)
        HistoricalRequest.objects.filter(organism=old).update(organism=new)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0082_alter_historicalrequest_competence_urba_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DDTM", "DDTM"),
                    ("DEAL", "DEAL"),
                    ("DREAL", "DREAL"),
                    ("DRIEAT", "DRIEAT"),
                    ("EPCI", "EPCI"),
                    ("PARTIC", "Particulier"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=30,
                verbose_name="Organisme",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DDTM", "DDTM"),
                    ("DEAL", "DEAL"),
                    ("DREAL", "DREAL"),
                    ("DRIEAT", "DRIEAT"),
                    ("EPCI", "EPCI"),
                    ("PARTIC", "Particulier"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=30,
                verbose_name="Organisme",
            ),
        ),
        migrations.RunPython(ventilate_project_request_organisms),
    ]
