# Generated by Django 4.2.13 on 2024-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0084_rnupackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rnupackage",
            name="departement_official_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
