# Generated by Django 4.2.13 on 2024-06-27 12:15

from django.db import migrations


def move_theme_map_conso_to_landstaticfigure(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    LandStaticFigure = apps.get_model("public_data", "LandStaticFigure")

    for project in (
        Project.objects.all()
        .filter(land_id__isnull=False)
        .only(
            "analyse_start_date",
            "analyse_end_date",
            "first_year_ocsge",
            "last_year_ocsge",
            "look_a_like",
            "name",
            "territory_name",
            "level",
            "target_2031",
            "theme_map_conso",
            "land_type",
            "land_id",
        )
        .iterator()
    ):
        params = {
            "analyse_start_date": project.analyse_end_date,
            "analyse_end_date": project.analyse_end_date,
            "first_year_ocsge": project.last_year_ocsge,
            "last_year_ocsge": project.last_year_ocsge,
            "look_a_like": project.look_a_like,
            "name": project.name,
            "territory_name": project.territory_name,
            "level": project.level,
            "target_2031": project.target_2031,
        }
        params_hash = str(hash(frozenset(params.items())))
        if project.theme_map_conso:
            LandStaticFigure.objects.create(
                land_type=project.land_type,
                land_id=project.land_id,
                figure=project.theme_map_conso,
                figure_name="theme_map_conso",
                params=params,
                params_hash=params_hash,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0084_remove_historicalproject_cover_image_and_more"),
    ]

    operations = [
        migrations.RunPython(
            move_theme_map_conso_to_landstaticfigure,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="theme_map_conso",
        ),
        migrations.RemoveField(
            model_name="project",
            name="theme_map_conso",
        ),
    ]
