# Generated by Django 4.2.13 on 2024-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0085_alter_rnupackage_departement_official_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rnupackage",
            name="app_version",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
