# Generated by Django 4.2.13 on 2024-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0086_rnupackage_app_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rnupackage",
            name="file",
            field=models.FileField(upload_to="rnu_packages"),
        ),
    ]
