# Generated by Django 4.2.13 on 2024-09-30 09:42

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0089_rnupackagerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="first_name",
            field=models.CharField(
                max_length=150, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="function",
            field=models.CharField(
                max_length=250, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Fonction"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="last_name",
            field=models.CharField(
                max_length=150, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DDTM", "DDTM"),
                    ("DEAL", "DEAL"),
                    ("DREAL", "DREAL"),
                    ("DRIEAT", "DRIEAT"),
                    ("EPCI", "EPCI"),
                    ("PARTIC", "Particulier"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Organisme",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport de consommation"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Document demandé",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="first_name",
            field=models.CharField(
                max_length=150, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="function",
            field=models.CharField(
                max_length=250, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Fonction"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="last_name",
            field=models.CharField(
                max_length=150, null=True, validators=[utils.validators.is_alpha_validator], verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="organism",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Agence d'urbanisme"),
                    ("ASSOCI", "Association"),
                    ("BUREAU", "Bureau d'études"),
                    ("COMMUN", "Commune"),
                    ("DDT", "DDT"),
                    ("DDTM", "DDTM"),
                    ("DEAL", "DEAL"),
                    ("DREAL", "DREAL"),
                    ("DRIEAT", "DRIEAT"),
                    ("EPCI", "EPCI"),
                    ("PARTIC", "Particulier"),
                    ("SCOT", "SCOT"),
                    ("AUTRE", "Autre"),
                ],
                default="COMMUN",
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Organisme",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_document",
            field=models.CharField(
                choices=[
                    ("rapport-conso", "Rapport de consommation"),
                    ("rapport-complet", "Rapport complet"),
                    ("rapport-local", "Rapport local"),
                ],
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Document demandé",
            ),
        ),
    ]
