# Generated by Django 4.2.13 on 2024-10-01 09:14

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0091_auto_20240930_1152"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="couverture_usage",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="import_date",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="import_error",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="import_status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="couverture_usage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="import_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="import_error",
        ),
        migrations.RemoveField(
            model_name="project",
            name="import_status",
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(
                max_length=100, validators=[utils.validators.is_alpha_validator], verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="territory_name",
            field=models.CharField(
                blank=True,
                help_text="C'est le nom qui est utilisé pour désigner votre territoire, notamment dans le rapport word.",
                max_length=250,
                null=True,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=100, validators=[utils.validators.is_alpha_validator], verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="territory_name",
            field=models.CharField(
                blank=True,
                help_text="C'est le nom qui est utilisé pour désigner votre territoire, notamment dans le rapport word.",
                max_length=250,
                null=True,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Territoire",
            ),
        ),
    ]
