# Generated by Django 4.2.13 on 2024-10-16 20:17

from django.db import migrations


def set_land_id_from_primary_keys_to_natural_key(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    for project in Project.objects.all():
        project.land_id = project.land.official_id
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0093_auto_20241016_2205"),
    ]

    operations = []
