# Generated by Django 4.2.13 on 2024-10-16 20:21

from django.db import migrations
from public_data.models import AdminRef


def modify_lookalike_from_primary_keys_to_natural_key(apps, schema_editor):  # noqa: C901
    Project = apps.get_model("project", "Project")
    for project in Project.objects.all():
        land_keys = []
        for land in project.look_a_like.split(";"):
            if not project.id:
                # Project has been deleted
                continue
            if not land:
                project.delete()
                continue
            land_type, land_id = land.split("_")
            klass = None
            if land_type == AdminRef.COMMUNE:
                try:
                    klass = apps.get_model("public_data", "Commune")
                    new_land_id = klass.objects.get(id=land_id).insee
                except klass.DoesNotExist:
                    project.delete()
                    continue
            elif land_type == AdminRef.EPCI:
                try:
                    klass = apps.get_model("public_data", "Epci")
                    new_land_id = klass.objects.get(id=land_id).source_id
                except klass.DoesNotExist:
                    project.delete()
                    continue
            elif land_type == AdminRef.DEPARTEMENT:
                try:
                    klass = apps.get_model("public_data", "Departement")
                    new_land_id = klass.objects.get(id=land_id).source_id
                except klass.DoesNotExist:
                    project.delete()
                    continue
            elif land_type == AdminRef.REGION:
                try:
                    klass = apps.get_model("public_data", "Region")
                    new_land_id = klass.objects.get(id=land_id).source_id
                except klass.DoesNotExist:
                    project.delete()
                    continue
            else:
                project.delete()
                continue
            land_keys.append(f"{land_type}_{new_land_id}")
        project.look_a_like = ";".join(land_keys)
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0094_auto_20241016_2217"),
    ]

    operations = [migrations.RunPython(modify_lookalike_from_primary_keys_to_natural_key)]
