# Generated by Django 4.2.13 on 2024-10-16 20:21

from django.db import migrations


def modify_lookalike_from_primary_keys_to_natural_key(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    for project in Project.objects.all():
        lands = project.get_look_a_like()
        land_keys = []
        for land in lands:
            land_keys.append(f"{land.type}_{land.official_id}")
        project.look_a_like = ";".join(land_keys)
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0094_auto_20241016_2217"),
    ]

    operations = []
