# Generated by Django 4.2.13 on 2024-10-16 20:21

from django.db import migrations
from public_data.models import AdminRef


def modify_lookalike_from_primary_keys_to_natural_key(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    for project in Project.objects.all():
        land_keys = []
        for land in project.look_a_like.split(";"):
            if not land:
                raise ValueError("Empty land key")
            land_type, land_id = land.split("_")
            klass = None
            if land_type == AdminRef.COMMUNE:
                klass = apps.get_model("public_data", "Commune")
                new_land_id = klass.objects.get(id=land_id).insee
            elif land_type == AdminRef.EPCI:
                klass = apps.get_model("public_data", "Epci")
                new_land_id = klass.objects.get(id=land_id).source_id
            elif land_type == AdminRef.DEPARTEMENT:
                klass = apps.get_model("public_data", "Departement")
                new_land_id = klass.objects.get(id=land_id).source_id
            elif land_type == AdminRef.REGION:
                klass = apps.get_model("public_data", "Region")
                new_land_id = klass.objects.get(id=land_id).source_id
            else:
                raise ValueError(f"Unknown land type: {land_type}")
            land_keys.append(f"{land_type}_{new_land_id}")
        project.look_a_like = ";".join(land_keys)
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0094_auto_20241016_2217"),
    ]

    operations = [migrations.RunPython(modify_lookalike_from_primary_keys_to_natural_key)]
