# Generated by Django 4.2.13 on 2024-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0095_auto_20241016_2221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="land_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifiants du territoire du diagnostic"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="look_a_like",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Territoire pour se comparer"),
        ),
        migrations.AlterField(
            model_name="project",
            name="land_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifiants du territoire du diagnostic"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="look_a_like",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Territoire pour se comparer"),
        ),
    ]
