# Generated by Django 4.2.13 on 2024-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0096_alter_historicalproject_land_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcommune",
            name="commune_insee",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Code INSEE"),
        ),
    ]
