# Generated by Django 4.2.13 on 2024-10-22 08:51

from django.db import migrations


def modify_project_commune_from_primary_keys_to_natural_key(apps, schema_editor):
    ProjectCommune = apps.get_model("project", "ProjectCommune")
    for project_commune in ProjectCommune.objects.all():
        commune = project_commune.commune
        project_commune.commune_insee = commune.insee
        project_commune.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0097_projectcommune_commune_insee"),
    ]

    operations = [migrations.RunPython(modify_project_commune_from_primary_keys_to_natural_key)]
