# Generated by Django 4.2.13 on 2024-10-22 08:51

from django.db import migrations, connection


def modify_project_commune_from_primary_keys_to_natural_key(apps, schema_editor):
    with connection.cursor() as cursor:
        with connection.cursor() as cursor:
            sql = """
                UPDATE project_projectcommune as ppc
                SET commune_insee = (
                    SELECT insee FROM public_data_commune
                    WHERE id = (
                        SELECT commune_id FROM
                        project_projectcommune
                        WHERE id = ppc.id
                        LIMIT 1
                    )
                    LIMIT 1
                )


                """
            cursor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0097_projectcommune_commune_insee"),
    ]

    operations = [migrations.RunPython(modify_project_commune_from_primary_keys_to_natural_key)]
