# Generated by Django 4.2.13 on 2024-10-22 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0100_auto_20241022_1100"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectcommune",
            name="commune_insee",
        ),
    ]
