# Generated by Django 4.2.13 on 2024-11-20 15:10

import config.storages
from django.db import migrations, models
import project.models.project_base


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0101_remove_projectcommune_commune_insee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.PublicMediaStorage(),
                upload_to=project.models.project_base.get_path_in_version_folder,
            ),
        ),
    ]
