# Generated by Django 4.2.13 on 2024-11-26 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0101_remove_projectcommune_commune_insee"),
    ]

    operations = []
