# Generated by Django 4.2.13 on 2024-11-21 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0191_landconso_landconsocomparison_landconsostats_landpop_and_more"),
        ("project", "0101_remove_projectcommune_commune_insee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_theme_map_gpu_done",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="theme_map_gpu",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_theme_map_gpu_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="theme_map_gpu",
        ),
    ]
