# Generated by Django 4.2.13 on 2024-11-28 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0102_alter_projectcommune_commune"),
        ("project", "0102_remove_historicalproject_async_theme_map_gpu_done_and_more"),
    ]

    operations = []
