# Generated by Django 4.2.13 on 2024-11-26 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0192_landconso_landconsocomparison_landconsostats_landpop_and_more"),
        ("project", "0102_alter_projectcommune_commune"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_set_combined_emprise_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_set_combined_emprise_done",
        ),
    ]
