# Generated by Django 4.2.13 on 2024-11-28 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0192_landconso_landconsocomparison_landconsostats_landpop_and_more"),
        ("project", "0102_alter_projectcommune_commune"),
    ]

    operations = []
