# Generated by Django 4.2.13 on 2024-11-26 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0192_landconso_landconsocomparison_landconsostats_landpop_and_more"),
        ("project", "0103_remove_historicalproject_async_set_combined_emprise_done_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Emprise",
        ),
    ]
