# Generated by Django 4.2.13 on 2024-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0103_alter_historicalproject_land_type_and_more"),
        ("project", "0103_merge_20241128_1446"),
    ]

    operations = []
