# Generated by Django 4.2.17 on 2025-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0194_autorisationlogement_logementvacant"),
        ("project", "0105_alter_historicalproject_land_type_and_more"),
    ]

    operations = []
