# Generated by Django 4.2.13 on 2025-02-10 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0195_artifzonage_delete_artifareazoneurba"),
        ("project", "0106_alter_projectcommune_commune"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_theme_map_fill_gpu_done",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="theme_map_fill_gpu",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_theme_map_fill_gpu_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="theme_map_fill_gpu",
        ),
    ]
