# Generated by Django 4.2.20 on 2025-05-15 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0198_artifzonageindex_landartifstock_and_more"),
        ("project", "0108_remove_historicalproject_async_find_first_and_last_ocsge_done_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_add_city_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_add_city_done",
        ),
    ]
