# Generated by Django 4.2.20 on 2025-05-22 16:43

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("public_data", "0198_artifzonageindex_landartifstock_and_more"),
        ("project", "0109_remove_historicalproject_async_add_city_done_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="cities",
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="organism",
            field=models.CharField(
                choices=[
                    ("COMMUNE", "Commune"),
                    ("EPCI", "EPCI"),
                    ("SCOT", "SCoT"),
                    ("SERVICES_REGIONAUX", "DREAL / DRIEAT / DRIHL"),
                    ("SERVICES_DEPARTEMENTAUX", "DDT / DDTM / DEAL"),
                    ("EXPERTS_URBANISTES", "Bureaux d'études / Agence d'urbanisme"),
                    ("ACTEURS_CITOYENS", "Association / Particulier"),
                ],
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Organisme",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="organism",
            field=models.CharField(
                choices=[
                    ("COMMUNE", "Commune"),
                    ("EPCI", "EPCI"),
                    ("SCOT", "SCoT"),
                    ("SERVICES_REGIONAUX", "DREAL / DRIEAT / DRIHL"),
                    ("SERVICES_DEPARTEMENTAUX", "DDT / DDTM / DEAL"),
                    ("EXPERTS_URBANISTES", "Bureaux d'études / Agence d'urbanisme"),
                    ("ACTEURS_CITOYENS", "Association / Particulier"),
                ],
                max_length=30,
                validators=[utils.validators.is_alpha_validator],
                verbose_name="Organisme",
            ),
        ),
    ]
