# Generated by Django 4.2.20 on 2025-05-22 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0110_remove_project_cities_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectCommune",
        ),
    ]
