# Generated by Django 4.2.20 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0112_historicalrequest_service_request_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESPONSABLE_URBANISME", "Chargé(e) ou responsable de mission urbanisme"),
                    ("RESPONSABLE_PLANIFICATION", "Chargé(e) ou responsable de planification"),
                    ("RESPONSABLE_AMENAGEMENT", "Chargé(e) aménagement"),
                    ("SECRETAIRE_MAIRIE", "Secrétaire de mairie (commune)"),
                    ("ELU", "Élu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Fonction",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMENAGEMENT_URBANISME_ET_PAYSAGE", "Aménagement Urbanisme et Paysage"),
                    ("ETUDES_ET_EVALUATIONS", "Etudes et évaluations"),
                    ("SECURITE_PREVENTION_ET_GESTION_DES_RISQUES", "Sécurité Prévention et Gestion des Risques"),
                    (
                        "ELABORATION_ET_PILOTAGE_DE_POLITIQUES_PUBLIQUES",
                        "Elaboration et pilotage de politiques publiques",
                    ),
                    ("RESSOURCES_NATURELLES_ET_BIODIVERSITE", "Ressources naturelles et biodiversité"),
                    ("HABITAT_LOGEMENT", "Habitat Logement"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESPONSABLE_URBANISME", "Chargé(e) ou responsable de mission urbanisme"),
                    ("RESPONSABLE_PLANIFICATION", "Chargé(e) ou responsable de planification"),
                    ("RESPONSABLE_AMENAGEMENT", "Chargé(e) aménagement"),
                    ("SECRETAIRE_MAIRIE", "Secrétaire de mairie (commune)"),
                    ("ELU", "Élu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Fonction",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMENAGEMENT_URBANISME_ET_PAYSAGE", "Aménagement Urbanisme et Paysage"),
                    ("ETUDES_ET_EVALUATIONS", "Etudes et évaluations"),
                    ("SECURITE_PREVENTION_ET_GESTION_DES_RISQUES", "Sécurité Prévention et Gestion des Risques"),
                    (
                        "ELABORATION_ET_PILOTAGE_DE_POLITIQUES_PUBLIQUES",
                        "Elaboration et pilotage de politiques publiques",
                    ),
                    ("RESSOURCES_NATURELLES_ET_BIODIVERSITE", "Ressources naturelles et biodiversité"),
                    ("HABITAT_LOGEMENT", "Habitat Logement"),
                    ("AUTRE", "Autre"),
                ],
                max_length=250,
                null=True,
                verbose_name="Service",
            ),
        ),
    ]
