# Generated by Django 4.2.20 on 2025-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0113_alter_historicalrequest_function_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrequest",
            name="function",
        ),
        migrations.RemoveField(
            model_name="historicalrequest",
            name="organism",
        ),
        migrations.RemoveField(
            model_name="historicalrequest",
            name="service",
        ),
        migrations.RemoveField(
            model_name="request",
            name="function",
        ),
        migrations.RemoveField(
            model_name="request",
            name="organism",
        ),
        migrations.RemoveField(
            model_name="request",
            name="service",
        ),
    ]
