# Generated by Django 4.2.20 on 2025-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0114_remove_historicalrequest_function_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprise",
            name="srid_source",
            field=models.IntegerField(
                choices=[
                    (2154, "France Métropolitaine et Corse"),
                    (32620, "Guadeloupe et Martinique"),
                    (2972, "Guyane Française"),
                    (2975, "La réunion"),
                    (4471, "Mayotte"),
                    (4326, "Monde (GPS)"),
                    (3857, "Monde (Google Maps, OpenStreetMap etc.)"),
                ],
                default=2154,
                verbose_name="SRID",
            ),
        ),
    ]
