# Generated by Django 4.2.20 on 2025-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0115_alter_emprise_srid_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_add_comparison_lands_done",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_cover_image_done",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_generate_theme_map_conso_done",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="async_set_combined_emprise_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_add_comparison_lands_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_cover_image_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_generate_theme_map_conso_done",
        ),
        migrations.RemoveField(
            model_name="project",
            name="async_set_combined_emprise_done",
        ),
    ]
