# Generated by Django 4.2.23 on 2025-12-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0116_remove_historicalproject_async_add_comparison_lands_done_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="look_a_like",
        ),
        migrations.RemoveField(
            model_name="project",
            name="look_a_like",
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="comparison_lands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des territoires de comparaison",
                verbose_name="Territoires de comparaison",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="comparison_lands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des territoires de comparaison",
                verbose_name="Territoires de comparaison",
            ),
        ),
        migrations.CreateModel(
            name="ReportDraft",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("rapport-conso", "Rapport de consommation"),
                            ("rapport-complet", "Rapport complet"),
                            ("rapport-local", "Rapport local"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.JSONField(default=dict)),
                (
                    "land_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMM", "Commune"),
                            ("EPCI", "EPCI"),
                            ("DEPART", "Département"),
                            ("SCOT", "SCoT"),
                            ("REGION", "Région"),
                            ("NATION", "Nation"),
                            ("COMP", "Composite"),
                        ],
                        max_length=7,
                        null=True,
                        verbose_name="Type de territoire",
                    ),
                ),
                (
                    "land_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Identifiant du territoire"),
                ),
                (
                    "comparison_lands",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des territoires de comparaison",
                        verbose_name="Territoires de comparaison",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report_drafts", to="project.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brouillon de rapport",
                "verbose_name_plural": "Brouillons de rapports",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="historicalrequest",
            name="report_draft",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.reportdraft",
                verbose_name="Brouillon de rapport",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="report_draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="download_requests",
                to="project.reportdraft",
                verbose_name="Brouillon de rapport",
            ),
        ),
    ]
