# Generated by Django 4.2.23 on 2025-12-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models.export_job
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0116_remove_historicalproject_async_add_comparison_lands_done_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En cours"), ("completed", "Terminé"), ("failed", "Échec")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to=project.models.export_job.export_pdf_path),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["job_id"], name="project_exp_job_id_8a6948_idx"),
                    models.Index(fields=["user", "status"], name="project_exp_user_id_1e67d1_idx"),
                ],
            },
        ),
    ]
