# Generated by Django 5.2.9 on 2025-12-15 13:42

import project.models.export_job
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0117_add_export_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to=project.models.export_job.export_pdf_path),
        ),
    ]
