# Generated by Django 5.2.9 on 2025-12-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0118_alter_exportjob_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="land_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="land_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[("rapport-complet", "Rapport complet"), ("rapport-local", "Rapport local")],
                max_length=30,
            ),
        ),
    ]
