# Generated by Django 4.2.23 on 2025-12-16 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0117_remove_historicalproject_look_a_like_and_more"),
        ("project", "0119_add_land_and_report_type_to_exportjob"),
    ]

    operations = []
