# Generated by Django 5.2.9 on 2026-01-20 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0121_target_2031_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                default="EPCI",
                help_text="Indique le niveau administratif des territoires sélectionnés par l'utilisateur lors de la création du diagnostic. Cela va de la commune à la région.",
                max_length=7,
                null=True,
                verbose_name="Type de territoire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                default="COMMUNE",
                help_text="Utilisé dans les rapports afin de déterminer le niveau d'aggrégation des données à afficher. Si EPCI est sélectionné, alors les rapports montre des données EPCI par EPCI.",
                max_length=7,
                verbose_name="Niveau d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="target_2031",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="L'objectif fixé au niveau national par la loi Climat et résilience est de réduire de 50% la consommation d'espaces sur 2021-2031 par rapport à la décennie précédente.<br /><br />Cet objectif doit être territorialisé et peut être modulé via les documents de planification régionale ainsi que les documents d'urbanisme (SCOT, PLU(i), cartes communales).<br /><br /> Aussi, l'objectif de réduction fixé à défaut à -50% est indicatif et ne correspond pas nécessairement à l'objectif qui sera fixé pour le territoire sélectionné.",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Objectif de réduction à 2031 (en %)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                default="EPCI",
                help_text="Indique le niveau administratif des territoires sélectionnés par l'utilisateur lors de la création du diagnostic. Cela va de la commune à la région.",
                max_length=7,
                null=True,
                verbose_name="Type de territoire",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                default="COMMUNE",
                help_text="Utilisé dans les rapports afin de déterminer le niveau d'aggrégation des données à afficher. Si EPCI est sélectionné, alors les rapports montre des données EPCI par EPCI.",
                max_length=7,
                verbose_name="Niveau d'analyse",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_2031",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="L'objectif fixé au niveau national par la loi Climat et résilience est de réduire de 50% la consommation d'espaces sur 2021-2031 par rapport à la décennie précédente.<br /><br />Cet objectif doit être territorialisé et peut être modulé via les documents de planification régionale ainsi que les documents d'urbanisme (SCOT, PLU(i), cartes communales).<br /><br /> Aussi, l'objectif de réduction fixé à défaut à -50% est indicatif et ne correspond pas nécessairement à l'objectif qui sera fixé pour le territoire sélectionné.",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Objectif de réduction à 2031 (en %)",
            ),
        ),
        migrations.AlterField(
            model_name="reportdraft",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMM", "Commune"),
                    ("EPCI", "EPCI"),
                    ("DEPART", "Département"),
                    ("SCOT", "SCoT"),
                    ("REGION", "Région"),
                    ("NATION", "Nation"),
                    ("COMP", "Composite"),
                    ("CUSTOM", "Personnalisé"),
                ],
                max_length=7,
                null=True,
                verbose_name="Type de territoire",
            ),
        ),
    ]
