# Generated by Django 5.2.11 on 2026-02-18 13:29

import config.storages
import django.core.validators
import django.db.models.deletion
import project.models.export_job
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0122_alter_historicalproject_land_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportdraft",
            name="project",
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                storage=config.storages.ExportStorage(),
                upload_to=project.models.export_job.export_pdf_path,
            ),
        ),
        migrations.CreateModel(
            name="UserLandPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("land_id", models.CharField(max_length=255, verbose_name="Identifiant du territoire")),
                ("land_type", models.CharField(max_length=7, verbose_name="Type de territoire")),
                (
                    "target_2031",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Objectif de reduction a 2031 (en %)",
                    ),
                ),
                (
                    "comparison_lands",
                    models.JSONField(blank=True, default=list, verbose_name="Territoires de comparaison"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference utilisateur par territoire",
                "verbose_name_plural": "Preferences utilisateur par territoire",
                "unique_together": {("user", "land_id", "land_type")},
            },
        ),
    ]
