# Generated by Django 5.2.11 on 2026-02-20 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0123_remove_project_from_report_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rnupackagerequest",
            name="rnu_package",
        ),
        migrations.RemoveField(
            model_name="rnupackagerequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="RNUPackage",
        ),
        migrations.DeleteModel(
            name="RNUPackageRequest",
        ),
    ]
