
version: 2

models:
  - name: app_commune
  - name: app_departement
  - name: app_region
  - name: app_epci
  - name: app_scot
  - name: app_usagesol
  - name: app_couverturesol
  - name: app_couvertureusagematrix

sources:
  - name: public
    tables:
    - name: app_commune
    - name: app_departement
    - name: app_region
    - name: app_epci
    - name: app_scot
    - name: app_usagesol
    - name: app_couverturesol
    - name: app_couvertureusagematrix
