name: 'sparte'
version: '1.0.0'
profile: 'sparte'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  sparte:
    app:
      +schema: app
    ocsge:
      +schema: ocsge
    admin_express:
      +schema: admin_express
    gpu:
      +schema: gpu
    majic:
      +schema: majic
    dgaln:
      +schema: sudocuh
