name: 'sparte'
version: '1.0.0'
profile: 'sparte'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  sparte:
    for_app:
    REGION: "REGION"
    DEPARTEMENT: "DEPART"
    SCOT: "SCOT"
    EPCI: "EPCI"
    COMMUNE: "COMM"
    COMPOSITE: "COMP"
    NATION: "NATION"

models:
  +grants:
    select: ["alexis", "sofian", "metabase", "scaleway_server", "matomo"]
    insert: ["alexis", "sofian", "scaleway_server"]
    update: ["alexis", "sofian", "scaleway_server"]
  sparte:
    analytics:
      +schema: analytics
    app:
      +schema: app
    ocsge:
      +schema: ocsge
    admin_express:
      +schema: admin_express
    gpu:
      +schema: gpu
    majic:
      +schema: majic
    sudocuh:
      +schema: sudocuh
    insee:
      +schema: insee
    for_brevo:
      +schema: for_brevo
    for_app:
      +schema: for_app
    for_export:
      +schema: for_export
    for_vector_tiles:
      +schema: for_vector_tiles
    sitadel:
      +schema: sitadel
    rpls:
      +schema: rpls
    zlv:
      +schema: zlv
    cartofriches:
      +schema: cartofriches
    matomo:
      +schema: matomo
    land:
      +schema: land
