name: 'sparte'
version: '1.0.0'
profile: 'sparte'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  sparte:
    for_app:
    REGION: "REGION"
    DEPARTEMENT: "DEPART"
    SCOT: "SCOT"
    EPCI: "EPCI"
    COMMUNE: "COMM"
    COMPOSITE: "COMP"
    NATION: "NATION"

models:
  sparte:
    app:
      +schema: app
    ocsge:
      +schema: ocsge
    admin_express:
      +schema: admin_express
    gpu:
      +schema: gpu
    majic:
      +schema: majic
    sudocuh:
      +schema: sudocuh
    insee:
      +schema: insee
    for_app:
      +schema: for_app
    sitadel:
      +schema: sitadel
