# Generated by Django 3.2.5 on 2021-09-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
