version: 2

valid_srids: &valid_srids
  values: [ 32620, 2972, 2975, 2154, 4471 ]

models:
  - name: for_app_departement
    columns:
      - name: source_id
        data_tests:
          - not_null
          - unique
          - relationships:
              field: code
              to: ref('departement')
        data_type: character varying
      - name: name
        data_tests:
          - not_null
          - unique
        data_type: character varying
      - name: region_id
        data_tests:
          - not_null
          - relationships:
              field: code
              to: ref('region')
        data_type: character varying
      - name: is_artif_ready
        data_tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
        data_type: boolean
      - name: mpoly
        data_tests:
          - not_null
          - unique
          - is_valid_geom
          - is_not_empty_geom
          - is_srid_4326
        data_type: user-defined
      - name: srid_source
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 32620
                - 2972
                - 2975
                - 2154
                - 4471
        data_type: integer
      - name: ocsge_millesimes
        data_type: array
      - name: autorisation_logement_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
      - name: logements_vacants_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
  - name: for_app_commune
    columns:
      - name: competence_planification
        data_tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
        data_type: boolean
      - name: insee
        data_tests:
          - not_null
          - unique
          - relationships:
              field: code
              to: ref('commune')
        data_type: character varying
      - name: departement_id
        data_tests:
          - not_null
          - relationships:
              field: source_id
              to: ref('for_app_departement')
        data_type: character varying
      - name: name
        data_tests:
          - not_null
        data_type: character varying
      - name: srid_source
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 32620
                - 2972
                - 2975
                - 2154
                - 4471
        data_type: integer
      - name: ocsge_available
        data_tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
        data_type: boolean
      - name: area
        data_tests:
          - not_null
        data_type: double precision
      - name: mpoly
        data_tests:
          - not_null
          - unique
          - is_valid_geom
          - is_not_empty_geom
          - is_srid_4326
        data_type: user-defined
      - name: consommation_correction_status
        data_tests:
          - not_null
          - accepted_values:
              values:
                - UNCHANGED
                - DIVISION
                - FUSION
                - COG_ERROR
                - MISSING_FROM_SOURCE
        data_type: text
      - name: epci_id
        tests:
          - relationships:
              field: code
              to: ref('epci')
        data_type: character varying
      - name: ept_id
        data_type: character varying

      - name: scot_id
        data_type: text
        tests:
          - relationships:
              field: id_scot
              to: ref('scot')
      - name: first_millesime
        data_type: integer
      - name: last_millesime
        data_type: integer
      - name: surface_artif
        data_type: double precision
      - name: autorisation_logement_available
        data_type: boolean
        tests:
          - accepted_values:
              values:
                - "true"
                - "false"
          - not_null
      - name: logements_vacants_available
        data_type: boolean
        tests:
          - accepted_values:
              values:
                - "true"
                - "false"
          - not_null
  - name: for_app_epci
    columns:
      - name: source_id
        data_tests:
          - not_null
          - unique
          - relationships:
              field: code
              to: ref('epci')
        data_type: character varying
      - name: name
        data_tests:
          - not_null
        data_type: character varying
      - name: srid_source
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 32620
                - 2972
                - 2975
                - 2154
                - 4471
        data_type: integer
      - name: mpoly
        data_tests:
          - not_null
          - unique
          - is_valid_geom
          - is_not_empty_geom
          - is_srid_4326
        data_type: user-defined
      - name: autorisation_logement_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
      - name: logements_vacants_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
  - name: for_app_region
    columns:
      - name: source_id
        data_tests:
          - not_null
          - unique
          - relationships:
              field: code
              to: ref('region')
        data_type: character varying
      - name: name
        data_tests:
          - not_null
        data_type: character varying
      - name: srid_source
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 32620
                - 2972
                - 2975
                - 2154
                - 4471
        data_type: integer
      - name: mpoly
        data_tests:
          - not_null
          - unique
          - is_valid_geom
          - is_not_empty_geom
          - is_srid_4326
        data_type: user-defined
      - name: autorisation_logement_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
      - name: logements_vacants_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
  - name: for_app_scot
    columns:
      - name: siren
        data_type: text
        data_tests:
          - not_null
      - name: name
        data_tests:
          - not_null
        data_type: text
      - name: srid_source
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 32620
                - 2972
                - 2975
                - 2154
                - 4471
        data_type: integer
      - name: mpoly
        data_tests:
          - not_null
          - unique
          - is_valid_geom
          - is_not_empty_geom
          - is_srid_4326
        data_type: user-defined
      - name: source_id
        data_type: text
        tests:
          - not_null
          - relationships:
              field: id_scot
              to: ref('scot')
      - name: autorisation_logement_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
      - name: logements_vacants_available
        data_type: boolean
        tests:
          - not_null
          - accepted_values:
              values:
                - "true"
                - "false"
