version: 2

models:
  - name: desartif_flux_commune
    columns:
      - name: commune_code
        data_tests:
          - not_null
      - name: year_old
        data_tests:
          - not_null
      - name: year_new
        data_tests:
          - not_null
      - name: flux_desartif
        data_tests:
          - not_null
