# Generated by Django 4.2.4 on 2023-09-04 07:34

from django.db import migrations


def update_analysis_level(apps, schema_editor):
    StatDiagnostic = apps.get_model('metabase', 'StatDiagnostic')
    StatDiagnostic.objects.filter(analysis_level='COMMUNE').update(analysis_level='COMM')


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0006_statdiagnostic_date_first_trajectory_and_more"),
    ]

    operations = [
        migrations.RunPython(update_analysis_level, reverse_code=migrations.RunPython.noop)
    ]
