# Generated by Django 4.2.20 on 2025-09-02 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0008_remove_statdiagnostic_date_first_trajectory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statdiagnostic",
            name="group_organism",
        ),
        migrations.RemoveField(
            model_name="statdiagnostic",
            name="organism",
        ),
    ]
