
version: 2

models:
  - name: commune
  - name: commune_guadeloupe
  - name: commune_guyane
  - name: commune_martinique
  - name: commune_reunion
  - name: departement
  - name: departement_guadeloupe
  - name: departement_guyane
  - name: departement_martinique
  - name: departement_reunion

sources:
  - name: public
    tables:
    - name: commune_metropole
    - name: commune_guadeloupe
    - name: commune_guyane
    - name: commune_martinique
    - name: commune_reunion
    - name: departement_metropole
    - name: departement_guadeloupe
    - name: departement_guyane
    - name: departement_martinique
    - name: departement_reunion
    - name: epci
    - name: region
