version: 2

code_is_unique_and_not_null: &code_is_unique_and_not_null
  - name: code
    data_tests:
      - not_null
      - unique

models:
  - name: commune
    columns: *code_is_unique_and_not_null
  - name: commune_guadeloupe
    columns: *code_is_unique_and_not_null
  - name: commune_guyane
    columns: *code_is_unique_and_not_null
  - name: commune_martinique
    columns: *code_is_unique_and_not_null
  - name: commune_reunion
    columns: *code_is_unique_and_not_null
  - name: commune_metropole
    columns: *code_is_unique_and_not_null
  - name: departement
    columns: *code_is_unique_and_not_null
  - name: departement_guadeloupe
    columns: *code_is_unique_and_not_null
  - name: departement_guyane
    columns: *code_is_unique_and_not_null
  - name: departement_martinique
    columns: *code_is_unique_and_not_null
  - name: departement_reunion
    columns: *code_is_unique_and_not_null
  - name: departement_metropole
    columns: *code_is_unique_and_not_null
  - name: epci
    columns: *code_is_unique_and_not_null
  - name: epci_guadeloupe
    columns: *code_is_unique_and_not_null
  - name: epci_guyane
    columns: *code_is_unique_and_not_null
  - name: epci_martinique
    columns: *code_is_unique_and_not_null
  - name: epci_reunion
    columns: *code_is_unique_and_not_null
  - name: epci_metropole
    columns: *code_is_unique_and_not_null
  - name: region
    columns: *code_is_unique_and_not_null
  - name: region_reunion
    columns: *code_is_unique_and_not_null
  - name: region_guadeloupe
    columns: *code_is_unique_and_not_null
  - name: region_guyane
    columns: *code_is_unique_and_not_null
  - name: region_martinique
    columns: *code_is_unique_and_not_null
  - name: region_metropole
    columns: *code_is_unique_and_not_null

sources:
  - name: public
    tables:
      - name: commune_metropole
      - name: commune_guadeloupe
      - name: commune_guyane
      - name: commune_martinique
      - name: commune_reunion
      - name: departement_metropole
      - name: departement_guadeloupe
      - name: departement_guyane
      - name: departement_martinique
      - name: departement_reunion
      - name: epci_metropole
      - name: epci_guadeloupe
      - name: epci_guyane
      - name: epci_martinique
      - name: epci_reunion
      - name: region_reunion
      - name: region_guadeloupe
      - name: region_guyane
      - name: region_martinique
      - name: region_metropole
