# Generated by Django 4.2.16 on 2024-10-28 11:40
# Previously updated FAQ_URL in django_app_parameter, now a no-op (parameter moved to settings.py)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crisp", "0001_initial"),
    ]

    operations = []
