# Generated by Django 4.2.16 on 2024-10-28 11:40

from django.db import migrations


def update_faq_url(apps, schema_editor):
    Parameter = apps.get_model("django_app_parameter", "parameter")

    Parameter.objects.filter(slug="FAQ_URL").update(value="https://faq.mondiagartif.beta.gouv.fr/fr/")


class Migration(migrations.Migration):
    dependencies = [
        ("crisp", "0001_initial"),
        ("django_app_parameter", "0003_alter_parameter_value_type"),
    ]

    operations = [
        migrations.RunPython(update_faq_url),
    ]
