name: Deploy to production Airflow
on:
  push:
    branches:
      - "staging"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AIRFLOW_SSH_HOST }}
          username: ${{ secrets.AIRFLOW_SSH_USER }}
          key: ${{ secrets.AIRFLOW_SSH_KEY }}
          port: ${{ secrets.AIRFLOW_SSH_PORT }}
          script: cd ~/sparte && git pull
      - name: Generate DBT docs
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AIRFLOW_SSH_HOST }}
            username: ${{ secrets.AIRFLOW_SSH_USER }}
            key: ${{ secrets.AIRFLOW_SSH_KEY }}
            port: ${{ secrets.AIRFLOW_SSH_PORT }}
            script: cd ~/sparte/airflow/include/sql && dbt docs generate --static
