name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ staging, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: kartoza/postgis:13-3.1--v2021.09.08
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install GDAL and co
      run: |
        sudo apt install -y binutils libproj-dev gdal-bin
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install Dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pipenv install --system --deploy --ignore-pipfile --dev
    - name: Run tests
      env:
        DATABASE_URL: postgis://postgres:postgres@127.0.0.1:5432/postgres
        SECRET: publicbadsecretthatshouldnotbeusedelsewhere_wink_
      run: |
        pytest -vv
