name: Python lint and test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t app-image .
        docker save app-image | gzip > app-image.tar.gz

    - uses: actions/upload-artifact@v3
      with:
        name: app-image
        path: app-image.tar.gz

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: app-image
    - run: |
        gzip -d app-image.tar.gz
        docker load < app-image.tar
    - name: Run black
      run: docker run app-image /bin/sh -c "black --check --include='\.py$' --exclude='/migrations/' ."

    # - name: check black formatting
    #   run: pipenv run black --check --include="\.py" --exclude="env/*,0*" .

    # - name: check isort
    #   run: pipenv run isort . --check-only --skip env

    # - name: Run Tests
    #   run: |
    #     python manage.py test

    # - name: Run test suite
    #   run: |
    #     pipenv run test -svvv
    #   env:
    #     TEST_DB_HOST: localhost
    #     TEST_DB_NAME: postgres
    #     TEST_DB_PASS: postgres
    #     TEST_DB_PORT: 5432
    #     TEST_DB_USER: postgres

    # - name: Run linter
    #   run: |
    #     pipenv run lint

    # - name: Run formatting check
    #   run: |
    #     pipenv run format --check

    # - name: Setup node.js (for pyright)
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: "12"

    # - name: Run type checking
    #   run: |
    #     npm install -g pyright
    #     pipenv run typecheck
