version: 2
models:
  - name: period_flux_population_departement
    columns:
      - name: departement
        data_tests:
          - not_null
          - has_all_departements:
              severity: warn
          - relationships:
              to: ref('departement')
              field: code
