version: 2

models:
  - name: period_flux_population_region
    columns:
      - name: region
        data_tests:
          - not_null
          - has_all_regions:
              severity: warn
          - relationships:
              to: ref('region')
              field: code
